### ISSUE TITLE
Error 500 on broker tab

### ISSUE THREAD

**Issue by v1sion** [mher/flower#1005]
**Description**
I'm getting a 500 error when visiting the broker tab.

```
Uncaught exception GET /broker (127.0.0.1)
HTTPServerRequest(protocol='http', host='******', method='GET', uri='/broker', version='HTTP/1.1', remote_ip='127.0.0.1')
     Traceback (most recent call last):
       File "/opt/venv/lib/python3.7/site-packages/tornado/web.py", line 1703, in _execute
         result = await result
       File "/opt/venv/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
         yielded = next(result)
       File "/opt/venv/lib/python3.7/site-packages/flower/views/broker.py", line 33, in get
         http_api=http_api, broker_options=broker_options, broker_use_ssl=broker_use_ssl)
       File "/opt/venv/lib/python3.7/site-packages/flower/utils/broker.py", line 246, in __new__
         return RedisSsl(broker_url, *args, **kwargs)
       File "/opt/venv/lib/python3.7/site-packages/flower/utils/broker.py", line 229, in __init__
         super(RedisSsl, self).__init__(broker_url, *args, **kwargs)
       File "/opt/venv/lib/python3.7/site-packages/flower/utils/broker.py", line 143, in __init__
         self.redis = self._get_redis_client()
       File "/opt/venv/lib/python3.7/site-packages/flower/utils/broker.py", line 164, in _get_redis_client
         return redis.Redis(**self._get_redis_client_args())
       File "/opt/venv/lib/python3.7/site-packages/flower/utils/broker.py", line 234, in _get_redis_client_args
         client_args.update(self.broker_use_ssl)
     TypeError: 'NoneType' object is not iterable
```

**To Reproduce**
1. Open the browser
2. Visit the `broker` tab
3. See error

**Screenshots**

<img width="1440" alt="Screenshot 2020-07-20 at 10 14 47" src="https://user-images.githubusercontent.com/10966855/87921085-00fec300-ca72-11ea-95ce-ba5893245bd1.png">

**System information**

```
flower   -> flower:0.9.4 tornado:6.0.4 humanize:(0, 4)
software -> celery:4.4.2 (cliffs) kombu:4.6.11 py:3.7.7
            billiard:3.6.3.0 redis:3.5.2
platform -> system:Linux arch:64bit
            kernel version:4.14.177-139.253.amzn2.x86_64 imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:rediss results:rediss://:**@redis01.**:6379/0
```

**Comment by mher** [comment]
Looks like [broker_use_ssl](https://docs.celeryproject.org/en/stable/userguide/configuration.html#std:setting-broker_use_ssl) option is not properly configured in your celery configs.

**Comment by v1sion** [comment]
Hum, that's a bit weird as I'm able to connect to do broker using the ssl config as query parameters `rediss://:***@redis01.****:6379/0?ssl_cert_reqs=required`, but looks like flower can't use it like this.
If i setup the ssl config as describe [here](https://docs.celeryproject.org/en/stable/userguide/configuration.html#std:setting-broker_use_ssl) im able to get the `broker` tab from the dashboard
Thank you

**Comment by innovia** [comment]
can't get this thing to read the config file at all
