### ISSUE TITLE
Address not available 

### ISSUE THREAD

**Issue by PauloCabral-internations** [mher/flower#1032]
**Describe the bug**
When I use the flag --address and give a domain I got the error: 
`OSError: [Errno 99] Address not available`
The address that  I am passing is a real domain with a public DNS configuration. 

**To Reproduce**
1. Run flower from docker 

`docker run -p 5555:5555 mher/flower --address=<mypublicdomain.com>`

**System information**
`Traceback (most recent call last):
  File "/usr/local/bin/flower", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/flower/__main__.py", line 11, in main
    flower.execute_from_commandline()
  File "/usr/local/lib/python3.8/site-packages/celery/bin/base.py", line 305, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/local/lib/python3.8/site-packages/flower/command.py", line 56, in handle_argv
    return self.run_from_argv(prog_name, argv)
  File "/usr/local/lib/python3.8/site-packages/flower/command.py", line 51, in run_from_argv
    flower.start()
  File "/usr/local/lib/python3.8/site-packages/flower/app.py", line 60, in start
    self.listen(self.options.port, address=self.options.address,
  File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 2116, in listen
    server.listen(port, address)
  File "/usr/local/lib/python3.8/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/local/lib/python3.8/site-packages/tornado/netutil.py", line 174, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 99] Address not available
`

**Comment by mher** [comment]
Address may be either an IP address or hostname (not domain name). If it’s a hostname, the server will listen on all IP addresses associated with the name. Address may be an empty string or None to listen on all available interfaces.
