### ISSUE TITLE
I have installed flower and trying to run it gives following error

### ISSUE THREAD

**Issue by sant527** [mher/flower#1067]
I have installed flower and trying to run it gives following error

I have 

```
flower: "version": "==0.9.7"
celery: "version": "==5.0.5"
vine: "version": "==5.0.0"
python_version = "3.7"
```

When i run flower using:

```
celery -A boiler flower --address=0.0.0.0 --port=5555
```

i get 
```
Warning: entry point could not be loaded. Contact its author for help.
Traceback (most recent call last):
  File "/home/simha/app/.venv/lib/python3.7/site-packages/click_plugins/core.py", line 37, in decorator
    group.add_command(entry_point.load())
  File "/home/simha/app/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2446, in load
    self.require(*args, **kwargs)
  File "/home/simha/app/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2469, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/simha/app/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (celery 5.0.5 (/home/simha/app/.venv/lib/python3.7/site-packages), Requirement.parse('celery<5.0.0,>=4.3.0; python_version >= "3.7"'))
```

**Comment by dre2004** [comment]
Based on that message it appears flower needs celery 5.0.0 or lower and you're using 5.0.5.
