### ISSUE TITLE
api/tasks endpoint crashing with TypeError: '>=' not supported between instances of 'int' and 'NoneType'

### ISSUE THREAD

**Issue by Tomasz-Kluczkowski** [mher/flower#1088]
**Describe the bug**
Hi,

When running flower 0.97 to monitor my celery workers (3 workers, 3 queues if that changes anything) and accessing the `api/tasks` endpoint , flower raises an exception:

```
TypeError: '>=' not supported between instances of 'int' and 'NoneType'
2021-03-29 18:36:38,233 ERROR   [web.py:log_exception] Uncaught exception GET /api/tasks (::1)
HTTPServerRequest(protocol='http', host='localhost:5555', method='GET', uri='/api/tasks', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Users/tomaszkluczkowski/envs/platform/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/Users/tomaszkluczkowski/envs/platform/lib/python3.9/site-packages/tornado/web.py", line 3173, in wrapper
    return method(self, *args, **kwargs)
  File "/Users/tomaszkluczkowski/envs/platform/lib/python3.9/site-packages/flower/api/tasks.py", line 534, in get
    for task_id, task in tasks.iter_tasks(
  File "/Users/tomaszkluczkowski/envs/platform/lib/python3.9/site-packages/flower/utils/tasks.py", line 43, in iter_tasks
    if i >= offset:
TypeError: '>=' not supported between instances of 'int' and 'NoneType'
```

I have tested with flower 0.9.4 and `api/tasks` works fine with identical remaining setup of my app.

The `api/workers` endpoint works fine though.

**To Reproduce**
My setup:
celery==4.4.7
flower==0.9.7 

Broker: rabbitmq
Result Backend: rabbitmq

1. Go to `api/tasks` in flower
2. Observe its logs - it will show an exception as above.

**Expected behavior**
The `api/tasks` endpoint works correctly.

**Screenshots**

**System information**
Output of `python -c 'from flower.utils import bugreport; print(bugreport())'` command

**Comment by ezhlobo** [comment]
I see that it was fixed already: #1051, #1057.

It seems like it's a great time to release new version :).

**Comment by kodless** [comment]
**LEEK: a new celery tasks monitoring tool!**

Repository: https://github.com/kodless/leek

Website: https://tryleek.com/

**Comment by Tomasz-Kluczkowski** [comment]
Confirm on newest master it works fine. Closing.
