### ISSUE TITLE
--persistent UnpickleableError

### ISSUE THREAD

**Issue by sacre** [mher/flower#109]
after ctrl+c I got:

```
[D 130722 17:08:09 events:70] Saving state to 'flower.db'...
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/xxx/lib/python2.6/site-packages/flower-0.6.0-py2.6.egg/flower/app.py", line 49, in stop
    self.events.stop()
  File "/home/xxx/lib/python2.6/site-packages/flower-0.6.0-py2.6.egg/flower/events.py", line 72, in stop
    state['events'] = self.state
  File "/usr/lib/python2.6/shelve.py", line 132, in __setitem__
    p.dump(value)
UnpickleableError: Cannot pickle <type 'thread.lock'> objects
```

**Comment by mustaqeem** [comment]
I am also getting same error. My celery version is 3.1.17

The error that I was getting:

Traceback (most recent call last):
  File "/home/ubuntu/workspace/envs/ingrapher_env/bin/flower", line 9, in <module>
    load_entry_point('flower==0.7.3', 'console_scripts', 'flower')()
  File "/home/ubuntu/workspace/envs/ingrapher_env/local/lib/python2.7/site-packages/flower/__main__.py", line 11, in main
    flower.execute_from_commandline()
  File "/home/ubuntu/workspace/envs/ingrapher_env/local/lib/python2.7/site-packages/celery/bin/base.py", line 307, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/home/ubuntu/workspace/envs/ingrapher_env/local/lib/python2.7/site-packages/flower/command.py", line 118, in handle_argv
    return self.run_from_argv(prog_name, argv)
  File "/home/ubuntu/workspace/envs/ingrapher_env/local/lib/python2.7/site-packages/flower/command.py", line 94, in run_from_argv
    **app_settings)
  File "/home/ubuntu/workspace/envs/ingrapher_env/local/lib/python2.7/site-packages/flower/app.py", line 40, in __init__
    max_tasks_in_memory=max_tasks)
  File "/home/ubuntu/workspace/envs/ingrapher_env/local/lib/python2.7/site-packages/flower/events.py", line 65, in __init__
    self.state = state['events']
  File "/usr/lib/python2.7/shelve.py", line 122, in __getitem__
    value = Unpickler(f).load()
EOFError

----------------------------------


flower --version
0.7.3
3.1.17 (Cipater)
flower   -> 0.7.3
software -> celery:3.1.17 (Cipater) kombu:3.0.24 py:2.7.3
            billiard:3.3.0.19 py-amqp:1.4.6
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled

**Comment by burkestar** [comment]
any resolution to this?

**Comment by peketamin** [comment]
@mustaqeem How about try to delete flower.* (in the directory path set by `--persistant`) files which is pickled data for persistence?
