### ISSUE TITLE
Support Python 3.10

### ISSUE THREAD

**Issue by dominik-bln** [mher/flower#1175]
**Is your feature request related to a problem? Please describe.**

We recently upgrade from Python 3.9 to 3.10 and noticed that flower stopped working with the update.

You can see this with the following minimal Dockerfile:

```dockerfile
FROM python:3.10.1

RUN pip install celery==5.2.1 celery-flower==1.0.1

CMD ["celery", "--help"]
```

Showing:

```bash
flower   † Warning: could not load plugin. See `celery flower --help`.
```

and for `celery flower --help`:

```bash
Warning: entry point could not be loaded. Contact its author for help.


Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/click_plugins/core.py", line 37, in decorator
    group.add_command(entry_point.load())
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.10/site-packages/flower/command.py", line 15, in <module>
    from celery.bin.base import Command
ImportError: cannot import name 'Command' from 'celery.bin.base' (/usr/local/lib/python3.10/site-packages/celery/bin/base.py)
```

**Describe the solution you'd like**

Support Python 3.10

**Comment by dominik-bln** [comment]
Sorry, need to recheck, since my Dockerfile seems to have included the wrong `flower` package. We are definitely seeing a very similar issue in our full setup though.

**Comment by dominik-bln** [comment]
So upon further investigation the problem seems to be somewhat related to our usage of bitnami/python as a Docker base image. Some dependencies that seems to miss some dependencies somewhere along the line.

This doesn't work for us:

```dockerfile
FROM bitnami/python:3.10.1-prod-debian-10-r3

RUN pip install celery==5.2.1 flower==1.0.0

CMD ["/opt/bitnami/python/bin/celery", "flower"]
```

While this:

```dockerfile
FROM bitnami/python:3.10.1-prod-debian-10-r3

RUN pip install celery==5.2.1 flower==1.0.0 cached-property backports.functools-lru-cache

CMD ["/opt/bitnami/python/bin/celery", "flower"]
```

and this does:

```dockerfile
FROM python:3.10.1

RUN pip install celery==5.2.1 flower==1.0.0

CMD ["celery", "flower"]
```

**Comment by dominik-bln** [comment]
With bitnami/python:3.9 it works as well:

```dockerfile
FROM bitnami/python:3.9

RUN pip install celery==5.2.1 flower==1.0.0

CMD ["/opt/bitnami/python/bin/celery", "flower"]
```

**Comment by dominik-bln** [comment]
The issue seems to be with an old version of `setuptools` in the `bitnami/python` base image we are using. This dockerfile works as well for us:

```dockerfile
FROM bitnami/python:3.10-prod

RUN pip install setuptools==59.5.0

RUN pip install celery==5.2.1 flower==1.0.0

CMD ["/opt/bitnami/python/bin/celery", "flower"]
```

I've opened an issue on their side: https://github.com/bitnami/bitnami-docker-python/issues/17
