### ISSUE TITLE
Conflict: not running if click >= 8.0

### ISSUE THREAD

**Issue by bsauvage1** [mher/flower#1212]
Hello. 

Windows10, flower 1.0.0, celery 5.1.2, python 3.9

When trying to run celery with flower output ("celery -A cl.tasks flower") I get the following error.

Warning: entry point could not be loaded. Contact its author for help.
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\py39\lib\site-packages\click_plugins\core.py", line 37, in decorator
    group.add_command(entry_point.load())
  File "C:\ProgramData\Anaconda3\envs\py39\lib\site-packages\pkg_resources\__init__.py", line 2457, in load
    self.require(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\py39\lib\site-packages\pkg_resources\__init__.py", line 2480, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "C:\ProgramData\Anaconda3\envs\py39\lib\site-packages\pkg_resources\__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (click 8.0.3 (c:\programdata\anaconda3\envs\py39\lib\site-packages), Requirement.parse('click<8.0,>=7.0'), {'celery'})

**Comment by mher** [comment]
Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use StackOverflow.com for general usage questions instead.
