### ISSUE TITLE
Unkown celery version after google auth redirect

### ISSUE THREAD

**Issue by lalatgithub** [mher/flower#1235]
When i am trying to login using Google auth, after successfully logged in google and redirect, it throws this error. This works fine on local but not on prod.

I have added the correct origin and redirect urls to google developer console.
I am passing correct env vars to flower as well for google auth. This was working before but suddenly stopped working on both Staging and Prod. Local seems fine till now.

```
It looks like you have found a bug! You can help to improve Flower by opening an issue in https://github.com/mher/flower/issues

Unknown Celery version
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/usr/local/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/usr/local/lib/python3.7/site-packages/flower/views/auth.py", line 26, in get
    code=self.get_argument('code'),
  File "/usr/local/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/usr/local/lib/python3.7/site-packages/tornado/auth.py", line 919, in get_authenticated_user
    body=body,
tornado.httpclient.HTTPClientError: HTTP 400: Bad Request
```

This is how i run flower. Flower is running in a container.
```
flower -A proj --address=0.0.0.0 --port=5050 --db=./flower.db --persistent=true --debug=true --auth=.*@example\.com$ --auto-refresh=false
```

```
celery==4.4.7
flower==0.9.7
tornado==6.1
```

**Comment by mher** [comment]
This bug is already fixed. Try to update to the latest version.
