### ISSUE TITLE
Unable to start flower when redis is protected by password

### ISSUE THREAD

**Issue by supreme-core** [mher/flower#1253]
**Describe the bug**
Unable to start flower when redis is protected by password

$celery --broker=redis://:$REDIS_PASSWORD@localhost:6379/0 flower

**System information**
   Traceback (most recent call last):
      File "/venv/lib/python3.8/site-packages/kombu/connection.py", line 446, in _reraise_as_library_errors
        yield
      File "/venv/lib/python3.8/site-packages/kombu/connection.py", line 433, in _ensure_connection
        return retry_over_time(
      File "/venv/lib/python3.8/site-packages/kombu/utils/functional.py", line 312, in retry_over_time
        return fun(*args, **kwargs)
      File "/venv/lib/python3.8/site-packages/kombu/connection.py", line 877, in _connection_factory
        self._connection = self._establish_connection()
      File "/venv/lib/python3.8/site-packages/kombu/connection.py", line 812, in _establish_connection
        conn = self.transport.establish_connection()
      File "/venv/lib/python3.8/site-packages/kombu/transport/virtual/base.py", line 949, in establish_connection
        self._avail_channels.append(self.create_channel(self))
      File "/venv/lib/python3.8/site-packages/kombu/transport/virtual/base.py", line 927, in create_channel
        channel = self.Channel(connection)
      File "/venv/lib/python3.8/site-packages/kombu/transport/redis.py", line 737, in __init__
        self.client.ping()
      File "/venv/lib/python3.8/site-packages/redis/commands/core.py", line 1132, in ping
        return self.execute_command("PING", **kwargs)
      File "/venv/lib/python3.8/site-packages/redis/client.py", line 1235, in execute_command
        conn = self.connection or pool.get_connection(command_name, **options)
      File "/venv/lib/python3.8/site-packages/redis/connection.py", line 1387, in get_connection
        connection.connect()
      File "/venv/lib/python3.8/site-packages/redis/connection.py", line 623, in connect
        self.on_connect()
      File "/venv/lib/python3.8/site-packages/redis/connection.py", line 713, in on_connect
        auth_response = self.read_response()
      File "/venv/lib/python3.8/site-packages/redis/connection.py", line 839, in read_response
        raise response
    redis.exceptions.ResponseError: AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?
    
    The above exception was the direct cause of the following exception

**Comment by supreme-core** [comment]
Flower does not support redis with password just in case someone else is experiencing the same issue
