### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'true'

### ISSUE THREAD

**Issue by lemaadi** [mher/flower#1314]
**Describe the bug**

Hi there,

It seems there are some issues with the latest versions of flower package when used with latest versions of celery

```
Traceback (most recent call last):
--
File "/usr/local/bin/celery", line 8, in <module>
sys.exit(main())
File "/usr/local/lib/python3.8/site-packages/celery/__main__.py", line 15, in main
sys.exit(_main())
File "/usr/local/lib/python3.8/site-packages/celery/bin/celery.py", line 213, in main
return celery(auto_envvar_prefix="CELERY")
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
return callback(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
return f(get_current_context(), *args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/flower/command.py", line 35, in flower
apply_env_options()
File "/usr/local/lib/python3.8/site-packages/flower/command.py", line 71, in apply_env_options
value = option.type(value)
ValueError: invalid literal for int() with base 10: 'true'
```

**To Reproduce**

- Install `flower==1.1.0` or later 
- Install `celery==5.0.5` or later
- Deploy flower service to aws fargate instance and start the service with the command `celery -A config.celery flower --inspect-timeout=20000 -l INFO`

**Expected behavior**
The service should start and work as expected

**Comment by lemaadi** [comment]
Migrating to https://tryleek.com/ since no feedback provided
