### ISSUE TITLE
 Flower crashed with Failed to inspect workers: 'Socket closed',

### ISSUE THREAD

**Issue by linearregression** [mher/flower#220]
Rabbitmq server he latest release of RabbitMQ is 3.3.1.
cmdline: celery flower --basic_auth=<userID>:<password>  broker=amqp://<rabbitmq server>:5672// --broker_api='http://<rabbitmq server>:15672/' --debug=True --log_to_stderr
environment: ubuntu 64bit 13.0+ for both rabbitmq server and celery flower 
There is no workers registered to rabbitmq sever
amqp pthon module 1.4.5
Expect No error and the webUI shows 0 workers

But following exceptions:

[D 140512 13:40:44 state:79] Inspecting workers...
[D 140512 13:40:44 connection:751] Start from server, version: 0.9, properties: {u'information': u'Licensed under the MPL.  See http://www.rabbitmq.com/', u'product': u'RabbitMQ', u'copyright': u'Copyright (C) 2007-2013 GoPivotal, Inc.', u'capabilities': {u'exchange_exchange_bindings': True, u'consumer_cancel_notify': True, u'publisher_confirms': True, u'basic.nack': True}, u'platform': u'Erlang/OTP', u'version': u'3.1.5'}, mechanisms: [u'AMQPLAIN', u'PLAIN'], locales: [u'en_US']
[D 140512 13:40:44 connection:751] Start from server, version: 0.9, properties: {u'information': u'Licensed under the MPL.  See http://www.rabbitmq.com/', u'product': u'RabbitMQ', u'copyright': u'Copyright (C) 2007-2013 GoPivotal, Inc.', u'capabilities': {u'exchange_exchange_bindings': True, u'consumer_cancel_notify': True, u'publisher_confirms': True, u'basic.nack': True}, u'platform': u'Erlang/OTP', u'version': u'3.1.5'}, mechanisms: [u'AMQPLAIN', u'PLAIN'], locales: [u'en_US']
[D 140512 13:40:44 events:114] Failed to enable events: 'Socket closed'
[D 140512 13:40:46 events:110] Enabling events
[D 140512 13:40:46 connection:751] Start from server, version: 0.9, properties: {u'information': u'Licensed under the MPL.  See http://www.rabbitmq.com/', u'product': u'RabbitMQ', u'copyright': u'Copyright (C) 2007-2013 GoPivotal, Inc.', u'capabilities': {u'exchange_exchange_bindings': True, u'consumer_cancel_notify': True, u'publisher_confirms': True, u'basic.nack': True}, u'platform': u'Erlang/OTP', u'version': u'3.1.5'}, mechanisms: [u'AMQPLAIN', u'PLAIN'], locales: [u'en_US']
[E 140512 13:40:47 state:138] Failed to inspect workers: 'Socket closed', trying again in 8 seconds
[D 140512 13:40:47 state:139] Socket closed
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/flower/state.py", line 80, in run
        stats = i.stats()
      File "/usr/local/lib/python2.7/dist-packages/celery/app/control.py", line 89, in stats
        return self._request('stats')
      File "/usr/local/lib/python2.7/dist-packages/celery/app/control.py", line 70, in _request
        timeout=self.timeout, reply=True,
      File "/usr/local/lib/python2.7/dist-packages/celery/app/control.py", line 306, in broadcast
        limit, callback, channel=channel,
      File "/usr/local/lib/python2.7/dist-packages/kombu/pidbox.py", line 283, in _broadcast
        chan = channel or self.connection.default_channel
      File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 773, in default_channel
        self.connection
      File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 758, in connection
        self._connection = self._establish_connection()
      File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 713, in _establish_connection
        conn = self.transport.establish_connection()
      File "/usr/local/lib/python2.7/dist-packages/kombu/transport/pyamqp.py", line 112, in establish_connection
        conn = self.Connection(**opts)
      File "/usr/local/lib/python2.7/dist-packages/amqp/connection.py", line 183, in __init__
        return self._x_open(virtual_host)
      File "/usr/local/lib/python2.7/dist-packages/amqp/connection.py", line 624, in _x_open
        (10, 41),    # Connection.open_ok
      File "/usr/local/lib/python2.7/dist-packages/amqp/abstract_channel.py", line 67, in wait
        self.channel_id, allowed_methods)
      File "/usr/local/lib/python2.7/dist-packages/amqp/connection.py", line 237, in _wait_method
        self.method_reader.read_method()
      File "/usr/local/lib/python2.7/dist-packages/amqp/method_framing.py", line 189, in read_method
        raise m
    IOError: Socket closed
[E 140512 13:40:47 events:103] Failed to capture events: 'Socket closed', trying again in 8 seconds.
[D 140512 13:40:47 events:104] Socket closed
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/flower/events.py", line 90, in run
        app=self._celery_app)
      File "/usr/local/lib/python2.7/dist-packages/celery/events/__init__.py", line 287, in __init__
        self.channel = maybe_channel(channel)
      File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 1071, in maybe_channel
        return channel.default_channel
      File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 773, in default_channel
        self.connection
      File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 758, in connection
        self._connection = self._establish_connection()
      File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 713, in _establish_connection
        conn = self.transport.establish_connection()
      File "/usr/local/lib/python2.7/dist-packages/kombu/transport/pyamqp.py", line 112, in establish_connection
        conn = self.Connection(**opts)
      File "/usr/local/lib/python2.7/dist-packages/amqp/connection.py", line 183, in __init__
        return self._x_open(virtual_host)
      File "/usr/local/lib/python2.7/dist-packages/amqp/connection.py", line 624, in _x_open
        (10, 41),    # Connection.open_ok
      File "/usr/local/lib/python2.7/dist-packages/amqp/abstract_channel.py", line 67, in wait
        self.channel_id, allowed_methods)
      File "/usr/local/lib/python2.7/dist-packages/amqp/connection.py", line 237, in _wait_method
        self.method_reader.read_method()
      File "/usr/local/lib/python2.7/dist-packages/amqp/method_framing.py", line 189, in read_method
        raise m
    IOError: Socket closed
[D 140512 13:40:49 events:114] Failed to enable events: 'Socket closed'
[D 140512 13:40:51 events:110] Enabling events
[D 140512 13:40:51 connection:751] Start from server, version: 0.9, properties: {u'information': u'Licensed under the MPL.  See http://www.rabbitmq.com/', u'product': u'RabbitMQ', u'copyright': u'Copyright (C) 2007-2013 GoPivotal, Inc.', u'capabilities': {u'exchange_exchange_bindings': True, u'consumer_cancel_notify': True, u'publisher_confirms': True, u'basic.nack': True}, u'platform': u'Erlang/OTP', u'version': u'3.1.5'}, mechanisms: [u'AMQPLAIN', u'PLAIN'], locales: [u'en_US']
[D 140512 13:40:54 events:114] Failed to enable events: 'Socket closed'
[D 140512 13:40:55 state:79] Inspecting workers...
[D 140512 13:40:55 connection:751] Start from server, version: 0.9, properties: {u'information': u'Licensed under the MPL.  See http://www.rabbitmq.com/', u'product': u'RabbitMQ', u'copyright': u'Copyright (C) 2007-2013 GoPivotal, Inc.', u'capabilities': {u'exchange_exchange_bindings': True, u'consumer_cancel_notify': True, u'publisher_confirms': True, u'basic.nack': True}, u'platform': u'Erlang/OTP', u'version': u'3.1.5'}, mechanisms: [u'AMQPLAIN', u'PLAIN'], locales: [u'en_US']
[D 140512 13:40:55 connection:751] Start from server, version: 0.9, properties: {u'information': u'Licensed under the MPL.  See http://www.rabbitmq.com/', u'product': u'RabbitMQ', u'copyright': u'Copyright (C) 2007-2013 GoPivotal, Inc.', u'capabilities': {u'exchange_exchange_bindings': True, u'consumer_cancel_notify': True, u'publisher_confirms': True, u'basic.nack': True}, u'platform': u'Erlang/OTP', u'version': u'3.1.5'}, mechanisms: [u'AMQPLAIN', u'PLAIN'], locales: [u'en_US']
[D 140512 13:40:56 events:110] Enabling events
[D 140512 13:40:56 connection:751] Start from server, version: 0.9, properties: {u'information': u'Licensed under the MPL.  See http://www.rabbitmq.com/', u'product': u'RabbitMQ', u'copyright': u'Copyright (C) 2007-2013 GoPivotal, Inc.', u'capabilities': {u'exchange_exchange_bindings': True, u'consumer_cancel_notify': True, u'publisher_confirms': True, u'basic.nack': True}, u'platform': u'Erlang/OTP', u'version': u'3.1.5'}, mechanisms: [u'AMQPLAIN', u'PLAIN'], locales: [u'en_US']
[E 140512 13:40:58 events:103] Failed to capture events: 'Socket closed', trying again in 16 seconds.
[D 140512 13:40:58 events:104] Socket closed
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/flower/events.py", line 90, in run
        app=self._celery_app)
      File "/usr/local/lib/python2.7/dist-packages/celery/events/__init__.py", line 287, in __init__
        self.channel = maybe_channel(channel)
      File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 1071, in maybe_channel
        return channel.default_channel
      File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 773, in default_channel
        self.connection
      File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 758, in connection
        self._connection = self._establish_connection()
      File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 713, in _establish_connection
        conn = self.transport.establish_connection()
      File "/usr/local/lib/python2.7/dist-packages/kombu/transport/pyamqp.py", line 112, in establish_connection
        conn = self.Connection(**opts)
      File "/usr/local/lib/python2.7/dist-packages/amqp/connection.py", line 183, in __init__
        return self._x_open(virtual_host)
      File "/usr/local/lib/python2.7/dist-packages/amqp/connection.py", line 624, in _x_open
        (10, 41),    # Connection.open_ok
      File "/usr/local/lib/python2.7/dist-packages/amqp/abstract_channel.py", line 67, in wait
        self.channel_id, allowed_methods)
      File "/usr/local/lib/python2.7/dist-packages/amqp/connection.py", line 237, in _wait_method
        self.method_reader.read_method()
      File "/usr/local/lib/python2.7/dist-packages/amqp/method_framing.py", line 189, in read_method
        raise m
    IOError: Socket closed
[E 140512 13:40:58 state:138] Failed to inspect workers: 'Socket closed', trying again in 16 seconds
[D 140512 13:40:58 state:139] Socket closed
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/flower/state.py", line 80, in run
        stats = i.stats()
      File "/usr/local/lib/python2.7/dist-packages/celery/app/control.py", line 89, in stats
        return self._request('stats')
      File "/usr/local/lib/python2.7/dist-packages/celery/app/control.py", line 70, in _request
        timeout=self.timeout, reply=True,
      File "/usr/local/lib/python2.7/dist-packages/celery/app/control.py", line 306, in broadcast
        limit, callback, channel=channel,
      File "/usr/local/lib/python2.7/dist-packages/kombu/pidbox.py", line 283, in _broadcast
        chan = channel or self.connection.default_channel
      File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 773, in default_channel
        self.connection
      File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 758, in connection
        self._connection = self._establish_connection()
      File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 713, in _establish_connection
        conn = self.transport.establish_connection()
      File "/usr/local/lib/python2.7/dist-packages/kombu/transport/pyamqp.py", line 112, in establish_connection
        conn = self.Connection(**opts)
      File "/usr/local/lib/python2.7/dist-packages/amqp/connection.py", line 183, in __init__
        return self._x_open(virtual_host)
      File "/usr/local/lib/python2.7/dist-packages/amqp/connection.py", line 624, in _x_open
        (10, 41),    # Connection.open_ok
      File "/usr/local/lib/python2.7/dist-packages/amqp/abstract_channel.py", line 67, in wait
        self.channel_id, allowed_methods)
      File "/usr/local/lib/python2.7/dist-packages/amqp/connection.py", line 237, in _wait_method
        self.method_reader.read_method()
      File "/usr/local/lib/python2.7/dist-packages/amqp/method_framing.py", line 189, in read_method
        raise m
    IOError: Socket closed
[D 140512 13:40:59 events:114] Failed to enable events: 'Socket closed'
[D 140512 13:41:01 events:110] Enabling events
[D 140512 13:41:01 connection:751] Start from server, version: 0.9, properties: {u'information': u'Licensed under the MPL.  See http://www.rabbitmq.com/', u'product': u'RabbitMQ', u'copyright': u'Copyright (C) 2007-2013 GoPivotal, Inc.', u'capabilities': {u'exchange_exchange_bindings': True, u'consumer_cancel_notify': True, u'publisher_confirms': True, u'basic.nack': True}, u'platform': u'Erlang/OTP', u'version': u'3.1.5'}, mechanisms: [u'AMQPLAIN', u'PLAIN'], locales: [u'en_US']
^[[1;2B^[[1;2B^[[1;2B^[[1;2B^[[1;2B^[[1;2B^[[1;2B^[[1;2B^[[1;2B^[[1;2B^[[1;2B^[[1;2B^[[1;2B^[[1;2B^[[1;2B[D 140512 13:41:04 events:114] Failed to enable events: 'Socket closed'
^A[D 140512 13:41:06 events:110] Enabling events
[D 140512 13:41:06 connection:751] Start from server, version: 0.9, properties: {u'information': u'Licensed under the MPL.  See http://www.rabbitmq.com/', u'product': u'RabbitMQ', u'copyright': u'Copyright (C) 2007-2013 GoPivotal, Inc.', u'capabilities': {u'exchange_exchange_bindings': True, u'consumer_cancel_notify': True, u'publisher_confirms': True, u'basic.nack': True}, u'platform': u'Erlang/OTP', u'version': u'3.1.5'}, mechanisms: [u'AMQPLAIN', u'PLAIN'], locales: [u'en_US']
[D 140512 13:41:09 events:1

**Comment by mher** [comment]
This is an obsolete issue. state.py is gone
