### ISSUE TITLE
Attempting to run flower with Google OAuth 2.0 yields 403

### ISSUE THREAD

**Issue by michaelshobbs** [mher/flower#248]
I'm sure I have something wrong here. I'm pretty new to the Google Dev console but I've setup a new project and created a new OAuth Client ID.

I'm exporting the following env vars and running flower with --auth with my google app domain. 

export GOOGLE_OAUTH2_REDIRECT_URI="https://xxxx.xxxxx.com/flower/login"
export GOOGLE_OAUTH2_SECRET=<CLIENT_SECRET_FROM_GOOGLE>
export GOOGLE_OAUTH2_KEY=<CLIENT_ID_FROM_GOOGLE>

I hit my flower installation, get redirected to google auth, I login, then redirected back to /login?code=xxxxxxxx and get the following:

flower   -> 0.8.0-dev
software -> celery:3.1.7 (Cipater) kombu:3.0.21 py:2.7.3
            billiard:3.3.0.18 redis:2.10.1
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:redis results:disabled

Traceback (most recent call last):
  File "/srv/www/corvus/local/lib/python2.7/site-packages/tornado/web.py", line 1250, in wrapper
    return callback(_args, *_kwargs)
  File "/srv/www/corvus/local/lib/python2.7/site-packages/flower/views/auth.py", line 49, in _on_auth
    response = httpclient.HTTPClient().fetch('https://www.googleapis.com/plus/v1/people/me', headers={'Authorization': 'Bearer %s' % access_token})
  File "/srv/www/corvus/local/lib/python2.7/site-packages/tornado/httpclient.py", line 85, in fetch
    self._async_client.fetch, request, **kwargs))
  File "/srv/www/corvus/local/lib/python2.7/site-packages/tornado/ioloop.py", line 389, in run_sync
    return future_cell[0].result()
  File "/srv/www/corvus/local/lib/python2.7/site-packages/tornado/concurrent.py", line 131, in result
    return super(TracebackFuture, self).result(timeout=timeout)
  File "/srv/www/corvus/local/lib/python2.7/site-packages/tornado/concurrent.py", line 65, in result
    raise self._exception
HTTPError: HTTP 403: Forbidden

Any help would be greatly appreciated.

**Comment by iurisilvio** [comment]
@michaelshobbs thanks for this issue and for your answer! I was stucked with the same problem.

I don't know if it is written in the docs, but it is not easy to discover this.

**Comment by mher** [comment]
Please open a pull request if you think something important is missing from the docs. Thanks!
