### ISSUE TITLE
3.1.16 (Cipater) Crashed on Yosemite

### ISSUE THREAD

**Issue by kodeshpa** [mher/flower#294]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/tornado/web.py", line 1346, in _when_complete
    callback()
  File "/Library/Python/2.7/site-packages/tornado/web.py", line 1367, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "/Library/Python/2.7/site-packages/tornado/web.py", line 2523, in wrapper
    return method(self, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/flower/views/tasks.py", line 47, in get
    state=state)
  File "/Library/Python/2.7/site-packages/flower/views/__init__.py", line 16, in render
    super(BaseHandler, self).render(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/tornado/web.py", line 666, in render
    html = self.render_string(template_name, **kwargs)
  File "/Library/Python/2.7/site-packages/tornado/web.py", line 773, in render_string
    return t.generate(**namespace)
  File "/Library/Python/2.7/site-packages/tornado/template.py", line 278, in generate
    return execute()
  File "tasks_html.generated.py", line 63, in _tt_execute
    for uuid, task in tasks:  # tasks.html:100 (via base.html:48)
  File "/Library/Python/2.7/site-packages/flower/models.py", line 105, in iter_tasks
    for uuid, task in events_state._sort_tasks_by_time(
AttributeError: 'EventsState' object has no attribute '_sort_tasks_by_time

**Comment by mher** [comment]
Closing. models.py is removed from the latest versions
