### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by glynjackson** [mher/flower#331]
Running a tasks that passes around large binary image data causes Flower to crash. This does not impact Celery as tasks still complete.

Example Task:

```
@app.task(base=BaseTask, max_retries="5", ignore_result=False, bind=True)
def segment(self, id):
      header = (
        segment_image.s(image_channels_compressed,
                                        theta,
                                        smooth_sigmas, photo_id)
        for theta_ind, theta in enumerate(mpb.default_orientations)
    )

    callback = segment_finish.s(content=content, id=id,segmentation_start_time=segmentation_start_time)

    chord(header)(callback)
```

Viewing these tasks in Flower crash the app and it restarts showing the error:

```
flower   -> 0.7.3
software -> celery:3.1.17 (Cipater) kombu:3.0.24 py:2.7.6
            billiard:3.3.0.19 py-amqp:1.4.6
platform -> system:Linux arch:64bit imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled



Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1332, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 2607, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flower/views/tasks.py", line 46, in get
    state=state)
  File "/usr/local/lib/python2.7/dist-packages/flower/views/__init__.py", line 30, in render
    super(BaseHandler, self).render(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 665, in render
    html = self.render_string(template_name, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 772, in render_string
    return t.generate(**namespace)
  File "/usr/local/lib/python2.7/dist-packages/tornado/template.py", line 278, in generate
    return execute()
  File "tasks_html.generated.py", line 183, in _tt_execute
    _tt_tmp = humanize(task.args, length=20)  # tasks.html:115 (via base.html:52)
  File "/usr/local/lib/python2.7/dist-packages/flower/utils/template.py", line 33, in humanize
    obj = obj.replace('-', ' ').replace('_', ' ')
MemoryError
```

**Comment by mher** [comment]
Sorry for late answer. Can you try the master version with `max_tasks` option?

http://flower.readthedocs.org/en/latest/config.html#max-tasks

**Comment by mher** [comment]
#326

**Comment by glynjackson** [comment]
@mher Thanks, still too much in memory, however I have resolved this issue by compressing the data differently on the chord task before being sent. Flower seems to be stable now.
