### ISSUE TITLE
Exception in `WorkersModel.get_latest(app)`

### ISSUE THREAD

**Issue by petrjasek** [mher/flower#332]
hey, getting this exception in ioloop, in ui I can only see tasks, other pages are empty.
exception is:
```
[E 150213 12:30:29 ioloop:585] Exception in callback functools.partial(<bound method type.on_update_time of <class 'flower.views.update.UpdateWorkers'>>, <flower.app.Flower object at 0x7fe897efa9b0>)
    Traceback (most recent call last):
      File "/home/petr/dev/superdesk-server/env/lib/python3.4/site-packages/tornado/ioloop.py", line 976, in _run
        return self.callback()
      File "/home/petr/dev/superdesk-server/env/lib/python3.4/site-packages/flower/views/update.py", line 51, in on_update_time
        workers = WorkersModel.get_latest(app)
      File "/home/petr/dev/superdesk-server/env/lib/python3.4/site-packages/flower/models.py", line 43, in get_latest
        return WorkersModel(app)
      File "/home/petr/dev/superdesk-server/env/lib/python3.4/site-packages/flower/models.py", line 31, in __init__
        pool = stat.get('pool') or {}
    AttributeError: 'list' object has no attribute 'get'
```
info from workers page:
```
flower   -> 0.7.3
software -> celery:3.1.17 (Cipater) kombu:3.0.24 py:3.4.1+
            billiard:3.3.0.19 redis:2.10.3
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:disabled
```
any idea what is the issue? was trying to fix it but no luck so far.

**Comment by mher** [comment]
Please try the master version. It should solve the problem.

**Comment by petrjasek** [comment]
:+1: master works
