### ISSUE TITLE
Flower 0.8.0 displays error when clicking "Browser" link on web page

### ISSUE THREAD

**Issue by jiml521** [mher/flower#336]
flower   -> 0.8.0-dev
software -> celery:3.1.17 (Cipater) kombu:3.0.24 py:3.4.0
            billiard:3.3.0.19 py-amqp:1.4.6
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:amqp://xxxx:yyyy@rmq-cluster.dddd.local//

CELERY_TASK_SERIALIZER: 'json'
CELERY_RESULT_BACKEND: 'amqp://xxxx.yyyy@rmq-cluster.dddd.local//'
CELERY_ENABLE_UTC: True
CELERY_TASK_RESULT_EXPIRES: 30
BROKER_URL: 'amqp://xxxx:********@rmq-cluster.dddd.local:5672//'
CELERY_TIMEZONE: 'America/New_York'
CELERY_ACCEPT_CONTENT: ['json']
CELERY_RESULT_SERIALIZER: 'json'

Traceback (most recent call last):
  File "/home/dddd/Envs/quantum3flower/lib/python3.4/site-packages/tornado/web.py", line 1348, in _execute
    result = yield result
  File "/home/dddd/Envs/quantum3flower/lib/python3.4/site-packages/tornado/gen.py", line 807, in run
    value = future.result()
  File "/home/dddd/Envs/quantum3flower/lib/python3.4/site-packages/tornado/concurrent.py", line 209, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/home/dddd/Envs/quantum3flower/lib/python3.4/site-packages/tornado/gen.py", line 810, in run
    yielded = self.gen.throw(*sys.exc_info())
  File "/home/dddd/Envs/quantum3flower/lib/python3.4/site-packages/flower/views/broker.py", line 31, in get
    queues = yield broker.queues(queue_names)
  File "/home/dddd/Envs/quantum3flower/lib/python3.4/site-packages/tornado/gen.py", line 807, in run
    value = future.result()
  File "/home/dddd/Envs/quantum3flower/lib/python3.4/site-packages/tornado/concurrent.py", line 209, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/home/dddd/Envs/quantum3flower/lib/python3.4/site-packages/tornado/gen.py", line 812, in run
    yielded = self.gen.send(value)
  File "/home/dddd/Envs/quantum3flower/lib/python3.4/site-packages/flower/utils/broker.py", line 84, in queues
    info = json.loads(response.body)
  File "/usr/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

**Comment by mher** [comment]
Are you using the latest master version? This bug should be fixed by https://github.com/mher/flower/commit/b7d841bbfe07518f679e9edbc16ec17c748646cf

**Comment by jiml521** [comment]
I was using what PIP had for the flower-new package.  I will try taking it directly from master.  Thanks.
