### ISSUE TITLE
/api/task/async-apply eta option?

### ISSUE THREAD

**Issue by pcairns** [mher/flower#339]
I could use some clarification on what format I should supply the eta option to the API. Is this currently possible? 

I'm get a 500 Internal Server when I attempt to include the eta option (this works fine without it).

```
curl -v -X POST --data '{"args":[1,524],"eta":"2015-03-11T14:08:06-04:00"}' http://localhost:5555/api/task/async-apply/tasks.add                                                  
```

```
[E 150309 19:24:53 web:1421] Uncaught exception POST /api/task/async-apply/tasks.add (10.0.2.2)
    HTTPServerRequest(protocol='http', host='localhost:5555', method='POST', uri='/api/task/async-apply/tasks.add', version='HTTP/1.1', remote_ip='10.0.2.2', headers={'Content-Length': '50', 'Host': 'localhost:5555', 'User-Agent': 'curl/7.22.0 (x86_64-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3', 'Content-Type': 'application/x-www-form-urlencoded', 'Accept': '*/*'})
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/site-packages/tornado/web.py", line 1346, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python3.4/site-packages/tornado/web.py", line 2626, in wrapper
        return method(self, *args, **kwargs)
      File "/usr/local/lib/python3.4/site-packages/flower/api/tasks.py", line 106, in post
        result = task.apply_async(args=args, kwargs=kwargs, **options)
      File "/usr/local/lib/python3.4/site-packages/celery/app/task.py", line 555, in apply_async
        **dict(self._get_exec_options(), **options)
      File "/usr/local/lib/python3.4/site-packages/celery/app/base.py", line 353, in send_task
        reply_to=reply_to or self.oid, **options
      File "/usr/local/lib/python3.4/site-packages/celery/app/amqp.py", line 265, in publish_task
        eta = eta and eta.isoformat()
    AttributeError: 'str' object has no attribute 'isoformat'

```

**Comment by mher** [comment]
Please try the fix from the master

**Comment by pcairns** [comment]
Thanks for the quick reply. But, there's still an issue with this; datetime.datetime requires year, month and day integer arguments.

```
HTTPServerRequest(protocol='http', host='localhost:5555', method='POST', uri='/api/task/async-apply/tasks.add', version='HTTP/1.1', remote_ip='10.0.2.2', headers={'Content-Length': '50', 'Host': 'localhost:5555', 'Content-Type': 'application/x-www-form-urlencoded', 'Accept': '*/*', 'User-Agent': 'curl/7.22.0 (x86_64-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3'})
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/site-packages/tornado/web.py", line 1346, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python3.4/site-packages/tornado/web.py", line 2626, in wrapper
        return method(self, *args, **kwargs)
      File "/usr/local/lib/python3.4/site-packages/flower/api/tasks.py", line 114, in post
        options[name] = self.option_types[name](value)
    TypeError: an integer is required (got type str)
```

**Comment by mher** [comment]
Fixed, thanks!

**Comment by mher** [comment]
`expire` and `eta` should have `%Y-%m-%d %H:%M:%S.%f` format
