### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by zwy-ok** [mher/flower#357]
When trying to open flower webpage, see the following error (btw, the flower webpage worked before, not sure when it stopped working):

It looks like you have found a bug! You can help to improve Celery Flower by opening an issue in https://github.com/mher/flower/issues
flower   -> 0.7.3
software -> celery:3.1.17 (Cipater) kombu:3.0.24 py:2.6.6
            billiard:3.3.0.19 redis:2.9.1
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://wqrbmeta006:6379/0

CELERYD_PREFETCH_MULTIPLIER: 1
CELERY_ACKS_LATE: True
BROKER_TRANSPORT_OPTIONS: {
    'visibility_timeout': 86400}
CELERY_IGNORE_RESULT: True

Traceback (most recent call last):
  File "/home/wqmetaprod/.local/lib/python2.6/site-packages/tornado-4.0.2-py2.6-linux-x86_64.egg/tornado/web.py", line 1332, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/wqmetaprod/.local/lib/python2.6/site-packages/tornado-4.0.2-py2.6-linux-x86_64.egg/tornado/web.py", line 2607, in wrapper
    return method(self, *args, **kwargs)
  File "/home/wqmetaprod/.local/lib/python2.6/site-packages/flower-0.7.3-py2.6.egg/flower/views/workers.py", line 13, in get
    workers = WorkersModel.get_latest(app).workers
  File "/home/wqmetaprod/.local/lib/python2.6/site-packages/flower-0.7.3-py2.6.egg/flower/models.py", line 43, in get_latest
    return WorkersModel(app)
  File "/home/wqmetaprod/.local/lib/python2.6/site-packages/flower-0.7.3-py2.6.egg/flower/models.py", line 38, in __init__
    state.active_queues.get(workername, []) if x]
TypeError: string indices must be integers

**Comment by mher** [comment]
Please try to update your flower version. This shouldn't be an issue in version 0.8

**Comment by zwy-ok** [comment]
Thank you very much.  I upgraded to 0.8 and since I am using python 2.6, I encounter the same issue as in "0.8.0 version does not work with python 2.6#352", when will #352 be released?  Thanks a lot.

**Comment by mher** [comment]
I will try to release this weekend

**Comment by mher** [comment]
Version 0.8.1 has been released

**Comment by zwy-ok** [comment]
Hi Mher,


v0.8.1 works for me perfectly.  Thank you very much.








Sent from Windows Mail





From: Mher Movsisyan
Sent: ‎Saturday‎, ‎April‎ ‎4‎, ‎2015 ‎8‎:‎37‎ ‎PM
To: mher/flower
Cc: Wenyi Zhang





Version 0.8.1 has been released
