### ISSUE TITLE
No such file or directory: workers.html

### ISSUE THREAD

**Issue by hamiltont** [mher/flower#362]
I recently did a `rm -rf env`, then created a new virtualenv and did `pip install -r requirements.txt`. Suddenly getting this error: 

```
flower   -> 0.7.3
software -> celery:3.1.17 (Cipater) kombu:3.0.24 py:2.7.6
            billiard:3.3.0.19 py-amqp:1.4.6
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:amqp://guest:guest@192.168.59.103:49212//

BROKER_URL: 'amqp://guest:********@192.168.59.103:49212//'
CELERY_RESULT_BACKEND: u'amqp://guest:guest@192.168.59.103:49212//'

Traceback (most recent call last):
  File "/Users/hamiltont/Documents/WebJuice/env/lib/python2.7/site-packages/tornado/web.py", line 1346, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/Users/hamiltont/Documents/WebJuice/env/lib/python2.7/site-packages/tornado/web.py", line 2626, in wrapper
    return method(self, *args, **kwargs)
  File "/Users/hamiltont/Documents/WebJuice/env/lib/python2.7/site-packages/flower/views/workers.py", line 16, in get
    if refresh:
  File "/Users/hamiltont/Documents/WebJuice/env/lib/python2.7/site-packages/flower/views/__init__.py", line 30, in render
    error_trace = ""
  File "/Users/hamiltont/Documents/WebJuice/env/lib/python2.7/site-packages/tornado/web.py", line 664, in render
    html = self.render_string(template_name, **kwargs)
  File "/Users/hamiltont/Documents/WebJuice/env/lib/python2.7/site-packages/tornado/web.py", line 768, in render_string
    t = loader.load(template_name)
  File "/Users/hamiltont/Documents/WebJuice/env/lib/python2.7/site-packages/tornado/template.py", line 343, in load
    self.templates[name] = self._create_template(name)
  File "/Users/hamiltont/Documents/WebJuice/env/lib/python2.7/site-packages/tornado/template.py", line 370, in _create_template
    with open(path, "rb") as f:
IOError: [Errno 2] No such file or directory: '/Users/hamiltont/Documents/WebJuice/env/lib/python2.7/site-packages/flower/templates/workers.html'
```

Can confirm the file is missing: 

```
ls env/lib/python2.7/site-packages/flower/templates/
404.html	broker.html	error.html	navbar.html	tasks.html
base.html	dashboard.html	monitor.html	task.html	worker.html
```

**Comment by mher** [comment]
`workers.html` is renamed in version 0.8. Your stacktrace is from version 0.7 but the content of template directory from 0.8. I think your setup is broken.

`pip install -U flower` should install all dependencies. There is not need for `pip install -r requirements.txt`

**Comment by hamiltont** [comment]
Deleted virtualenv and redid the setup, it's working fine now. THanks
