### ISSUE TITLE
flower crash

### ISSUE THREAD

**Issue by osallou** [mher/flower#363]
After having executed celery with mongdb broker, I try to connect to the dashboard on selected port but it fails:

(biomajenv)osallou@osallou-ldaptop:$ flower --port=5555 --broker=mongodb://localhost:27017/biomaj_celery
[I 150331 16:07:32 command:111] Visit me at http://localhost:5555
/home/osallou/Development/NOSAVE/genouest/biomajenv/local/lib/python2.7/site-packages/pkg_resources.py:991: UserWarning: /home/osallou/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
[I 150331 16:07:32 command:112] Broker: mongodb://localhost%3A27017%2Fbiomaj_celery/biomaj_celery
[I 150331 16:07:32 command:114] Registered tasks: 
    ['celery.backend_cleanup',
     'celery.chain',
     'celery.chord',
     'celery.chord_unlock',
     'celery.chunks',
     'celery.group',
     'celery.map',
     'celery.starmap']
[E 150331 16:07:45 web:1421] Uncaught exception GET / (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:5555', method='GET', uri='/', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4', 'Accept-Encoding': 'gzip, deflate, sdch', 'Cookie': 'owa_u=admin; csrftoken=5EJbT6QVjRcl7RleJKeJHMaESK78l2sU; m=34e2:|18c3:t|1a28:f|5cf4:t|77cb:t|79d4:chart|640c:small|678e:3600%7C60|3a95:chart|54b5:small|29b3:3600%7C60; _pk_id.2.1fff=8c4685c0cad6583a.1411723448.5.1412759609.1412595322.; _ga=GA1.1.1210330138.1416232491; galaxysession=c6ca0ddb55be603a90dfd667bd373bc8816e4b5f8d673059a2ad1add2f6059c1ebab38fb473bb0eb; gateone_user="2|1:0|10:1427186201|12:gateone_user|108:eyJ1cG4iOiAiQU5PTllNT1VTIiwgInNlc3Npb24iOiAiWkdZek5HUXlNMkZsWW1RNE5HTTBNVGd3WVdZNE5HVTVPR0prTWpGak16ZzRNIn0=|52910cfac30330d6a97c0b3a02170ddba70552052f8230db9c19d80adcf3d2d6"; auth_tkt="62917baf88a75db158dad85f1fdeb351e201fb5480d625a0004f6361a15163c4fe82c6c24a6c3def7a3406927a44780cafc921448d20559c5fb68f609d1accb255196e57b3NhbGxvdQ%3D%3D!userid_type:b64unicode"', 'Host': 'localhost:5555', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36'})
    Traceback (most recent call last):
      File "/home/osallou/Development/NOSAVE/genouest/biomajenv/local/lib/python2.7/site-packages/tornado/web.py", line 1348, in _execute
        result = yield result
      File "/home/osallou/Development/NOSAVE/genouest/biomajenv/local/lib/python2.7/site-packages/tornado/gen.py", line 807, in run
        value = future.result()
      File "/home/osallou/Development/NOSAVE/genouest/biomajenv/local/lib/python2.7/site-packages/tornado/concurrent.py", line 209, in result
        raise_exc_info(self._exc_info)
      File "/home/osallou/Development/NOSAVE/genouest/biomajenv/local/lib/python2.7/site-packages/tornado/gen.py", line 212, in wrapper
        yielded = next(result)
      File "/home/osallou/Development/NOSAVE/genouest/biomajenv/local/lib/python2.7/site-packages/flower/views/dashboard.py", line 39, in get
        info.update(self._as_dict(worker))
      File "/home/osallou/Development/NOSAVE/genouest/biomajenv/local/lib/python2.7/site-packages/flower/views/dashboard.py", line 45, in _as_dict
        return dict((k, worker.__getattribute__(k)) for k in worker._fields)
      File "/home/osallou/Development/NOSAVE/genouest/biomajenv/local/lib/python2.7/site-packages/celery-3.0.23-py2.7.egg/celery/datastructures.py", line 224, in __getattr__
        "'%s' object has no attribute '%s'" % (type(self).__name__, k))
    AttributeError: 'Worker' object has no attribute '_fields'
[E 150331 16:07:45 web:930] Uncaught exception in write_error
    Traceback (most recent call last):
      File "/home/osallou/Development/NOSAVE/genouest/biomajenv/local/lib/python2.7/site-packages/tornado/web.py", line 928, in send_error
        self.write_error(status_code, **kwargs)
      File "/home/osallou/Development/NOSAVE/genouest/biomajenv/local/lib/python2.7/site-packages/flower/views/__init__.py", line 37, in write_error
        bugreport=bugreport())
      File "/home/osallou/Development/NOSAVE/genouest/biomajenv/local/lib/python2.7/site-packages/flower/utils/__init__.py", line 21, in bugreport
        + celery.bugreport(app)
    TypeError: bugreport() takes no arguments (1 given)

Celery is up and running:

 -------------- celery@osallou-ldaptop v3.0.23 (Chiastic Slide)
---- **** ----- 
--- * ***  * -- Linux-3.13.0-48-generic-x86_64-with-Ubuntu-14.04-trusty
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> broker:      mongodb://localhost%2Fbiomaj_celery/biomaj_celery
- ** ---------- .> app:         default:0x7f8f961c0ed0 (.default.Loader)
- ** ---------- .> concurrency: 8 (processes)
- *** --- * --- .> events:      OFF (enable -E to monitor this worker)
-- ******* ---- 
--- ***** ----- [queues]
 -------------- .> celery:      exchange:celery(direct) binding:celery

**Comment by dellsystem** [comment]
Hey, I'm not a maintainer but it looks like your issue comes from the version of celery you're running. In v3.0.23 of celery, `celery.bugreport` (which is called in flower/utils/\_\_init\_\_.py) is a function that takes no arguments, which is what the error is indicating. For the v3.1.0 release, `celery.bugreport` was changed to accommodate an optional argument, as you can see in commit [99eea5f9d867e63446e166b43249f17a961ed176](https://github.com/celery/celery/commit/99eea5f9d867e63446e166b43249f17a961ed176). I suspect that if you upgrade to celery v3.1.0 or higher your problem will be resolved.

Good luck!

**Comment by mher** [comment]
I've updated Celery requirements for Flower. Please use Flower 0.7 for Celery < 3.1
