### ISSUE TITLE
Tasks table sorting exception

### ISSUE THREAD

**Issue by brettatoms** [mher/flower#367]
When I sort on Name, Received or Started (but not State) I get the following error:

```
flower   -> flower:0.8.0 tornado:4.1 babel:1.3
software -> celery:3.1.17 (Cipater) kombu:3.0.24 py:3.4.2
            billiard:3.3.0.19 redis:2.10.3
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://<scrubbed>

BROKER_URL: 'redis://<scrubbed>'
CELERY_RESULT_BACKEND: 'redis://<scrubbed>'
CELERY_ALWAYS_EAGER: False

Traceback (most recent call last):
  File "/Users/brett/.pyenv/versions/savant/lib/python3.4/site-packages/tornado/web.py", line 1346, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/Users/brett/.pyenv/versions/savant/lib/python3.4/site-packages/tornado/web.py", line 2626, in wrapper
    return method(self, *args, **kwargs)
  File "/Users/brett/.pyenv/versions/savant/lib/python3.4/site-packages/flower/views/tasks.py", line 74, in get
    started_end=started_end)
  File "/Users/brett/.pyenv/versions/savant/lib/python3.4/site-packages/flower/views/__init__.py", line 20, in render
    super(BaseHandler, self).render(*args, **kwargs)
  File "/Users/brett/.pyenv/versions/savant/lib/python3.4/site-packages/tornado/web.py", line 664, in render
    html = self.render_string(template_name, **kwargs)
  File "/Users/brett/.pyenv/versions/savant/lib/python3.4/site-packages/tornado/web.py", line 771, in render_string
    return t.generate(**namespace)
  File "/Users/brett/.pyenv/versions/savant/lib/python3.4/site-packages/tornado/template.py", line 278, in generate
    return execute()
  File "tasks_html.generated.py", line 183, in _tt_execute
    for uuid, task in tasks:  # tasks.html:123 (via base.html:49)
  File "/Users/brett/.pyenv/versions/savant/lib/python3.4/site-packages/flower/utils/tasks.py", line 17, in iter_tasks
    for uuid, task in tasks:
  File "/Users/brett/.pyenv/versions/savant/lib/python3.4/site-packages/flower/utils/tasks.py", line 45, in sort_tasks
    for task in sorted(tasks, key=lambda x: getattr(x[1], sort_by), reverse=reverse):
TypeError: unorderable types: NoneType() < NoneType()
```

**Comment by mher** [comment]
Fixed, thanks!
