### ISSUE TITLE
Show info windows celery worker bug

### ISSUE THREAD

**Issue by xBeAsTx** [mher/flower#372]
When you visit page on http://\<host\>/worker/\<worker_name\> it's show:
```
flower   -> flower:0.9.0-dev tornado:4.1 babel:1.3
software -> celery:3.1.17 (Cipater) kombu:3.0.24 py:2.7.6
            billiard:3.3.0.19 py-amqp:1.4.6
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:amqp



Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1348, in _execute
    result = yield result
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 807, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 209, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 212, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python2.7/dist-packages/flower/views/workers.py", line 29, in get
    self.render("worker.html", worker=dict(worker, name=name))
  File "/usr/local/lib/python2.7/dist-packages/flower/views/__init__.py", line 20, in render
    super(BaseHandler, self).render(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 664, in render
    html = self.render_string(template_name, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 771, in render_string
    return t.generate(**namespace)
  File "/usr/local/lib/python2.7/dist-packages/tornado/template.py", line 278, in generate
    return execute()
  File "worker_html.generated.py", line 403, in _tt_execute
    for name, value in worker['stats'].get('rusage', {}).items():  # worker.html:337 (via base.html:49)
AttributeError: 'unicode' object has no attribute 'items'
```

template code
```html
                <tbody>
                {% for name, value in worker['stats'].get('rusage', {}).items() %}
                    <tr>
                      <td>{{ name }}</td>
                      <td>{{ value }}</td>
                    </tr>
                {% end %}
                </tbody>
```

Thst's because on windows worker celery can't get rusage information:
```python
    def rusage(self):
        if resource is None:
            raise NotImplementedError('rusage not supported by this platform')
        s = resource.getrusage(resource.RUSAGE_SELF)
        return {
            'utime': s.ru_utime,
            'stime': s.ru_stime,
            'maxrss': s.ru_maxrss,
            'ixrss': s.ru_ixrss,
            'idrss': s.ru_idrss,
            'isrss': s.ru_isrss,
            'minflt': s.ru_minflt,
            'majflt': s.ru_majflt,
            'nswap': s.ru_nswap,
            'inblock': s.ru_inblock,
            'oublock': s.ru_oublock,
            'msgsnd': s.ru_msgsnd,
            'msgrcv': s.ru_msgrcv,
            'nsignals': s.ru_nsignals,
            'nvcsw': s.ru_nvcsw,
            'nivcsw': s.ru_nivcsw,
        }

    def stats(self):
        info = self.info()
        info.update(self.blueprint.info(self))
        info.update(self.consumer.blueprint.info(self.consumer))
        try:
            info['rusage'] = self.rusage()
        except NotImplementedError:
            info['rusage'] = 'N/A'
        return info
```

**Comment by brizzbane** [comment]
wondered if I missed something because of windows, so did some more searching after posting this issue:

https://github.com/mher/flower/issues/385
