### ISSUE TITLE
Dashboard Not Loading

### ISSUE THREAD

**Issue by michaelhelmick** [mher/flower#373]
I am able to get to Tasks, Broker and Monitor but not able to get to the Dashboard.

The `requirements/default.txt` says `flower` needs `celery>=2.5.0` and I'm running `celery==3.0.23`

```stacktrace
[E 150408 14:29:42 web:930] Uncaught exception in write_error
    Traceback (most recent call last):
      File "/Users/mikehelmick/.virtualenv/proj/lib/python2.7/site-packages/tornado/web.py", line 928, in send_error
        self.write_error(status_code, **kwargs)
      File "/Users/mikehelmick/.virtualenv/proj/lib/python2.7/site-packages/flower/views/__init__.py", line 37, in write_error
        bugreport=bugreport())
      File "/Users/mikehelmick/.virtualenv/proj/lib/python2.7/site-packages/flower/utils/__init__.py", line 25, in bugreport
        celery.bugreport(app)
    TypeError: bugreport() takes no arguments (1 given)
[E 150408 14:29:42 web:1825] 500 GET / (::1) 4.39ms
```

My `celery/app/__init__.py@bugreport` looks like this:

```python
def bugreport():
    return current_app().bugreport()
```

Current celery looks like this:
https://github.com/celery/celery/blob/77d7eb06e3aea636e0f2e1388c491181b955358f/celery/app/__init__.py#L54-L55

After fixing the `bugreport` arg issue, I ran into an `AttributeError`:

```stacktrace
Traceback (most recent call last):
  File "/Users/mikehelmick/.virtualenv/proj/lib/python2.7/site-packages/tornado/web.py", line 1348, in _execute
    result = yield result
  File "/Users/mikehelmick/.virtualenv/proj/lib/python2.7/site-packages/tornado/gen.py", line 807, in run
    value = future.result()
  File "/Users/mikehelmick/.virtualenv/proj/lib/python2.7/site-packages/tornado/concurrent.py", line 209, in result
    raise_exc_info(self._exc_info)
  File "/Users/mikehelmick/.virtualenv/proj/lib/python2.7/site-packages/tornado/gen.py", line 212, in wrapper
    yielded = next(result)
  File "/Users/mikehelmick/.virtualenv/proj/lib/python2.7/site-packages/flower/views/dashboard.py", line 41, in get
    info.update(self._as_dict(worker))
  File "/Users/mikehelmick/.virtualenv/proj/lib/python2.7/site-packages/flower/views/dashboard.py", line 47, in _as_dict
    return dict((k, worker.__getattribute__(k)) for k in worker._fields)
  File "/Users/mikehelmick/.virtualenv/proj/lib/python2.7/site-packages/celery/datastructures.py", line 224, in __getattr__
    "'%s' object has no attribute '%s'" % (type(self).__name__, k))
AttributeError: 'Worker' object has no attribute '_fields'
```

**Comment by raghuramos1987** [comment]
I'm getting the same issue with celery at 3.1

flower   -> flower:0.8.2 tornado:4.1 babel:1.3
software -> celery:3.1.0 (Cipater) kombu:3.0.26 py:2.7.5
            billiard:3.3.0.20 redis:2.10.1
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader

    Traceback (most recent call last):
      File "/usr/local/affine/affine/env/lib/python2.7/site-packages/tornado/web.py", line 1348, in _execute
        result = yield result
      File "/usr/local/affine/affine/env/lib/python2.7/site-packages/tornado/gen.py", line 807, in run
        value = future.result()
      File "/usr/local/affine/affine/env/lib/python2.7/site-packages/tornado/concurrent.py", line 209, in result
        raise_exc_info(self._exc_info)
      File "/usr/local/affine/affine/env/lib/python2.7/site-packages/tornado/gen.py", line 212, in wrapper
        yielded = next(result)
      File "/usr/local/affine/affine/env/lib/python2.7/site-packages/flower/views/dashboard.py", line 41, in get
        info.update(self._as_dict(worker))
      File "/usr/local/affine/affine/env/lib/python2.7/site-packages/flower/views/dashboard.py", line 47, in _as_dict
        return dict((k, worker.__getattribute__(k)) for k in worker._fields)
      File "/usr/local/affine/affine/env/lib/python2.7/site-packages/celery/datastructures.py", line 340, in __getattr__
        type(self).__name__, k))
    AttributeError: 'Worker' object has no attribute '_fields'
