### ISSUE TITLE
Cannot use broker or monitor, the worker sometime appears and sometime doesnt

### ISSUE THREAD

**Issue by AKSHAYUBHAT** [mher/flower#382]
It looks like you have found a bug! You can help to improve Celery Flower by opening an issue in https://github.com/mher/flower/issues

flower   -> flower:0.8.1 tornado:4.1 babel:1.3
software -> celery:3.1.17 (Cipater) kombu:3.0.24 py:2.7.6
            billiard:3.3.0.20 py-amqp:1.4.6
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1348, in _execute
    result = yield result
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 807, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 209, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 810, in run
    yielded = self.gen.throw(*sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/flower/views/broker.py", line 29, in get
    queues = yield broker.queues(sorted(queue_names))
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 807, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 209, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 810, in run
    yielded = self.gen.throw(*sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/flower/utils/broker.py", line 74, in queues
    url, auth_username=username, auth_password=password)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 807, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 209, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
ValueError: Unsupported url scheme: queues/%2F

**Comment by mher** [comment]
How do you launch flower?

**Comment by AKSHAYUBHAT** [comment]
flower --port=9555 --broker=amqp://{}:{}@localhost:5672//'.format(username,password)

I have noticed that restarting flower makes some of the errors go away. Additionally it asks me to enable RMQ management-plugin even though its already enabled.

**Comment by mher** [comment]
I'm not able to reproduce this issue. Please share the exact command line you use to launch flower. Above mentioned is not a valid bash command.

**Comment by AKSHAYUBHAT** [comment]
(.pyenv)dhcp-ccc-3494: aub3$ fab flower
[52.6.155.47] Executing task 'flower'
[localhost] local: flower --port=9555 --broker=amqp://akshay:<omitted manually>@localhost:5672//
[I 150426 10:59:19 command:112] Visit me at http://localhost:9555
[I 150426 10:59:19 command:114] Broker: amqp://akshay:**@localhost:5672//
[I 150426 10:59:19 command:117] Registered tasks: 
    ['celery.backend_cleanup',
     'celery.chain',
     'celery.chord',
     'celery.chord_unlock',
     'celery.chunks',
     'celery.group',
     'celery.map',
     'celery.starmap']
[I 150426 10:59:19 mixins:225] Connected to amqp://akshay:**@127.0.0.1:5672//

**Comment by AKSHAYUBHAT** [comment]
Actually it works now, still cannot see the count of tasks. other three graphs in monitor show up correctly. 
![screenshot 2015-04-26 11 01 33](https://cloud.githubusercontent.com/assets/35259/7337771/ae277746-ec03-11e4-8601-09d216a76b0e.png)

**Comment by snarfed** [comment]
just fyi, i'm seeing this too. originally the broker tab was blank for me. after i found [this SO question](http://stackoverflow.com/questions/18391563/celery-flowers-broker-tab-is-blank) and added the `--broker_api` flag, i started seeing this stack trace instead. details below.

```sh
$ python /.../celery flower --broker=amqp://guest:guest@localhost:5672// --broker_api=amqp://guest:guest@localhost:5672/api
[I 150629 23:48:14 command:114] Visit me at http://localhost:5555
[I 150629 23:48:14 command:116] Broker: amqp://guest:**@localhost:5672//
[I 150629 23:48:14 command:119] Registered tasks: 
    ['celery.backend_cleanup',
     'celery.chain',
     'celery.chord',
     'celery.chord_unlock',
     'celery.chunks',
     'celery.group',
     'celery.map',
     'celery.starmap']
[I 150629 23:48:14 mixins:225] Connected to amqp://guest:**@127.0.0.1:5672//
...
```

broker tab shows:

```py
lower   -> flower:0.8.2 tornado:4.2 babel:1.3
software -> celery:3.1.17 (Cipater) kombu:3.0.26 py:2.7.6
            billiard:3.3.0.20 py-amqp:1.4.5
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled



Traceback (most recent call last):
  File "/color/releases/2015-06-29-18-19-59/local/lib/python2.7/site-packages/tornado/web.py", line 1415, in _execute
    result = yield result
  File "/color/releases/2015-06-29-18-19-59/local/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/color/releases/2015-06-29-18-19-59/local/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/color/releases/2015-06-29-18-19-59/local/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/color/releases/2015-06-29-18-19-59/local/lib/python2.7/site-packages/flower/views/broker.py", line 29, in get
    queues = yield broker.queues(sorted(queue_names))
  File "/color/releases/2015-06-29-18-19-59/local/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/color/releases/2015-06-29-18-19-59/local/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/color/releases/2015-06-29-18-19-59/local/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/color/releases/2015-06-29-18-19-59/local/lib/python2.7/site-packages/flower/utils/broker.py", line 74, in queues
    url, auth_username=username, auth_password=password)
  File "/color/releases/2015-06-29-18-19-59/local/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/color/releases/2015-06-29-18-19-59/local/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
ValueError: Unsupported url scheme: queues/%2F
```

**Comment by Arvi3d** [comment]
I have the same issue.
