### ISSUE TITLE
error on http://localhost:5555/worker/celery@tattoine

### ISSUE THREAD

**Issue by brizzbane** [mher/flower#385]
flower   -> flower:0.8.1 tornado:4.1 babel:1.3
software -> celery:3.1.17 (Cipater) kombu:3.0.24 py:2.7.6
            billiard:3.3.0.20 py-amqp:1.4.6
platform -> system:Windows arch:64bit, WindowsPE imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:amqp

CELERYD_LOG_COLOR: True
CELERY_RESULT_BACKEND: 'amqp'

Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\tornado\web.py", line 1348, in _execute
    result = yield result
  File "c:\Python27\lib\site-packages\tornado\gen.py", line 807, in run
    value = future.result()
  File "c:\Python27\lib\site-packages\tornado\concurrent.py", line 209, in result
    raise_exc_info(self._exc_info)
  File "c:\Python27\lib\site-packages\tornado\gen.py", line 212, in wrapper
    yielded = next(result)
  File "c:\Python27\lib\site-packages\flower\views\workers.py", line 29, in get
    self.render("worker.html", worker=dict(worker, name=name))
  File "c:\Python27\lib\site-packages\flower\views\__init__.py", line 20, in render
    super(BaseHandler, self).render(*args, **kwargs)
  File "c:\Python27\lib\site-packages\tornado\web.py", line 664, in render
    html = self.render_string(template_name, **kwargs)
  File "c:\Python27\lib\site-packages\tornado\web.py", line 771, in render_string
    return t.generate(**namespace)
  File "c:\Python27\lib\site-packages\tornado\template.py", line 278, in generate
    return execute()
  File "worker_html.generated.py", line 403, in _tt_execute
    for name, value in worker['stats'].get('rusage', {}).items():  # worker.html:337 (via base.html:49)
AttributeError: 'unicode' object has no attribute 'items'

I'm new to using flower.  ran 'celery flower -A tasks'

**Comment by mher** [comment]
This issue has been fixed in the master version
