### ISSUE TITLE
docker build fails; cannot find pip

### ISSUE THREAD

**Issue by rwillmer** [mher/flower#394]
Following the instructions, I run "docker build -t "flower" ."

It fails with this error:

2015-05-15 10:48:32 (673 KB/s) - `get-pip.py' saved [1420671/1420671]

Traceback (most recent call last):
  File "get-pip.py", line 17853, in <module>
    main()
  File "get-pip.py", line 152, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 82, in bootstrap
    import pip
  File "/tmp/tmpHynwcd/pip.zip/pip/__init__.py", line 13, in <module>
  File "/tmp/tmpHynwcd/pip.zip/pip/utils/__init__.py", line 3, in <module>
ImportError: No module named contextlib

**Comment by mher** [comment]
Fixed by #422
