### ISSUE TITLE
support for redis unix socket

### ISSUE THREAD

**Issue by raghuramos1987** [mher/flower#401]
celery 3.1.18 has redis.sock capability. This fails with latest version of flower (master)

```
flower   -> flower:0.9.0-dev tornado:4.1 babel:1.3
software -> celery:3.1.18 (Cipater) kombu:3.0.26 py:2.7.5
            billiard:3.3.0.20 redis:2.10.1
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis+socket:///tmp/redis.sock

BROKER_URL: 'redis+redis://socket%3A%2F%2F%2Ftmp%2Fredis.sock:6379//'
CELERY_RESULT_BACKEND: 'redis+socket:///tmp/redis.sock'

Traceback (most recent call last):
  File "/home/raghu/git/env/lib/python2.7/site-packages/tornado/web.py", line 1348, in _execute
    result = yield result
  File "/home/raghu/git/env/lib/python2.7/site-packages/tornado/gen.py", line 807, in run
    value = future.result()
  File "/home/raghu/git/env/lib/python2.7/site-packages/tornado/concurrent.py", line 209, in result
    raise_exc_info(self._exc_info)
  File "/home/raghu/git/env/lib/python2.7/site-packages/tornado/gen.py", line 212, in wrapper
    yielded = next(result)
  File "/home/raghu/git/env/lib/python2.7/site-packages/flower-0.9.0-py2.7.egg/flower/views/broker.py", line 27, in get
    http_api=http_api)
  File "/home/raghu/git/env/lib/python2.7/site-packages/flower-0.9.0-py2.7.egg/flower/utils/broker.py", line 131, in __new__
    raise NotImplementedError
NotImplementedError
```

**Comment by rsung** [comment]
this is blocking us from using this tool. +1
