### ISSUE TITLE
Celery message signing results in exception

### ISSUE THREAD

**Issue by crepererum** [mher/flower#408]
When activating [Celery Message Signing](https://celery.readthedocs.org/en/latest/userguide/security.html#message-signing) flower results in the following exception while booting up:

```
[E 150608 08:35:05 concurrent:124] Future exception was never retrieved: Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 656, in callback
        result_list.append(f.result())
      File "/usr/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 396, in result
        return self.__get_result()
      File "/usr/local/lib/python2.7/site-packages/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/usr/local/lib/python2.7/site-packages/celery/app/control.py", line 90, in stats
        return self._request('stats')
      File "/usr/local/lib/python2.7/site-packages/celery/app/control.py", line 71, in _request
        timeout=self.timeout, reply=True,
      File "/usr/local/lib/python2.7/site-packages/celery/app/control.py", line 57, in _prepare
        by_node = flatten_reply(reply)
      File "/usr/local/lib/python2.7/site-packages/celery/app/control.py", line 32, in flatten_reply
        nodes.update(item)
    ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

Followed by multiple similar exceptions. Using flower is impossible afterwards because it lists the workers but selecting them results to "I don't know that worker"-like errors.

**Comment by mher** [comment]
Control commands have been refactored. Reopen this issue if you still experience the problem.
