### ISSUE TITLE
Cannot add a consumer.

### ISSUE THREAD

**Issue by adilansari** [mher/flower#409]
Tried to add a consumer and this happened.
```
flower   -> 0.7.3
software -> celery:3.1.18 (Cipater) kombu:3.0.25 py:2.7.6
            billiard:3.3.0.20 py-amqp:1.4.6
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1346, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 2626, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flower/api/control.py", line 339, in post
    workername, self.error_reason(workername, response)
TypeError: not enough arguments for format string
```

**Comment by mher** [comment]
This bug already fixed. Please try to update the flower version.
