### ISSUE TITLE
Getting an error when starting celery flower or refreshing worker?

### ISSUE THREAD

**Issue by bigblind** [mher/flower#412]
I got the following error, this also includes the info printed on the "it looks like you've found a bug" dialog:

````
flower   -> flower:0.8.2 tornado:4.2 babel:1.3
software -> celery:3.1.18 (Cipater) kombu:3.0.26 py:2.7.6
            billiard:3.3.0.20 redis:2.10.3
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://@localhost:6379/0

BROKER_URL: 'redis://localhost:6379/0'
CELERY_TRACK_STARTED: True
CELERY_RESULT_BACKEND: 'redis://@localhost:6379/0'

Traceback (most recent call last):
  File "/Users/frederikcreemers/.virtualenvs/podato-server/lib/python2.7/site-packages/tornado/web.py", line 1415, in _execute
    result = yield result
  File "/Users/frederikcreemers/.virtualenvs/podato-server/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/Users/frederikcreemers/.virtualenvs/podato-server/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/Users/frederikcreemers/.virtualenvs/podato-server/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/frederikcreemers/.virtualenvs/podato-server/lib/python2.7/site-packages/flower/api/workers.py", line 62, in get
    yield self.update_cache(workername=workername)
  File "/Users/frederikcreemers/.virtualenvs/podato-server/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/Users/frederikcreemers/.virtualenvs/podato-server/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/Users/frederikcreemers/.virtualenvs/podato-server/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/frederikcreemers/.virtualenvs/podato-server/lib/python2.7/site-packages/flower/api/control.py", line 23, in update_cache
    app=self.application)
  File "/Users/frederikcreemers/.virtualenvs/podato-server/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/Users/frederikcreemers/.virtualenvs/podato-server/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/Users/frederikcreemers/.virtualenvs/podato-server/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/frederikcreemers/.virtualenvs/podato-server/lib/python2.7/site-packages/flower/api/control.py", line 38, in update_workers
    results = yield futures
  File "/Users/frederikcreemers/.virtualenvs/podato-server/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/Users/frederikcreemers/.virtualenvs/podato-server/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/Users/frederikcreemers/.virtualenvs/podato-server/lib/python2.7/site-packages/tornado/gen.py", line 656, in callback
    result_list.append(f.result())
  File "/Users/frederikcreemers/.virtualenvs/podato-server/lib/python2.7/site-packages/concurrent/futures/_base.py", line 396, in result
    return self.__get_result()
  File "/Users/frederikcreemers/.virtualenvs/podato-server/lib/python2.7/site-packages/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/frederikcreemers/.virtualenvs/podato-server/lib/python2.7/site-packages/celery/app/control.py", line 93, in revoked
    return self._request('dump_revoked')
  File "/Users/frederikcreemers/.virtualenvs/podato-server/lib/python2.7/site-packages/celery/app/control.py", line 71, in _request
    timeout=self.timeout, reply=True,
  File "/Users/frederikcreemers/.virtualenvs/podato-server/lib/python2.7/site-packages/celery/app/control.py", line 307, in broadcast
    limit, callback, channel=channel,
  File "/Users/frederikcreemers/.virtualenvs/podato-server/lib/python2.7/site-packages/kombu/pidbox.py", line 300, in _broadcast
    channel=chan)
  File "/Users/frederikcreemers/.virtualenvs/podato-server/lib/python2.7/site-packages/kombu/pidbox.py", line 339, in _collect
    self.connection.drain_events(timeout=timeout)
  File "/Users/frederikcreemers/.virtualenvs/podato-server/lib/python2.7/site-packages/kombu/connection.py", line 275, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/Users/frederikcreemers/.virtualenvs/podato-server/lib/python2.7/site-packages/kombu/transport/virtual/__init__.py", line 845, in drain_events
    queue, message))
KeyError: u"Message for queue '34cf46ab-96ce-31cd-88de-744705a37d34.reply.celery.pidbox' without consumers: {'body': 'eyJjZWxlcnlAbXltYWMubG9jYWwiOiB7IkNFTEVSWV9JTkNMVURFIjogWyJ3ZWJhcHAucG9kY2FzdHMuY3Jhd2xlciIsICJjZWxlcnkuYXBwLmJ1aWx0aW5zIl0sICJCUk9LRVJfVVJMIjogInJlZGlzOi8vbG9jYWxob3N0OjYzNzkvMCIsICJDRUxFUllfVFJBQ0tfU1RBUlRFRCI6IHRydWUsICJDRUxFUllfUkVTVUxUX0JBQ0tFTkQiOiAicmVkaXM6Ly9AbG9jYWxob3N0OjYzNzkvMCJ9fQ==', 'headers': {'ticket': '2d836f13-b1da-45a5-b9d8-1f461e07624e', 'clock': 30731}, 'content-type': 'application/json', 'properties': {'body_encoding': 'base64', 'delivery_info': {'priority': 0, 'routing_key': '34cf46ab-96ce-31cd-88de-744705a37d34', 'exchange': 'reply.celery.pidbox'}, 'delivery_mode': 1, 'delivery_tag': '28fcb553-cd74-4023-93a3-c2eba5f783e6'}, 'content-encoding': 'utf-8'}"
````
Let me kno if you need any other info.

**Comment by mher** [comment]
This has been already fixed. Thanks for opening an issue.

**Comment by ibigbug** [comment]
Fixed in what version?

I'm also having a trouble with this.
