### ISSUE TITLE
Error viewing broker

### ISSUE THREAD

**Issue by jeromedoyle** [mher/flower#418]
I received this when visiting the broker tab.
```
flower   -> flower:0.8.2 tornado:4.2 babel:1.3
software -> celery:3.1.18 (Cipater) kombu:3.0.26 py:3.4.2
            billiard:3.3.0.20 py-amqp:1.4.6
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled



Traceback (most recent call last):
  File "/srv/virtualenvs/paceintegration_staging/lib/python3.4/site-packages/tornado/web.py", line 1415, in _execute
    result = yield result
  File "/srv/virtualenvs/paceintegration_staging/lib/python3.4/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/srv/virtualenvs/paceintegration_staging/lib/python3.4/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/srv/virtualenvs/paceintegration_staging/lib/python3.4/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/srv/virtualenvs/paceintegration_staging/lib/python3.4/site-packages/flower/views/broker.py", line 29, in get
    queues = yield broker.queues(sorted(queue_names))
  File "/srv/virtualenvs/paceintegration_staging/lib/python3.4/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/srv/virtualenvs/paceintegration_staging/lib/python3.4/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/srv/virtualenvs/paceintegration_staging/lib/python3.4/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/srv/virtualenvs/paceintegration_staging/lib/python3.4/site-packages/flower/utils/broker.py", line 74, in queues
    url, auth_username=username, auth_password=password)
  File "/srv/virtualenvs/paceintegration_staging/lib/python3.4/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/srv/virtualenvs/paceintegration_staging/lib/python3.4/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/srv/virtualenvs/paceintegration_staging/lib/python3.4/site-packages/tornado/simple_httpclient.py", line 207, in __init__
    self.request.url)
ValueError: Unsupported url scheme: queues/%2Fpaceintegration_staging```

**Comment by skabbit** [comment]
got the similar error on broker tab:


flower   -> flower:0.8.2 tornado:4.2 babel:1.3
software -> celery:3.1.18 (Cipater) kombu:3.0.26 py:2.7.9
            billiard:3.3.0.20 librabbitmq:1.6.1
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:librabbitmq results:amqp

Traceback (most recent call last):
  File "/var/www/sw/local/lib/python2.7/site-packages/tornado/web.py", line 1415, in _execute
    result = yield result
  File "/var/www/sw/local/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/var/www/sw/local/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/var/www/sw/local/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/var/www/sw/local/lib/python2.7/site-packages/flower/views/broker.py", line 29, in get
    queues = yield broker.queues(sorted(queue_names))
  File "/var/www/sw/local/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/var/www/sw/local/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/var/www/sw/local/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/var/www/sw/local/lib/python2.7/site-packages/flower/utils/broker.py", line 74, in queues
    url, auth_username=username, auth_password=password)
  File "/var/www/sw/local/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/var/www/sw/local/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
ValueError: Unsupported url scheme: queues/%2F

**Comment by dhui** [comment]
Same here:
```
Celery Flower
Dashboard
Tasks
Broker
Monitor
Docs
Code
It looks like you have found a bug! You can help to improve Celery Flower by opening an issue in https://github.com/mher/flower/issues

flower   -> flower:0.8.2 tornado:4.2 babel:1.3
software -> celery:3.1.18 (Cipater) kombu:3.0.26 py:2.7.6
            billiard:3.3.0.20 librabbitmq:1.6.1
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:librabbitmq results:store.celery.backends.cache.CacheBackend

CELERYBEAT_SCHEDULE: {
    'daily_load_campaigns_for_users': {   'schedule': <crontab: 23 1 * * * (m/h/d/dM/MY)>,
                                          'task': 'store.ads.tasks.load_campaigns_for_users'}}
BROKER_URL: 'amqp://celery:********@myhost.internal:5672/celery'
CELERY_RESULT_BACKEND: 'store.celery.backends.cache.CacheBackend'

Traceback (most recent call last):
  File "/mnt/encrypted/repos/myrepo/.virtualenv/local/lib/python2.7/site-packages/tornado/web.py", line 1415, in _execute
    result = yield result
  File "/mnt/encrypted/repos/myrepo/.virtualenv/local/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/mnt/encrypted/repos/myrepo/.virtualenv/local/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/mnt/encrypted/repos/myrepo/.virtualenv/local/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/mnt/encrypted/repos/myrepo/.virtualenv/local/lib/python2.7/site-packages/flower/views/broker.py", line 29, in get
    queues = yield broker.queues(sorted(queue_names))
  File "/mnt/encrypted/repos/myrepo/.virtualenv/local/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/mnt/encrypted/repos/myrepo/.virtualenv/local/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/mnt/encrypted/repos/myrepo/.virtualenv/local/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/mnt/encrypted/repos/myrepo/.virtualenv/local/lib/python2.7/site-packages/flower/utils/broker.py", line 74, in queues
    url, auth_username=username, auth_password=password)
  File "/mnt/encrypted/repos/myrepo/.virtualenv/local/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/mnt/encrypted/repos/myrepo/.virtualenv/local/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
ValueError: Unsupported url scheme: queues/celery
```

Note: The results backend I'm using is a local copy of the `CacheBackend` from djcelery. This doesn't seem related to the issue though.

**Comment by rico-suave** [comment]
I have the same error on Windows 7:
```
flower   -> flower:0.8.2 tornado:4.2.1 babel:1.3
software -> celery:3.1.18 (Cipater) kombu:3.0.26 py:2.7.4
            billiard:3.3.0.20 py-amqp:1.4.6
platform -> system:Windows arch:32bit, WindowsPE imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:amqp

BROKER_HEARTBEAT: 30
CELERY_SEND_EVENTS: True
CELERY_TASK_RESULT_EXPIRES: 14400
CELERY_RESULT_PERSISTENT: True
CELERYD_PREFETCH_MULTIPLIER: 1
CELERY_RESULT_BACKEND: 'amqp'
CELERYD_POOL_RESTARTS: True

Traceback (most recent call last):
  File "C:\Users\erik\workspace\gmtasks_project\lib\site-packages\tornado\web.py", line 1415, in _execute
    result = yield result
  File "C:\Users\erik\workspace\gmtasks_project\lib\site-packages\tornado\gen.py", line 870, in run
    value = future.result()
  File "C:\Users\erik\workspace\gmtasks_project\lib\site-packages\tornado\concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "C:\Users\erik\workspace\gmtasks_project\lib\site-packages\tornado\gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\erik\workspace\gmtasks_project\lib\site-packages\flower\views\broker.py", line 29, in get
    queues = yield broker.queues(sorted(queue_names))
  File "C:\Users\erik\workspace\gmtasks_project\lib\site-packages\tornado\gen.py", line 870, in run
    value = future.result()
  File "C:\Users\erik\workspace\gmtasks_project\lib\site-packages\tornado\concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "C:\Users\erik\workspace\gmtasks_project\lib\site-packages\tornado\gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\erik\workspace\gmtasks_project\lib\site-packages\flower\utils\broker.py", line 74, in queues
    url, auth_username=username, auth_password=password)
  File "C:\Users\erik\workspace\gmtasks_project\lib\site-packages\tornado\gen.py", line 870, in run
    value = future.result()
  File "C:\Users\erik\workspace\gmtasks_project\lib\site-packages\tornado\concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
ValueError: Unsupported url scheme: queues/%2F
```

I might add that the reason I'm looking into flower is that it seems that some of our tasks are not picked up by the celery worker processes. I wanted to use Flower to troubleshoot this.
The two problems might be related.
What we have in celery is a main tasks that spawns a set of smaller tasks using delay(). The main tasks is executed, the smaller tasks are put in the queue, but aren't picked up by the worker process.

It seems currently that this problem originates in version 3.1.13 of celery. 3.1.12 seems to work.

**Comment by LaurentGrimaud** [comment]
Hi there,

I think the problem here may be that rabbitmq management api protocol is http, not amqp.

Please note also that the default management port for rabbitmq is 15672, and not 5672, and the default endpoint is /api

So, the --broker-api option in the command above should be something like:
--broker-api=http://guest:XXXX@localhost:15672/api

Everything is doing fine in my flower install with this.

Hope it helps...

**Comment by dhui** [comment]
Confirmed that specifying `http` instead of `amqp` as the protocol works!

**Comment by rico-suave** [comment]
Confirmed as well. Thanks @LaurentGrimaud !

**Comment by mher** [comment]
RabbitMQ HTTP API validation is added in https://github.com/mher/flower/commit/f43fbdfa66438eef22518ccf76838fe135466d9a

**Comment by dhui** [comment]
Thanks for adding broker api validation!

**Comment by jeromedoyle** [comment]
That fixed it for me. Thanks!
