### ISSUE TITLE
satisfies_search_terms() takes exactly 5 arguments (4 given)

### ISSUE THREAD

**Issue by dz0ny** [mher/flower#424]
flower   -> flower:0.9.0-dev tornado:4.2 babel:1.3
software -> celery:3.1.18 (Cipater) kombu:3.0.26 py:2.7.4
            billiard:3.3.0.20 py-amqp:1.4.6
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled

Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/site-packages/tornado/web.py", line 1413, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/tornado/web.py", line 2717, in wrapper
    return method(self, *args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/flower/views/tasks.py", line 88, in get
    search=search
  File "/app/.heroku/python/lib/python2.7/site-packages/flower/views/__init__.py", line 20, in render
    super(BaseHandler, self).render(*args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/tornado/web.py", line 704, in render
    html = self.render_string(template_name, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/tornado/web.py", line 811, in render_string
    return t.generate(**namespace)
  File "/app/.heroku/python/lib/python2.7/site-packages/tornado/template.py", line 278, in generate
    return execute()
  File "tasks_html.generated.py", line 225, in _tt_execute
    for uuid, task in tasks:  # tasks.html:151 (via base.html:49)
  File "/app/.heroku/python/lib/python2.7/site-packages/flower/utils/tasks.py", line 44, in iter_tasks
    if not satisfies_search_terms(task, any_value_search_term, result_search_term, kwargs_search_terms):
TypeError: satisfies_search_terms() takes exactly 5 arguments (4 given)

**Comment by aphillipo** [comment]
I too get this error recently.  Very strange as I'm sure it was not happening until today.

**Comment by aphillipo** [comment]
flower   -> flower:0.9.0-dev tornado:4.1 babel:1.3
software -> celery:3.1.18 (Cipater) kombu:3.0.26 py:2.7.6
            billiard:3.3.0.20 py-amqp:1.4.6
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:amqp://

CELERY_CHORD_PROPAGATES: True
CELERY_RESULT_ENGINE_OPTIONS: {
    'echo': True}
CELERY_RESULT_SERIALIZER: 'json'
CELERY_ACCEPT_CONTENT: ['json']
CELERY_BROKER_URL: 'amqp://guest:********@localhost:5672//'
CELERY_IMPORTS: ['dave.tools', 'dave.test_types']
CELERY_ANNOTATIONS: {
    'celery.chord_unlock': {   'soft_time_limit': 10}}
CELERYD_CONCURRENCY: 10
CELERY_TASK_SERIALIZER: 'json'
CELERY_RESULT_BACKEND: 'amqp://'

Traceback (most recent call last):
  File "/Users/aphillipo/Sites/work/dave/venv_dave/lib/python2.7/site-packages/tornado/web.py", line 1346, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/Users/aphillipo/Sites/work/dave/venv_dave/lib/python2.7/site-packages/tornado/web.py", line 2626, in wrapper
    return method(self, *args, **kwargs)
  File "/Users/aphillipo/Sites/work/dave/venv_dave/lib/python2.7/site-packages/flower/views/tasks.py", line 88, in get
    search=search
  File "/Users/aphillipo/Sites/work/dave/venv_dave/lib/python2.7/site-packages/flower/views/__init__.py", line 20, in render
    super(BaseHandler, self).render(*args, **kwargs)
  File "/Users/aphillipo/Sites/work/dave/venv_dave/lib/python2.7/site-packages/tornado/web.py", line 664, in render
    html = self.render_string(template_name, **kwargs)
  File "/Users/aphillipo/Sites/work/dave/venv_dave/lib/python2.7/site-packages/tornado/web.py", line 771, in render_string
    return t.generate(**namespace)
  File "/Users/aphillipo/Sites/work/dave/venv_dave/lib/python2.7/site-packages/tornado/template.py", line 278, in generate
    return execute()
  File "tasks_html.generated.py", line 225, in _tt_execute
    for uuid, task in tasks:  # tasks.html:151 (via base.html:49)
  File "/Users/aphillipo/Sites/work/dave/venv_dave/lib/python2.7/site-packages/flower/utils/tasks.py", line 44, in iter_tasks
    if not satisfies_search_terms(task, any_value_search_term, result_search_term, kwargs_search_terms):
TypeError: satisfies_search_terms() takes exactly 5 arguments (4 given)

**Comment by mher** [comment]
Fixed by #428
