### ISSUE TITLE
Flower "Tasks" fails

### ISSUE THREAD

**Issue by digitaldavenyc** [mher/flower#425]
New to celery and encountered an error using the development version. Error occurs on the "Tasks" page.

```
flower   -> flower:0.9.0-dev tornado:4.2 babel:1.3
software -> celery:3.1.18 (Cipater) kombu:3.0.26 py:3.4.0
            billiard:3.3.0.20 redis:2.10.3
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:redis results:disabled



Traceback (most recent call last):
  File "/source/groovemaps/lib/python3.4/site-packages/tornado/web.py", line 1413, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/source/groovemaps/lib/python3.4/site-packages/tornado/web.py", line 2717, in wrapper
    return method(self, *args, **kwargs)
  File "/source/groovemaps/lib/python3.4/site-packages/flower/views/tasks.py", line 88, in get
    search=search
  File "/source/groovemaps/lib/python3.4/site-packages/flower/views/__init__.py", line 20, in render
    super(BaseHandler, self).render(*args, **kwargs)
  File "/source/groovemaps/lib/python3.4/site-packages/tornado/web.py", line 704, in render
    html = self.render_string(template_name, **kwargs)
  File "/source/groovemaps/lib/python3.4/site-packages/tornado/web.py", line 811, in render_string
    return t.generate(**namespace)
  File "/source/groovemaps/lib/python3.4/site-packages/tornado/template.py", line 278, in generate
    return execute()
  File "tasks_html.generated.py", line 225, in _tt_execute
    for uuid, task in tasks:  # tasks.html:151 (via base.html:49)
  File "/source/groovemaps/lib/python3.4/site-packages/flower/utils/tasks.py", line 44, in iter_tasks
    if not satisfies_search_terms(task, any_value_search_term, result_search_term, kwargs_search_terms):
TypeError: satisfies_search_terms() missing 1 required positional argument: 'kwargs_search_terms'
```

**Comment by mher** [comment]
This has been already fixed by #428
