### ISSUE TITLE
Configuration to use json serializer not working ?

### ISSUE THREAD

**Issue by asmodehn** [mher/flower#430]
I am using Celery with : 
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

I added this into flower_config.py but it seems it is still serializing task with pickle, since my worker tells me : 
```
body: '\x80\x02}q\x01(U\x07expiresq\x02NU\x03utcq\x03\x88U\x04argsq\x04]q\x05U\x05chordq\x06NU\tcallbacksq\x07NU\x08errbacksq\x08NU\x07tasksetq\tNU\x02idq\nU$c9929e37-85ee-4cca-8cb7-8ba325a0e282q\x0bU\x07retriesq\x0cK\x00U\x04taskq\rU1gopher_rocon_bootstrap.celery_tasks.delivery_rappq\x0eU\ttimelimitq\x0fNN\x86U\x03etaq\x10NU\x06kwargsq\x11}q\x12u.' (245b)
Traceback (most recent call last):
  File "/home/alexv/ROS/gopher_rocon/src/flask-ext-catkin/src/kombu/messaging.py", line 590, in _receive_callback
    decoded = None if on_m else message.decode()
  File "/home/alexv/ROS/gopher_rocon/src/flask-ext-catkin/src/kombu/message.py", line 142, in decode
    self.content_encoding, accept=self.accept)
  File "/home/alexv/ROS/gopher_rocon/src/flask-ext-catkin/src/kombu/serialization.py", line 174, in loads
    raise self._for_untrusted_content(content_type, 'untrusted')
ContentDisallowed: Refusing to deserialize untrusted content of type pickle (application/x-python-serialize)
```

So it seems my configuration is ignored... and I cannot find the place where the flowerconfig.py contents are passed to the celery app...

Any hints ? any other way to use json instead ?

**Comment by asmodehn** [comment]
OK I think I found the reason.
There are both : 
`--conf` option : accept a filename for flower configuration
`--config` option : accept a module for celery configuration

A little confusing... IMHO it would be nicer if we could merge both configs somehow...
