### ISSUE TITLE
ConnectionError

### ISSUE THREAD

**Issue by deter3** [mher/flower#434]
I am new to flower and i just follow the instructions saying I should file a bug here when something went wrong with my flower .  here is the info.

flower   -> flower:0.8.2 tornado:4.2 babel:1.3
software -> celery:3.1.18 (Cipater) kombu:3.0.26 py:2.7.6
            billiard:3.3.0.20 librabbitmq:1.6.1
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:librabbitmq results:disabled

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/tornado/web.py", line 1415, in _execute
    result = yield result
  File "/Library/Python/2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/Library/Python/2.7/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/Library/Python/2.7/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/Library/Python/2.7/site-packages/flower/api/workers.py", line 62, in get
    yield self.update_cache(workername=workername)
  File "/Library/Python/2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/Library/Python/2.7/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/Library/Python/2.7/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/Library/Python/2.7/site-packages/flower/api/control.py", line 23, in update_cache
    app=self.application)
  File "/Library/Python/2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/Library/Python/2.7/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/Library/Python/2.7/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/Library/Python/2.7/site-packages/flower/api/control.py", line 38, in update_workers
    results = yield futures
  File "/Library/Python/2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/Library/Python/2.7/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/Library/Python/2.7/site-packages/tornado/gen.py", line 656, in callback
    result_list.append(f.result())
  File "/Library/Python/2.7/site-packages/concurrent/futures/_base.py", line 396, in result
    return self.__get_result()
  File "/Library/Python/2.7/site-packages/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Library/Python/2.7/site-packages/celery/app/control.py", line 103, in active_queues
    return self._request('active_queues')
  File "/Library/Python/2.7/site-packages/celery/app/control.py", line 71, in _request
    timeout=self.timeout, reply=True,
  File "/Library/Python/2.7/site-packages/celery/app/control.py", line 307, in broadcast
    limit, callback, channel=channel,
  File "/Library/Python/2.7/site-packages/kombu/pidbox.py", line 294, in _broadcast
    serializer=serializer)
  File "/Library/Python/2.7/site-packages/kombu/pidbox.py", line 259, in _publish
    maybe_declare(self.reply_queue(channel))
  File "/Library/Python/2.7/site-packages/kombu/common.py", line 113, in maybe_declare
    return _maybe_declare(entity, declared, ident, channel)
  File "/Library/Python/2.7/site-packages/kombu/common.py", line 120, in _maybe_declare
    entity.declare()
  File "/Library/Python/2.7/site-packages/kombu/entity.py", line 514, in declare
    self.exchange.declare(nowait)
  File "/Library/Python/2.7/site-packages/kombu/entity.py", line 174, in declare
    nowait=nowait, passive=passive,
  File "/Library/Python/2.7/site-packages/librabbitmq/__init__.py", line 133, in exchange_declare
    auto_delete, arguments or {},
ConnectionError: exchange.declare: server connection error 320, message: CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'

**Comment by mher** [comment]
Fixed, thanks!
