### ISSUE TITLE
pkg_resources.DistributionNotFound: futures 

### ISSUE THREAD

**Issue by dbiswas1** [mher/flower#446]
Hi,
 i am using Flower first time i installed flower using pip and when i do "flower --port=5555", i get folowing error i have also installed futures using pip, can anybody help on this 

  File "/usr/local/bin/flower", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 2671, in <module>
    working_set.require(**requires**)
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 654, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 552, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: futures

**Comment by MattBlack85** [comment]
same here, any hint?

**Comment by mozillazg** [comment]
Maybe you need upgrade distribute, try this:

```
pip install --upgrade setuptools
```

**Comment by pcraston** [comment]
same problem here...

**Comment by MattBlack85** [comment]
I managed to make it work but I never found the root, there could be some problem with the virtualenv

**Comment by pannal** [comment]
This is still happening for me. Version 0.9.2, `Successfully installed amqp-2.2.2 babel-2.5.1 backports-abc-0.5 billiard-3.5.0.3 celery-4.1.0 certifi-2017.7.27.1 flower-0.9.2 futures-3.1.1 kombu-4.1.0 pytz-2017.2 singledispatch-3.4.0.3 six-1.11.0 tornado-4.5.2 vine-1.1.4`

```
flower --version
Traceback (most recent call last):
  File "/home/paperc/.pyenv/versions/paperc/bin/flower", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2671, in <module>
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 654, in require
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 552, in resolve
pkg_resources.DistributionNotFound: futures
```

**Comment by eltismerino** [comment]
This is still happening for me. Version 0.9.2, `Successfully installed amqp-2.2.2 babel-2.5.1 backports-abc-0.5 billiard-3.5.0.3 celery-4.1.0 certifi-2017.7.27.1 flower-0.9.2 futures-3.1.1 kombu-4.1.0 pytz-2017.2 singledispatch-3.4.0.3 six-1.11.0 tornado-4.5.2 vine-1.1.4`

```
flower --version
Traceback (most recent call last):
  File "/home/paperc/.pyenv/versions/paperc/bin/flower", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2671, in <module>
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 654, in require
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 552, in resolve
pkg_resources.DistributionNotFound: futures
```
