### ISSUE TITLE
Unable to check broker tab

### ISSUE THREAD

**Issue by sunilomrey** [mher/flower#447]
flower   -> flower:0.9.0-dev tornado:4.2.1 babel:2.0
software -> celery:3.1.18 (Cipater) kombu:3.0.21 py:2.7.6
            billiard:3.3.0.20 py-amqp:1.4.6
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:amqp://

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1415, in _execute
    result = yield result
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 230, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python2.7/dist-packages/flower/views/broker.py", line 28, in get
    http_api=http_api, broker_options=broker_options)
  File "/usr/local/lib/python2.7/dist-packages/flower/utils/broker.py", line 160, in __new__
    return RabbitMQ(broker_url, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flower/utils/broker.py", line 62, in __init__
    self.validate_http_api(http_api)
  File "/usr/local/lib/python2.7/dist-packages/flower/utils/broker.py", line 94, in validate_http_api
    raise ValueError("Invalid http api schema: %s" % url.scheme)
ValueError: Invalid http api schema: amqp

**Comment by mher** [comment]
How do you run flower?

**Comment by mher** [comment]
`--broker-api` option should start with `http`. See http://flower.readthedocs.org/en/latest/config.html#broker-api
