### ISSUE TITLE
worker error on dashboard

### ISSUE THREAD

**Issue by patelpritesh** [mher/flower#449]
flower   -> flower:0.8.3 tornado:4.2.1 babel:2.0
software -> celery:3.0.13 (Chiastic Slide) kombu:2.5.4 py:2.7.5
            billiard:2.7.3.19 py-amqp:N/A
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> djcelery.loaders.DjangoLoader
settings -> transport:amqp results:database

Traceback (most recent call last):
  File "/home/ec2-user/env/lib/python2.7/site-packages/tornado/web.py", line 1415, in _execute
    result = yield result
  File "/home/ec2-user/env/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/home/ec2-user/env/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/home/ec2-user/env/lib/python2.7/site-packages/tornado/gen.py", line 230, in wrapper
    yielded = next(result)
  File "/home/ec2-user/env/lib/python2.7/site-packages/flower/views/dashboard.py", line 42, in get
    info.update(self._as_dict(worker))
  File "/home/ec2-user/env/lib/python2.7/site-packages/flower/views/dashboard.py", line 49, in _as_dict
    return dict((k, worker.__getattribute__(k)) for k in worker._fields)
  File "/home/ec2-user/env/lib/python2.7/site-packages/celery/datastructures.py", line 217, in __getattr__
    "'%s' object has no attribute '%s'" % (type(self).__name__, k))
AttributeError: 'Worker' object has no attribute '_fields'

**Comment by mher** [comment]
Version 0.8.3 works only with celery>3.1

**Comment by caiofbpa** [comment]
I'm having this same error using flower 0.8.2 and celery 3.0.24. Which versions should I use?

**Comment by mher** [comment]
celery>3.1
