### ISSUE TITLE
Refreshing multiple times to get current workers

### ISSUE THREAD

**Issue by asmodehn** [mher/flower#455]
I didn't investigate more than that :

flower   -> flower:0.8.2 tornado:4.0.2 babel:1.3
software -> celery:3.1.18 (Cipater) kombu:3.0.26 py:2.7.6
            billiard:3.3.0.20 redis:2.7.2
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://localhost:6379

BROKER_URL: 'redis://localhost:6379//'
CELERY_REDIS_SCHEDULER_URL: 'redis://localhost:6379/2'
CELERY_RESULT_SERIALIZER: 'json'
CELERY_ACCEPT_CONTENT: ['application/json']
TESTING: False
CELERYBEAT_SYNC_EVERY: 1
CELERY_TRACK_STARTED: True
CELERYD_PREFETCH_MULTIPLIER: 1
DEBUG: False
CELERY_ALWAYS_EAGER: False
CELERYBEAT_MAX_LOOP_INTERVAL: 30
CELERY_TASK_SERIALIZER: 'json'
CELERY_REDIS_SCHEDULER_KEY_PREFIX: '********'
CELERY_RESULT_BACKEND: 'redis://localhost:6379'

Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/tornado/web.py", line 1334, in _execute
    result = yield result
  File "/opt/ros/indigo/lib/python2.7/dist-packages/tornado/gen.py", line 628, in run
    value = future.result()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/tornado/concurrent.py", line 109, in result
    raise_exc_info(self._exc_info)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/tornado/gen.py", line 631, in run
    yielded = self.gen.throw(*sys.exc_info())
  File "/opt/alexv/gopher_concert/src/flask-ext-catkin/src/flower/api/workers.py", line 62, in get
    yield self.update_cache(workername=workername)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/tornado/gen.py", line 628, in run
    value = future.result()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/tornado/concurrent.py", line 109, in result
    raise_exc_info(self._exc_info)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/tornado/gen.py", line 631, in run
    yielded = self.gen.throw(*sys.exc_info())
  File "/opt/alexv/gopher_concert/src/flask-ext-catkin/src/flower/api/control.py", line 23, in update_cache
    app=self.application)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/tornado/gen.py", line 628, in run
    value = future.result()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/tornado/concurrent.py", line 109, in result
    raise_exc_info(self._exc_info)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/tornado/gen.py", line 631, in run
    yielded = self.gen.throw(*sys.exc_info())
  File "/opt/alexv/gopher_concert/src/flask-ext-catkin/src/flower/api/control.py", line 38, in update_workers
    results = yield futures
  File "/opt/ros/indigo/lib/python2.7/dist-packages/tornado/gen.py", line 628, in run
    value = future.result()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/tornado/concurrent.py", line 109, in result
    raise_exc_info(self._exc_info)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/tornado/gen.py", line 464, in callback
    result_list = [i.result() for i in children]
  File "/usr/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 397, in result
    return self.__get_result()
  File "/usr/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 356, in __get_result
    raise self._exception
KeyError: u"Message for queue 'e0ecdd1b-4f04-303f-9be2-31d7a42f510e.reply.celery.pidbox' without consumers: {'body': 'eyJjZWxlcnlAYWxleHYtUEMiOiB7IkNFTEVSWV9UQVNLX1NFUklBTElaRVIiOiAianNvbiIsICJDRUxFUllfQUxXQVlTX0VBR0VSIjogZmFsc2UsICJDRUxFUllfUkVTVUxUX1NFUklBTElaRVIiOiAianNvbiIsICJDRUxFUllfQUNDRVBUX0NPTlRFTlQiOiBbImFwcGxpY2F0aW9uL2pzb24iXSwgIkNFTEVSWV9JTkNMVURFIjogWyJnb3BoZXJfdGFza3MudGFza3MiLCAiY2VsZXJ5LmFwcC5idWlsdGlucyIsICJjZWxlcm9zLmFwcCJdLCAiVEVTVElORyI6IGZhbHNlLCAiQ0VMRVJZX1JFRElTX1NDSEVEVUxFUl9VUkwiOiAicmVkaXM6Ly9sb2NhbGhvc3Q6NjM3OS8yIiwgIkNFTEVSWV9UUkFDS19TVEFSVEVEIjogdHJ1ZSwgIkNFTEVSWURfUFJFRkVUQ0hfTVVMVElQTElFUiI6IDEsICJERUJVRyI6IGZhbHNlLCAiQ0VMRVJZQkVBVF9TWU5DX0VWRVJZIjogMSwgIkNFTEVSWUJFQVRfTUFYX0xPT1BfSU5URVJWQUwiOiAzMCwgIkJST0tFUl9VUkwiOiAicmVkaXM6Ly9sb2NhbGhvc3Q6NjM3OS8vIiwgIkNFTEVSWV9SRURJU19TQ0hFRFVMRVJfS0VZX1BSRUZJWCI6ICIqKioqKioqKiIsICJDRUxFUllfUkVTVUxUX0JBQ0tFTkQiOiAicmVkaXM6Ly9sb2NhbGhvc3Q6NjM3OSJ9fQ==', 'headers': {'ticket': '8f7e2cf6-fed0-4778-972d-e68ce81b4996', 'clock': 110}, 'content-type': 'application/json', 'properties': {'body_encoding': 'base64', 'delivery_info': {'priority': 0, 'routing_key': 'e0ecdd1b-4f04-303f-9be2-31d7a42f510e', 'exchange': 'reply.celery.pidbox'}, 'delivery_mode': 1, 'delivery_tag': 'e4443a3a-4f5a-4c79-b9f4-8878855595a5'}, 'content-encoding': 'utf-8'}"

**Comment by asmodehn** [comment]
FYI this change seems to at least avoid breaking (500) flower when celery command returns an exception. Note that it may not be what we want ( is hiding celery crash a good thing ? ).

```diff
---------------------------- flower/api/control.py ----------------------------
index 3ea3251..f18ac3e 100644
@@ -35,7 +35,14 @@ class ControlHandler(BaseHandler):
         for method in cls.INSPECT_METHODS:
             futures.append(app.delay(getattr(inspect, method)))
 
-        results = yield futures
+        results = []
+        for i, future in enumerate(futures):
+            if future.exception() is None:
+                fres = yield future
+                results.append(fres)
+            else:
+                logger.warning("Future state : %r except : %r res : %r", future._state, future._exception, future._result)
+                results.append(None)
 
         for i, result in enumerate(results):
             if result is None:
```

**Comment by mher** [comment]
Try to increase inspect timeout with `--inspect-timeout` option
