### ISSUE TITLE
AttributeError: 'Worker' object has no attribute '_fields'

### ISSUE THREAD

**Issue by solomon-negusse** [mher/flower#458]
I just installed the latest version of flower from github and i'm hitting the following error which maybe a bug.  The celery workers and tasks are running with no problems.
```
flower   -> flower:0.8.3 tornado:4.2.1 babel:2.0
software -> celery:3.0.22 (Chiastic Slide) kombu:2.5.16 py:2.7.3
            billiard:2.7.3.34 redis:2.10.3
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://localhost/0

CELERY_ENABLE_UTC: True
CELERYBEAT_SCHEDULE: {
    'pull_ibwc': {   'schedule': <crontab: 5 */4 * * * (m/h/d/dM/MY)>,
                     'task': 'tasks.update_ibwc_data'},
    'pull_lcra': {   'schedule': <crontab: 5 */6 * * * (m/h/d/dM/MY)>,
                     'task': 'tasks.update_lcra_data'},
    'pull_usace': {   'schedule': <crontab: 5 */6 * * * (m/h/d/dM/MY)>,
                      'task': 'tasks.update_usace_data'},
    'pull_usbr': {   'schedule': <crontab: 5 */6 * * * (m/h/d/dM/MY)>,
                     'task': 'tasks.update_usbr_data'},
    'pull_usgs': {   'schedule': <crontab: 15 */6 * * * (m/h/d/dM/MY)>,
                     'task': 'tasks.update_usgs_data'},
    'pull_usgs_heavy': {   'schedule': <crontab: 5 21 * * * (m/h/d/dM/MY)>,
                           'task': 'tasks.update_usgs_provisional'},
    'purge_usgs_removed': {   'schedule': <crontab: 5 9 * * * (m/h/d/dM/MY)>,
                              'task': 'tasks.set_usgs_no_data'}}
CELERYD_MAX_TASKS_PER_CHILD: 1
CELERY_IMPORTS: 
    ('data.celery.tasks',)
CELERY_ROUTES: {
    'tasks.set_usgs_gauge_no_data': {   'queue': 'usgs'},
    'tasks.set_usgs_no_data': {   'queue': 'usgs'},
    'tasks.update_ibwc_data': {   'queue': 'light'},
    'tasks.update_lake_cache': {   'queue': 'heavy'},
    'tasks.update_lcra_data': {   'queue': 'light'},
    'tasks.update_storages': {   'queue': 'heavy'},
    'tasks.update_usace_data': {   'queue': 'light'},
    'tasks.update_usace_site': {   'queue': 'light'},
    'tasks.update_usbr_data': {   'queue': 'light'},
    'tasks.update_usgs_data': {   'queue': 'usgs'},
    'tasks.update_usgs_gauge_data': {   'queue': 'usgs'},
    'tasks.update_usgs_provisional': {   'queue': 'usgs'}}
CELERY_TIMEZONE: 'America/Chicago'
BROKER_URL: 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND: 'redis://localhost/0'

Traceback (most recent call last):
  File "/var/www/reservoirs/env/local/lib/python2.7/site-packages/tornado/web.py", line 1415, in _execute
    result = yield result
  File "/var/www/reservoirs/env/local/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/var/www/reservoirs/env/local/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/var/www/reservoirs/env/local/lib/python2.7/site-packages/tornado/gen.py", line 230, in wrapper
    yielded = next(result)
  File "/var/www/reservoirs/env/local/lib/python2.7/site-packages/flower/views/dashboard.py", line 42, in get
    info.update(self._as_dict(worker))
  File "/var/www/reservoirs/env/local/lib/python2.7/site-packages/flower/views/dashboard.py", line 49, in _as_dict
    return dict((k, worker.__getattribute__(k)) for k in worker._fields)
  File "/var/www/reservoirs/env/local/lib/python2.7/site-packages/celery/datastructures.py", line 224, in __getattr__
    "'%s' object has no attribute '%s'" % (type(self).__name__, k))
AttributeError: 'Worker' object has no attribute '_fields'
```

**Comment by ask** [comment]
You're using Celery 3.0.x with a flower version requiring Celery 3.1!
