### ISSUE TITLE
It looks like I have found a bug

### ISSUE THREAD

**Issue by moshebeeri** [mher/flower#462]
It looks like you have found a bug! You can help to improve Celery Flower by opening an issue in https://github.com/mher/flower/issues

flower   -> flower:0.8.3 tornado:4.2.1 babel:2.0
software -> celery:3.1.18 (Cipater) kombu:3.0.26 py:2.7.6
            billiard:3.3.0.20 sqs:N/A
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:sqs results:redis://localhost

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1415, in _execute
    result = yield result
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 230, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python2.7/dist-packages/flower/views/broker.py", line 28, in get
    http_api=http_api, broker_options=broker_options)
  File "/usr/local/lib/python2.7/dist-packages/flower/utils/broker.py", line 164, in __new__
    raise NotImplementedError
NotImplementedError

**Comment by mher** [comment]
SQS broker is not supported
