### ISSUE TITLE
NameError: name 'search' is not defined while accessing '/tasks?limit=100&state=STARTED'

### ISSUE THREAD

**Issue by esdotzed** [mher/flower#468]
flower   -> flower:0.8.0-dev tornado:4.2.1 babel:2.0
software -> celery:3.1.18 (Cipater) kombu:3.0.26 py:3.4.0
            billiard:3.3.0.20 py-amqp:1.4.6
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 1413, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 2721, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/ngwt-0.0.4-py3.4.egg/flower/views/tasks.py", line 74, in get
    started_end=started_end)
  File "/usr/local/lib/python3.4/dist-packages/ngwt-0.0.4-py3.4.egg/flower/views/__init__.py", line 20, in render
    super(BaseHandler, self).render(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 704, in render
    html = self.render_string(template_name, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 811, in render_string
    return t.generate(**namespace)
  File "/usr/local/lib/python3.4/dist-packages/tornado/template.py", line 278, in generate
    return execute()
  File "tasks_html.generated.py", line 139, in _tt_execute
    _tt_tmp = search or ''  # tasks.html:87 (via base.html:49)
NameError: name 'search' is not defined

**Comment by mher** [comment]
Can you try the master version? I'm unable to reproduce this error.

**Comment by esdotzed** [comment]
Looks like it's an environment issue, I re-configured server and the issue is gone. Thanks.
