### ISSUE TITLE
NotImplementedError, Python3.4 and django 1.8.4

### ISSUE THREAD

**Issue by abal09** [mher/flower#469]
NotImplementedError comes up when I go to the Broker tab in celery Flower.

Here is the traceback:
Traceback (most recent call last):
  File "/home/abal/cutter/lib/python3.4/site-packages/tornado/web.py", line 1415, in _execute
    result = yield result
  File "/home/abal/cutter/lib/python3.4/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/home/abal/cutter/lib/python3.4/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/home/abal/cutter/lib/python3.4/site-packages/tornado/gen.py", line 230, in wrapper
    yielded = next(result)
  File "/home/abal/cutter/lib/python3.4/site-packages/flower/views/broker.py", line 28, in get
    http_api=http_api, broker_options=broker_options)
  File "/home/abal/cutter/lib/python3.4/site-packages/flower/utils/broker.py", line 164, in __new__
    raise NotImplementedError
NotImplementedError

**Comment by mozillazg** [comment]
It looks like same as #462

**Comment by mher** [comment]
The master version now prints more meaningful message.
