### ISSUE TITLE
broker.py NotImplementedError

### ISSUE THREAD

**Issue by likaiguo** [mher/flower#473]
flower   -> flower:0.8.3 tornado:4.2.1 babel:2.0
software -> celery:3.1.18 (Cipater) kombu:3.0.26 py:2.7.10
            billiard:3.3.0.20 pymongo:2.7.2
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:mongodb results:disabled

Traceback (most recent call last):
  File "/Users/likaiguo/.virtualenvs/talentminer/lib/python2.7/site-packages/tornado/web.py", line 1415, in _execute
    result = yield result
  File "/Users/likaiguo/.virtualenvs/talentminer/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/Users/likaiguo/.virtualenvs/talentminer/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/Users/likaiguo/.virtualenvs/talentminer/lib/python2.7/site-packages/tornado/gen.py", line 230, in wrapper
    yielded = next(result)
  File "/Users/likaiguo/.virtualenvs/talentminer/lib/python2.7/site-packages/flower/views/broker.py", line 28, in get
    http_api=http_api, broker_options=broker_options)
  File "/Users/likaiguo/.virtualenvs/talentminer/lib/python2.7/site-packages/flower/utils/broker.py", line 164, in __new__
    raise NotImplementedError
NotImplementedError

**Comment by bmbouter** [comment]
I also just received a similar message. I was trying to use flower w/ Qpid as its broker (supported in kombu and Celery). My traceback was very similar.

```
flower   -> flower:0.8.3 tornado:4.3 babel:1.3
software -> celery:3.1.19 (Cipater) kombu:3.0.29 py:2.7.10
            billiard:3.3.0.21 qpid:N/A
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:qpid results:disabled



Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/tornado/web.py", line 1445, in _execute
    result = yield result
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 282, in wrapper
    yielded = next(result)
  File "/usr/lib/python2.7/site-packages/flower/views/broker.py", line 28, in get
    http_api=http_api, broker_options=broker_options)
  File "/usr/lib/python2.7/site-packages/flower/utils/broker.py", line 164, in __new__
    raise NotImplementedError
NotImplementedError
```

@mher I would like to get this working, but I'm not sure where to start. Where do I start?

**Comment by mher** [comment]
@bmbouter You will need to implement a broker class in https://github.com/mher/flower/blob/master/flower/utils/broker.py

**Comment by mher** [comment]
Currently, only RabbitMQ and Redis brokers are supported.
