### ISSUE TITLE
Searching Tasks results in TypeError and exception screen

### ISSUE THREAD

**Issue by melderan** [mher/flower#480]
Exception page results, altered paths/URLs for cleaner reading:

```
flower   -> flower:0.8.3 tornado:4.2.1 babel:2.0
software -> celery:3.1.18 (Cipater) kombu:3.0.26 py:2.7.3
            billiard:3.3.0.20 redis:2.10.1
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://redis.central.local:6379

CELERYBEAT_SCHEDULER: 'daemon.scheduler.TaskScheduler'
CELERY_TASK_RESULT_EXPIRES: 604800
BROKER_TRANSPORT_OPTIONS: {
    'fanout_patterns': True, 'fanout_prefix': True, 'visibility_timeout': 3600}
CELERY_ENABLE_UTC: True

Traceback (most recent call last):
  File "/flower-path/lib/python2.7/site-packages/tornado/web.py", line 1413, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/flower-path/lib/python2.7/site-packages/tornado/web.py", line 2721, in wrapper
    return method(self, *args, **kwargs)
  File "/flower-path/lib/python2.7/site-packages/flower/views/tasks.py", line 88, in get
    search=search
  File "/flower-path/lib/python2.7/site-packages/flower/views/__init__.py", line 20, in render
    super(BaseHandler, self).render(*args, **kwargs)
  File "/flower-path/lib/python2.7/site-packages/tornado/web.py", line 704, in render
    html = self.render_string(template_name, **kwargs)
  File "/flower-path/lib/python2.7/site-packages/tornado/web.py", line 811, in render_string
    return t.generate(**namespace)
  File "/flower-path/lib/python2.7/site-packages/tornado/template.py", line 278, in generate
    return execute()
  File "tasks_html.generated.py", line 225, in _tt_execute
    for uuid, task in tasks:  # tasks.html:151 (via base.html:49)
  File "/flower-path/lib/python2.7/site-packages/flower/utils/tasks.py", line 46, in iter_tasks
    if not satisfies_search_terms(task, any_value_search_term, result_search_term, args_search_terms, kwargs_search_terms):
  File "/flower-path/lib/python2.7/site-packages/flower/utils/search.py", line 32, in satisfies_search_terms
    any_value_search_term and any_value_search_term in '|'.join([task.args, task.kwargs, str(task.result)]),
TypeError: sequence item 0: expected string, NoneType found
```

Base search fields and values:
```
limit: 100
Workers: All
Seen task types: All
Received: blank, blank
Started: blank, blank
```

If I add a Search value and select a State that would return a large match set (All, RECEIVED, SUCCESS, etc.), I can reproduce the error every time.  If I change the Seen task types to anything but All, I do not get the error.  If I remove the Search value, I also don't get there error.

If any other search permutations would be helpful please let me know.  Thank you!

**Comment by mher** [comment]
Please try the master version. It should be fixed now. Thanks!
