### ISSUE TITLE
tornado 4.3 breaks basic auth

### ISSUE THREAD

**Issue by dgouldin** [mher/flower#489]
When tornado released 4.3 today, it broke our flower deployment. Apparently the options have changed, and the option key 'basic_auth' isn't valid anymore. I recommend being more explicit about the version of tornado required by flower.

**Comment by jwm** [comment]
I noticed the same thing with OAuth2. Flower fails to start with:

```
Traceback (most recent call last):
  File "/srv/venv/bin/flower", line 9, in <module>
    load_entry_point('flower==0.9.0', 'console_scripts', 'flower')()
  File "/srv/venv/local/lib/python2.7/site-packages/flower/__main__.py", line 11, in main
    flower.execute_from_commandline()
  File "/srv/venv/local/lib/python2.7/site-packages/celery/bin/base.py", line 311, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/srv/venv/local/lib/python2.7/site-packages/flower/command.py", line 98, in handle_argv
    return self.run_from_argv(prog_name, argv)
  File "/srv/venv/local/lib/python2.7/site-packages/flower/command.py", line 37, in run_from_argv
    option = options._options[name]
KeyError: 'oauth2_secret'
```

It looks like tornado.options.options._options has changed in 4.3.

**Comment by mher** [comment]
Fixed by https://github.com/mher/flower/commit/a587d4623904ec955019dbf9c9bb9b0e26b6a504, thanks!
