### ISSUE TITLE
GET /api/tasks seems broken in 0.9

### ISSUE THREAD

**Issue by BjBlazkowicz** [mher/flower#492]
Something on my end? 

I'm getting internal server errors:

2015-11-20 10:49:22+0000 [-] ERROR: [E 151120 10:49:22 web:1524] Uncaught exception GET /api/tasks?limit=100 (10.0.2.2)
2015-11-20 10:49:22+0000 [-] ERROR:     HTTPServerRequest(protocol='http', host='localhost:8080', method='GET', uri='/api/tasks?limit=100', version='HTTP/1.1', remote_ip='10.0.2.2', headers={'Host': 'localhost:8080'})
2015-11-20 10:49:22+0000 [-] ERROR:     Traceback (most recent call last):
2015-11-20 10:49:22+0000 [-] ERROR:       File "/bin/venv/local/lib/python2.7/site-packages/tornado/web.py", line 1443, in _execute
2015-11-20 10:49:22+0000 [-] ERROR:         result = method(*self.path_args, **self.path_kwargs)
2015-11-20 10:49:22+0000 [-] ERROR:       File "/bin/venv/local/lib/python2.7/site-packages/tornado/web.py", line 2800, in wrapper
2015-11-20 10:49:22+0000 [-] ERROR:         return method(self, *args, **kwargs)
2015-11-20 10:49:22+0000 [-] ERROR:       File "/bin/venv/local/lib/python2.7/site-packages/flower/api/tasks.py", line 447, in get
2015-11-20 10:49:22+0000 [-] ERROR:         worker=worker, state=state):
2015-11-20 10:49:22+0000 [-] ERROR:       File "/bin/venv/local/lib/python2.7/site-packages/flower/utils/tasks.py", line 21, in iter_tasks
2015-11-20 10:49:22+0000 [-] ERROR:         any_value_search_term = search_terms.get('any', None)
2015-11-20 10:49:22+0000 [-] ERROR:     AttributeError: 'NoneType' object has no attribute 'get'

**Comment by Gwill** [comment]
it seems already fixed in master branch

**Comment by mher** [comment]
Fixed in the master version by https://github.com/mher/flower/commit/79ef3fe160322781f567bbf88a3289803d1fe2e7
