### ISSUE TITLE
Explicit refresh causes stack trace

### ISSUE THREAD

**Issue by chimaerase** [mher/flower#495]
Hit the refresh button on the main page, and then got an error page with the stack trace below. Note that I was testing SSL configuration for Celery/RabbitMQ when I saw this problem for the first time, so possible that it's caused by a configuration problem or file permissions error -- though Flower probably still shouldn't respond with a stack trace.

It's also worth noting that my (single) Celery worker shows up on the dashboard, but I get an HTTP 400 when I try to drill down to see the worker.

-------

flower   -> flower:0.8.2 tornado:4.2.1 babel:2.0
software -> celery:3.1.18 (Cipater) kombu:3.0.26 py:2.7.9
            billiard:3.3.0.20 py-amqp:1.4.6
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled

Traceback (most recent call last):
  File "/usr/local/virtualenvs/edd-test.jbei.org/local/lib/python2.7/site-packages/tornado/web.py", line 1415, in _execute
    result = yield result
  File "/usr/local/virtualenvs/edd-test.jbei.org/local/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/local/virtualenvs/edd-test.jbei.org/local/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/virtualenvs/edd-test.jbei.org/local/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/virtualenvs/edd-test.jbei.org/local/lib/python2.7/site-packages/flower/api/workers.py", line 62, in get
    yield self.update_cache(workername=workername)
  File "/usr/local/virtualenvs/edd-test.jbei.org/local/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/local/virtualenvs/edd-test.jbei.org/local/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/virtualenvs/edd-test.jbei.org/local/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/virtualenvs/edd-test.jbei.org/local/lib/python2.7/site-packages/flower/api/control.py", line 23, in update_cache
    app=self.application)
  File "/usr/local/virtualenvs/edd-test.jbei.org/local/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/local/virtualenvs/edd-test.jbei.org/local/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/virtualenvs/edd-test.jbei.org/local/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/virtualenvs/edd-test.jbei.org/local/lib/python2.7/site-packages/flower/api/control.py", line 38, in update_workers
    results = yield futures
  File "/usr/local/virtualenvs/edd-test.jbei.org/local/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/local/virtualenvs/edd-test.jbei.org/local/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/virtualenvs/edd-test.jbei.org/local/lib/python2.7/site-packages/tornado/gen.py", line 656, in callback
    result_list.append(f.result())
  File "/usr/local/virtualenvs/edd-test.jbei.org/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 396, in result
    return self.__get_result()
  File "/usr/local/virtualenvs/edd-test.jbei.org/local/lib/python2.7/site-packages/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/virtualenvs/edd-test.jbei.org/local/lib/python2.7/site-packages/celery/app/control.py", line 90, in stats
    return self._request('stats')
  File "/usr/local/virtualenvs/edd-test.jbei.org/local/lib/python2.7/site-packages/celery/app/control.py", line 71, in _request
    timeout=self.timeout, reply=True,
  File "/usr/local/virtualenvs/edd-test.jbei.org/local/lib/python2.7/site-packages/celery/app/control.py", line 57, in _prepare
    by_node = flatten_reply(reply)
  File "/usr/local/virtualenvs/edd-test.jbei.org/local/lib/python2.7/site-packages/celery/app/control.py", line 32, in flatten_reply
    nodes.update(item)
ValueError: dictionary update sequence element #0 has length 1; 2 is required

**Comment by mher** [comment]
Fixed, thanks!
