### ISSUE TITLE
SQS Not supported By Flower

### ISSUE THREAD

**Issue by sumitjain34** [mher/flower#497]
Traceback (most recent call last):
  File "/home/ubuntu/virtualenvs/parkwheels-api/local/lib/python2.7/site-packages/tornado/web.py", line 1445, in _execute
    result = yield result
  File "/home/ubuntu/virtualenvs/parkwheels-api/local/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/home/ubuntu/virtualenvs/parkwheels-api/local/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/home/ubuntu/virtualenvs/parkwheels-api/local/lib/python2.7/site-packages/tornado/gen.py", line 282, in wrapper
    yielded = next(result)
  File "/home/ubuntu/virtualenvs/parkwheels-api/local/lib/python2.7/site-packages/flower/views/broker.py", line 28, in get
    http_api=http_api, broker_options=broker_options)
  File "/home/ubuntu/virtualenvs/parkwheels-api/local/lib/python2.7/site-packages/flower/utils/broker.py", line 164, in __new__
    raise NotImplementedError
NotImplementedError

**Comment by mher** [comment]
Celery doesn't implement inspect methods which are used by Flower for SQS transport.
