### ISSUE TITLE
Search exception in celery flower interface

### ISSUE THREAD

**Issue by shashank9487** [mher/flower#526]
`flower   -> flower:0.8.3 tornado:4.3 babel:2.1.1
software -> celery:3.1.19 (Cipater) kombu:3.0.32 py:2.7.6
            billiard:3.3.0.22 redis:2.10.5
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:redis results:disabled

Traceback (most recent call last):
  File "/home/user/.virtualenvs/optimation/local/lib/python2.7/site-packages/tornado/web.py", line 1443, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/user/.virtualenvs/optimation/local/lib/python2.7/site-packages/tornado/web.py", line 2800, in wrapper
    return method(self, *args, **kwargs)
  File "/home/user/.virtualenvs/optimation/local/lib/python2.7/site-packages/flower/views/tasks.py", line 88, in get
    search=search
  File "/home/user/.virtualenvs/optimation/local/lib/python2.7/site-packages/flower/views/__init__.py", line 20, in render
    super(BaseHandler, self).render(*args, **kwargs)
  File "/home/user/.virtualenvs/optimation/local/lib/python2.7/site-packages/tornado/web.py", line 699, in render
    html = self.render_string(template_name, **kwargs)
  File "/home/user/.virtualenvs/optimation/local/lib/python2.7/site-packages/tornado/web.py", line 806, in render_string
    return t.generate(**namespace)
  File "/home/user/.virtualenvs/optimation/local/lib/python2.7/site-packages/tornado/template.py", line 345, in generate
    return execute()
  File "tasks_html.generated.py", line 225, in _tt_execute
    for uuid, task in tasks:  # tasks.html:151 (via base.html:49)
  File "/home/user/.virtualenvs/optimation/local/lib/python2.7/site-packages/flower/utils/tasks.py", line 46, in iter_tasks
    if not satisfies_search_terms(task, any_value_search_term, result_search_term, args_search_terms, kwargs_search_terms):
  File "/home/user/.virtualenvs/optimation/local/lib/python2.7/site-packages/flower/utils/search.py", line 32, in satisfies_search_terms
    any_value_search_term and any_value_search_term in '|'.join([task.args, task.kwargs, str(task.result)]),
TypeError: sequence item 0: expected string, NoneType found`

**Comment by mher** [comment]
This bug should be fixed in 0.8.4. Please update to the latest version. Thanks!
