### ISSUE TITLE
Can't open tasks tab

### ISSUE THREAD

**Issue by don-makaron** [mher/flower#527]
When i try to open "tasks" tab, i've got datatables ajax error. When i opened tasks url i see

flower   -> flower:0.9.0-dev tornado:4.2 babel:2.2.0
software -> celery:3.1.20 (Cipater) kombu:3.0.33 py:3.4.4
            billiard:3.3.0.22 redis:2.10.5
platform -> system:Linux arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/tornado/web.py", line 1413, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/local/lib/python3.4/site-packages/tornado/web.py", line 2717, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/flower/views/tasks.py", line 61, in get
    recordsTotal=len(tasks),
TypeError: object of type 'map' has no len()

**Comment by mher** [comment]
Fixed, thanks!
