### ISSUE TITLE
issue when I use search in tasks

### ISSUE THREAD

**Issue by xlight** [mher/flower#556]
flower   -> flower:0.8.4 tornado:4.2 babel:2.2.0
software -> celery:3.1.19 (Cipater) kombu:3.0.33 py:2.7.3
            billiard:3.3.0.22 py-amqp:1.4.9
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 2717, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flower/views/tasks.py", line 93, in get
    search=search
  File "/usr/local/lib/python2.7/dist-packages/flower/views/__init__.py", line 20, in render
    super(BaseHandler, self).render(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 704, in render
    html = self.render_string(template_name, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 811, in render_string
    return t.generate(**namespace)
  File "/usr/local/lib/python2.7/dist-packages/tornado/template.py", line 278, in generate
    return execute()
  File "tasks_html.generated.py", line 226, in _tt_execute
    for uuid, task in tasks:  # tasks.html:151 (via base.html:50)
  File "/usr/local/lib/python2.7/dist-packages/flower/utils/tasks.py", line 48, in iter_tasks
    kwargs_search_terms):
  File "/usr/local/lib/python2.7/dist-packages/flower/utils/search.py", line 35, in satisfies_search_terms
    any_value_search_term and any_value_search_term in '|'.join(filter(None, ([task.args, task.kwargs, str(task.result)]))),
UnicodeEncodeError: 'ascii' codec can't encode characters in position 90-91: ordinal not in range(128)

**Comment by mher** [comment]
Please update to the latest version. This issue is already fixed.

**Comment by xlight** [comment]
flower   -> flower:1.0.0-dev tornado:4.2 babel:2.2.0
software -> celery:3.1.23 (Cipater) kombu:3.0.35 py:2.7.3
            billiard:3.3.0.23 py-amqp:1.4.9
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled



Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 2717, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flower/views/tasks.py", line 45, in get
    reverse=sort_order)
  File "/usr/local/lib/python2.7/dist-packages/flower/utils/tasks.py", line 42, in iter_tasks
    if not satisfies_search_terms(task, search_terms):
  File "/usr/local/lib/python2.7/dist-packages/flower/utils/search.py", line 45, in satisfies_search_terms
    filter(None, [task.name, task.uuid, task.state, task.worker.hostname, task.args, task.kwargs, str(task.result)])),
UnicodeEncodeError: 'ascii' codec can't encode characters in position 50-51: ordinal not in range(128)
