### ISSUE TITLE
Exception on startup

### ISSUE THREAD

**Issue by richburdon** [mher/flower#576]
Running Flower via:

celery --workdir=src/main/python/nx_worker -A worker flower --broker=redis://192.168.99.100:6379:0

I get the following exception (multiple) times, while the console seems to be working in tact.

[E 160512 20:32:52 concurrent:124] Future exception was never retrieved: Traceback (most recent call last):
      File "tools/python/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
        yielded = self.gen.throw(_exc_info)
      File "tools/python/lib/python2.7/site-packages/flower/api/control.py", line 39, in update_workers
        results = yield futures
      File "tools/python/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "tools/python/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "tools/python/lib/python2.7/site-packages/tornado/gen.py", line 656, in callback
        result_list.append(f.result())
      File "tools/python/lib/python2.7/site-packages/concurrent/futures/_base.py", line 398, in result
        return self.__get_result()
      File "tools/python/lib/python2.7/site-packages/concurrent/futures/thread.py", line 55, in run
        result = self.fn(_self.args, *_self.kwargs)
      File "tools/python/lib/python2.7/site-packages/celery/app/control.py", line 81, in active
        return self._request('dump_active', safe=safe)
      File "tools/python/lib/python2.7/site-packages/celery/app/control.py", line 71, in _request
        timeout=self.timeout, reply=True,
      File "tools/python/lib/python2.7/site-packages/celery/app/control.py", line 316, in broadcast
        limit, callback, channel=channel,
      File "tools/python/lib/python2.7/site-packages/kombu/pidbox.py", line 300, in _broadcast
        channel=chan)
      File "tools/python/lib/python2.7/site-packages/kombu/pidbox.py", line 339, in _collect
        self.connection.drain_events(timeout=timeout)
      File "tools/python/lib/python2.7/site-packages/kombu/connection.py", line 275, in drain_events
        return self.transport.drain_events(self.connection, *_kwargs)
      File "tools/python/lib/python2.7/site-packages/kombu/transport/virtual/**init**.py", line 845, in drain_events
        queue, message))
    KeyError: u"Message for queue 'f11aecab-578c-32ff-90af-f435fcaa82cd.reply.celery.pidbox' without consumers: {'body': 'eyJjZWxlcnlAYWxpZW5sYWJzLWJ1cmRvbi1pbWFjLmxvY2FsIjogW119', 'headers': {'ticket': 'a2eeefe6-71f9-40bb-b068-8da60c7ca0db', 'clock': 17}, 'content-type': 'application/json', 'properties': {'body_encoding': 'base64', 'delivery_info': {'priority': 0, 'routing_key': 'f11aecab-578c-32ff-90af-f435fcaa82cd', 'exchange': 'reply.celery.pidbox'}, 'delivery_mode': 1, 'delivery_tag': '9d703156-4973-4093-99f3-78058a972cdf'}, 'content-encoding': 'utf-8'}"

**Comment by mher** [comment]
This bug is already fixed. Which version of flower are you using?

**Comment by Nithya** [comment]
Hi, I am having similar issue. I am using flower version 0.9.1 with celery (3.1.24), kombu (3.0.32), redis(64.2.8.2101) broker in windows.

[E 161123 14:06:39 concurrent:124] Future exception was never retrieved: Traceba
ck (most recent call last):
      File "C:\Python27\Lib\site-packages\tornado\gen.py", line 656, in callback

        result_list.append(f.result())
      File "C:\Python27\Lib\site-packages\concurrent\futures\_base.py", line 398
, in result
        return self.__get_result()
      File "C:\Python27\Lib\site-packages\concurrent\futures\thread.py", line 55
, in run
        result = self.fn(*self.args, **self.kwargs)
      File "C:\Python27\Lib\site-packages\celery\app\control.py", line 81, in ac
tive
        return self._request('dump_active', safe=safe)
      File "C:\Python27\Lib\site-packages\celery\app\control.py", line 71, in _r
equest
        timeout=self.timeout, reply=True,
      File "C:\Python27\Lib\site-packages\celery\app\control.py", line 316, in b
roadcast
        limit, callback, channel=channel,
      File "C:\Python27\kombu\pidbox.py", line 300, in _broadcast
        channel=chan)
      File "C:\Python27\kombu\pidbox.py", line 339, in _collect
        self.connection.drain_events(timeout=timeout)
      File "C:\Python27\kombu\connection.py", line 275, in drain_events
        return self.transport.drain_events(self.connection, **kwargs)
      File "C:\Python27\kombu\transport\virtual\__init__.py", line 845, in drain
_events
        queue, message))
    KeyError: u"Message for queue 'f3355b70-3b1d-392f-80f4-9f072e136f0d.reply.ce
lery.pidbox' without consumers: {u'body': u'eyJjZWxlcnlATml0aHlhLVBDIjogWyJjZWxl
cnlBcHAuY2VsZXJ5X3Rhc2tzLnNlbmRMb2dNYWlsIiwgImRpZ2VzdE1haWxTZW5kaW5nIiwgInNlbmRN
YWlsIiwgInRhc2tFdmVyeTVNaW4iXX0=', u'headers': {u'ticket': u'b1e4904a-311e-4852-
bcd7-b7963b845651', u'clock': 9}, u'content-type': u'application/json', u'proper
ties': {u'body_encoding': u'base64', u'delivery_info': {u'priority': 0, u'routin
g_key': u'f3355b70-3b1d-392f-80f4-9f072e136f0d', u'exchange': u'reply.celery.pid
box'}, u'delivery_mode': 1, u'delivery_tag': u'9b62c859-6c4e-43f2-b182-8aee73b20
e5d'}, u'content-encoding': u'utf-8'}"
[E 161123 14:06:39 concurrent:124] Future exception was never retrieved: Traceba
ck (most recent call last):
      File "C:\Python27\Lib\site-packages\tornado\gen.py", line 876, in run
        yielded = self.gen.throw(*exc_info)
      File "C:\Python27\Lib\site-packages\flower\api\control.py", line 39, in up
date_workers
        results = yield futures
      File "C:\Python27\Lib\site-packages\tornado\gen.py", line 870, in run
        value = future.result()
      File "C:\Python27\Lib\site-packages\tornado\concurrent.py", line 215, in r
esult
        raise_exc_info(self._exc_info)
      File "C:\Python27\Lib\site-packages\tornado\gen.py", line 656, in callback

        result_list.append(f.result())
      File "C:\Python27\Lib\site-packages\concurrent\futures\_base.py", line 398
, in result
        return self.__get_result()
      File "C:\Python27\Lib\site-packages\concurrent\futures\thread.py", line 55
, in run
        result = self.fn(*self.args, **self.kwargs)
      File "C:\Python27\Lib\site-packages\celery\app\control.py", line 81, in ac
tive
        return self._request('dump_active', safe=safe)
      File "C:\Python27\Lib\site-packages\celery\app\control.py", line 71, in _r
equest
        timeout=self.timeout, reply=True,
      File "C:\Python27\Lib\site-packages\celery\app\control.py", line 316, in b
roadcast
        limit, callback, channel=channel,
      File "C:\Python27\kombu\pidbox.py", line 300, in _broadcast
        channel=chan)
      File "C:\Python27\kombu\pidbox.py", line 339, in _collect
        self.connection.drain_events(timeout=timeout)
      File "C:\Python27\kombu\connection.py", line 275, in drain_events
        return self.transport.drain_events(self.connection, **kwargs)
      File "C:\Python27\kombu\transport\virtual\__init__.py", line 845, in drain
_events
        queue, message))
    KeyError: u"Message for queue 'f3355b70-3b1d-392f-80f4-9f072e136f0d.reply.ce
lery.pidbox' without consumers: {u'body': u'eyJjZWxlcnlATml0aHlhLVBDIjogWyJjZWxl
cnlBcHAuY2VsZXJ5X3Rhc2tzLnNlbmRMb2dNYWlsIiwgImRpZ2VzdE1haWxTZW5kaW5nIiwgInNlbmRN
YWlsIiwgInRhc2tFdmVyeTVNaW4iXX0=', u'headers': {u'ticket': u'b1e4904a-311e-4852-
bcd7-b7963b845651', u'clock': 9}, u'content-type': u'application/json', u'proper
ties': {u'body_encoding': u'base64', u'delivery_info': {u'priority': 0, u'routin
g_key': u'f3355b70-3b1d-392f-80f4-9f072e136f0d', u'exchange': u'reply.celery.pid
box'}, u'delivery_mode': 1, u'delivery_tag': u'9b62c859-6c4e-43f2-b182-8aee73b20
e5d'}, u'content-encoding': u'utf-8'}"

Thanks.

**Comment by victorpantoja** [comment]
Hi

Any updates on this issue?

`$ flower --version                 
0.9.2                              
4.1.0 (latentcall)                 
flower   -> flower:0.9.2 tornado:5.0.2 babel:2.5.3
software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:3.6.5
                   billiard:3.5.0.3 py-amqp:2.2.2                            
platform -> system:Linux arch:64bit, ELF imp:CPython                  
loader   -> celery.loaders.app.AppLoader                              
settings -> transport:amqp results:disabled
`

**Comment by mher** [comment]
Try the latest version. This issue should be resolved.
