### ISSUE TITLE
Cannot view task status

### ISSUE THREAD

**Issue by nipunarora** [mher/flower#582]
I get the following error when I try to see the task status:

```
flower   -> flower:0.9.1 tornado:4.2 babel:2.3.4
software -> celery:3.1.23 (Cipater) kombu:3.0.35 py:2.7.6
            billiard:3.3.0.23 py-amqp:1.4.9
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled



Traceback (most recent call last):
  File "/home/parallels/flask/local/lib/python2.7/site-packages/tornado/web.py", line 1413, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/parallels/flask/local/lib/python2.7/site-packages/tornado/web.py", line 2717, in wrapper
    return method(self, *args, **kwargs)
  File "/home/parallels/flask/local/lib/python2.7/site-packages/flower/views/tasks.py", line 52, in get
    tasks = list(map(self.format_task, tasks))
  File "/home/parallels/flask/local/lib/python2.7/site-packages/flower/views/tasks.py", line 76, in format_task
    task = custom_format_task(copy.copy(task))
  File "<string>", line 5, in format_task
NameError: global name 'tasks' is not defined

```

Can anyone suggest a way to resolve this?

**Comment by mher** [comment]
There should be an error in your custom task function

**Comment by nipunarora** [comment]
@mher : what do you mean in the cutstom task function? I haven't modified flower at all? The celery task has no error.

**Comment by mher** [comment]
Don't you use `--format-task` http://flower.readthedocs.io/en/latest/config.html#format-task option? I think the exception happens in the custom format-task function.

**Comment by nipunarora** [comment]
@mher : No I am not using format-task.

**Comment by mher** [comment]
How do you run flower? Do you use flower config file?

**Comment by nipunarora** [comment]
apologies i do have a flower config file with the following 

```
from flower.utils.template import humanize

def format_task(task):
    task.args = humanize(task.args, length=10)
    tasks.nglaID = "NGLA"
    return task
```
What would be a simple way to format the task then?

**Comment by mher** [comment]
There is an error in your `format_task` function on the line `tasks.nglaID = "NGLA"`
