### ISSUE TITLE
Github auth and JSON TypeError on /login?code=...

### ISSUE THREAD

**Issue by mhelmer** [mher/flower#616]
I get the following traceback when setting up github oath2 with Python 3.5

It's on `GET /login?code=<code>`. Looks like it code be a py3 compatibility issue.

I'm on flower `0.9.1`

```
Traceback (most recent call last):
  File "/srv/django/.env/lib/python3.5/site-packages/tornado/web.py", line 1369, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "<string>", line 3, in raise_exc_info
  File "/srv/django/.env/lib/python3.5/site-packages/tornado/web.py", line 1572, in wrapper
    result = method(self, *args, **kwargs)
  File "/srv/django/.env/lib/python3.5/site-packages/flower/views/auth.py", line 106, in _on_access_token
    future.set_result(json.loads(response.body))
  File "/usr/local/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

**Comment by mher** [comment]
Fixed by https://github.com/mher/flower/pull/635
