### ISSUE TITLE
Repeated KeyError raising when using flower

### ISSUE THREAD

**Issue by tipu** [mher/flower#626]
```
flower   -> flower:0.9.1 tornado:4.2 babel:2.3.4
software -> celery:4.0.0rc5 (0today8) kombu:4.0.0 py:2.7.12
            billiard:3.5.0.1 py-amqp:2.1.1
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:db+postgresql://**:**@**/**

JSON_AS_ASCII: True
POSTGRES_HOST: '***'
SESSION_REFRESH_EACH_REQUEST: True
LOG_LEVEL: 'DEBUG'
APPLICATION_ROOT: None
SERVER_NAME: None
PREFERRED_URL_SCHEME: 'http'
TESTING: False
TEMPLATES_AUTO_RELOAD: None
JSONIFY_MIMETYPE: 'application/json'
ENABLE_ACCESS_LOG: False
POSTGRES_PASSWORD: u'********'
TRAP_HTTP_EXCEPTIONS: False
USE_X_SENDFILE: False
SESSION_COOKIE_SECURE: False
SESSION_COOKIE_DOMAIN: None
SESSION_COOKIE_NAME: 'session'
CELERY_BROKER_URL: u'amqp://**:********@**:5672//'
LOGGER_HANDLER_POLICY: 'always'
DEBUG: False
EXPLAIN_TEMPLATE_LOADING: False
POSTGRES_DBNAME: '**'
MAX_CONTENT_LENGTH: None
broker_url: u'amqp://**:********@**:5672//'
POSTGRES_USER: '**'
SQLITE3_DATABASE: u'********'
JSONIFY_PRETTYPRINT_REGULAR: True
POSTGRES_PORT: '5432'
PERMANENT_SESSION_LIFETIME: datetime.timedelta(31)
PROPAGATE_EXCEPTIONS: None
TRAP_BAD_REQUEST_ERRORS: False
JSON_SORT_KEYS: u'********'
SESSION_COOKIE_HTTPONLY: True
SESSION_COOKIE_PATH: None
SEND_FILE_MAX_AGE_DEFAULT: datetime.timedelta(0, 43200)
PRESERVE_CONTEXT_ON_EXCEPTION: None
result_backend: u'db+postgresql://**:********@**/**'

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1413, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 2717, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flower/views/tasks.py", line 61, in get
    task = as_dict(task)
  File "/usr/local/lib/python2.7/site-packages/flower/utils/tasks.py", line 80, in as_dict
    return task.as_dict()
  File "/usr/local/lib/python2.7/site-packages/celery/events/state.py", line 358, in as_dict
    k: handler(k, pass1)(get(self, k)) for k in self._fields
  File "/usr/local/lib/python2.7/site-packages/celery/events/state.py", line 358, in <dictcomp>
    k: handler(k, pass1)(get(self, k)) for k in self._fields
  File "/usr/local/lib/python2.7/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/usr/local/lib/python2.7/site-packages/celery/events/state.py", line 391, in root
    return self.root_id and self.cluster_state.tasks[self.root_id]
  File "/usr/local/lib/python2.7/site-packages/kombu/utils/functional.py", line 65, in __getitem__
    value = self[key] = self.data.pop(key)
  File "/usr/local/lib/python2.7/collections.py", line 160, in pop
    raise KeyError(key)
KeyError: u'7586ee16-4ced-4198-acd5-8c491c2131f7'

```

**Comment by OndrejIT** [comment]
same problem, python 3, celery 4...  rabbitmq or redis.

**Comment by bendemboski** [comment]
same problem, python 2.7, celery 4, rabbitmq, django-cache result backend

**Comment by ocervell** [comment]
Same problem here, can't even start flower anymore, even after clearing out db file.

**Comment by mher** [comment]
Fixed in celery/celery#3950
