### ISSUE TITLE
Worker page report KeyError with celery 4.0.0

### ISSUE THREAD

**Issue by jiangrzh** [mher/flower#641]
When i  update Celery to version 4.0.0, the flower worker page report a error:
=================================================================
Unknown Celery version
Traceback (most recent call last):
  File "/home/workspace/UTSC/lib/python3.5/site-packages/tornado/web.py", line 1415, in _execute
    result = yield result
  File "/home/workspace/UTSC/lib/python3.5/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/home/workspace/UTSC/lib/python3.5/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/home/workspace/UTSC/lib/python3.5/site-packages/tornado/gen.py", line 879, in run
    yielded = self.gen.send(value)
  File "/home/workspace/UTSC/lib/python3.5/site-packages/flower/views/workers.py", line 34, in get
    self.render("worker.html", worker=dict(worker, name=name))
  File "/home/workspace/UTSC/lib/python3.5/site-packages/flower/views/__init__.py", line 21, in render
    super(BaseHandler, self).render(*args, **kwargs)
  File "/home/workspace/UTSC/lib/python3.5/site-packages/tornado/web.py", line 704, in render
    html = self.render_string(template_name, **kwargs)
  File "/home/workspace/UTSC/lib/python3.5/site-packages/tornado/web.py", line 811, in render_string
    return t.generate(**namespace)
  File "/home/workspace/UTSC/lib/python3.5/site-packages/tornado/template.py", line 278, in generate
    return execute()
  File "worker_html.generated.py", line 118, in _tt_execute
    for name,value in worker['stats']['pool'].items():  # worker.html:35 (via base.html:55)
KeyError: 'pool'

**Comment by chavenor** [comment]
@jiangrzh were you able to fix this issue?

**Comment by yinkanghong** [comment]
same error:
` Uncaught exception GET /worker/celery@ykh-PC (192.168.1.108)
    HTTPServerRequest(protocol='http', host='192.168.1.108:5555', method='GET', uri='/worker/celery@ykh-PC', version='HTTP/1.1', r
emote_ip='192.168.1.108', headers={'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,im
age/webp,image/apng,*/*;q=0.8', 'Cookie': 'UM_distinctid=15ea333b2fb4c6-0c84ab6df86b82-5d1b3316-1aeaa0-15ea333b2fc377; CNZZDATA126
3447720=1755911514-1505971628-%7C1505982899; csrftoken=Dqydt88YbRhAlg0J958eESJsEfMkD4Mg4ZcEFqCjIQcz1nEmKWY4IsszBBAv0O46', 'Host':
'192.168.1.108:5555', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.
36 (KHTML, like Gecko) Chrome/61.0.3163.91 Safari/537.36', 'Upgrade-Insecure-Requests': '1', 'Accept-Language': 'zh-CN,zh;q=0.8',
'Referer': 'http://192.168.1.108:5555/', 'Authorization': 'Basic c2Nob29sbXM6c2Nob29sbXM='})
    Traceback (most recent call last):
      File "C:\django\SchoolMS\environment\lib\site-packages\tornado\web.py", line 1511, in _execute
        result = yield result
      File "C:\django\SchoolMS\environment\lib\site-packages\tornado\gen.py", line 1055, in run
        value = future.result()
      File "C:\django\SchoolMS\environment\lib\site-packages\tornado\concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "C:\django\SchoolMS\environment\lib\site-packages\tornado\gen.py", line 1069, in run
        yielded = self.gen.send(value)
      File "C:\django\SchoolMS\environment\lib\site-packages\flower\views\workers.py", line 34, in get
        self.render("worker.html", worker=dict(worker, name=name))
      File "C:\django\SchoolMS\environment\lib\site-packages\flower\views\__init__.py", line 21, in render
        super(BaseHandler, self).render(*args, **kwargs)
      File "C:\django\SchoolMS\environment\lib\site-packages\tornado\web.py", line 724, in render
        html = self.render_string(template_name, **kwargs)
      File "C:\django\SchoolMS\environment\lib\site-packages\tornado\web.py", line 865, in render_string
        return t.generate(**namespace)
      File "C:\django\SchoolMS\environment\lib\site-packages\tornado\template.py", line 348, in generate
        return execute()
      File "worker_html.generated.py", line 118, in _tt_execute
        for name,value in worker['stats']['pool'].items():  # worker.html:46 (via base.html:55)
    KeyError: 'pool'
`
