### ISSUE TITLE
/api/tasks fails on KeyError

### ISSUE THREAD

**Issue by akoren** [mher/flower#648]
When running /api/tasks, at some point i start getting 500, error stack is:

Uncaught exception GET /api/tasks (10.40.30.136)
    HTTPServerRequest(protocol='http', host='dev-sh01-event-mngr-01-aws.cloudyn.com:5555', method='GET', uri='/api/tasks', version='H 'Host': 'dev-sh01-event-mngr-01-aws.cloudyn.com:5555', 'Connection': 'keep-alive', 'Accept': '*/*', 'User-Agent': 'python-requests/2
    Traceback (most recent call last):
      File "/usr/local/lib64/python2.7/site-packages/tornado/web.py", line 1467, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib64/python2.7/site-packages/tornado/web.py", line 2829, in wrapper
        return method(self, *args, **kwargs)
      File "/usr/local/lib/python2.7/site-packages/flower/api/tasks.py", line 335, in get
        task = task.as_dict()
      File "/usr/local/lib/python2.7/site-packages/celery/events/state.py", line 358, in as_dict
        k: handler(k, pass1)(get(self, k)) for k in self._fields
      File "/usr/local/lib/python2.7/site-packages/celery/events/state.py", line 358, in <dictcomp>
        k: handler(k, pass1)(get(self, k)) for k in self._fields
      File "/usr/local/lib/python2.7/site-packages/kombu/utils/objects.py", line 44, in __get__
        value = obj.__dict__[self.__name__] = self.__get(obj)
      File "/usr/local/lib/python2.7/site-packages/celery/events/state.py", line 391, in root
        return self.root_id and self.cluster_state.tasks[self.root_id]
      File "/usr/local/lib/python2.7/site-packages/kombu/utils/functional.py", line 65, in __getitem__
        value = self[key] = self.data.pop(key)
      File "/usr/lib64/python2.7/collections.py", line 143, in pop
        raise KeyError(key)
    KeyError: '9a033dc6-97c1-432e-917c-0e7f7c499612'
[E 161206 15:06:45 web:1971] 500 GET /api/tasks (10.40.30.136) 1.32ms

Problem is resolved after flower restart when all tasks are flushed.

My environment is:

$ celery -A backend report 

software -> celery:4.0.0 (latentcall) kombu:4.0.0 py:2.7.9
            billiard:3.5.0.2 redis:2.10.5
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://:**@***

broker_url: u'redis://:********@***:6379/0'
result_backend: u'redis://:********@***/0'

**Comment by uoxiu** [comment]
I have the same problem after I started flower when many tasks have already been issued
celery==4.0.0

I wait for an update, thank you very much ^^

**Comment by cah-ricksuggs** [comment]
I'm also experiencing the same issue

**Comment by tramora** [comment]
Duplicate of #626

**Comment by jashandeep-sohi** [comment]
any updates on this?

**Comment by tramora** [comment]
@jashandeep-sohi : No news yet on @Photonios side - who has thoroughly studied the issue.
I've submitted a PR to the celery project. You can apply it as a Q&D fix
https://github.com/celery/celery/pull/3950

**Comment by jashandeep-sohi** [comment]
Thanks @tramora, that's what I was looking for 👍

**Comment by mher** [comment]
Fixed in celery/celery#3950
