### ISSUE TITLE
Unknown Celery version

### ISSUE THREAD

**Issue by feliupe** [mher/flower#663]
Hi. I am using celery 4.0.1 and I am having this error when clicking on 'Failed'.

```
Unknown Celery version
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 2717, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flower/views/tasks.py", line 61, in get
    task = as_dict(task)
  File "/usr/local/lib/python2.7/dist-packages/flower/utils/tasks.py", line 80, in as_dict
    return task.as_dict()
  File "/usr/local/lib/python2.7/dist-packages/celery/events/state.py", line 358, in as_dict
    k: handler(k, pass1)(get(self, k)) for k in self._fields
  File "/usr/local/lib/python2.7/dist-packages/celery/events/state.py", line 358, in <dictcomp>
    k: handler(k, pass1)(get(self, k)) for k in self._fields
  File "/usr/local/lib/python2.7/dist-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/usr/local/lib/python2.7/dist-packages/celery/events/state.py", line 391, in root
    return self.root_id and self.cluster_state.tasks[self.root_id]
  File "/usr/local/lib/python2.7/dist-packages/kombu/utils/functional.py", line 65, in __getitem__
    value = self[key] = self.data.pop(key)
  File "/usr/lib/python2.7/collections.py", line 146, in pop
    raise KeyError(key)
KeyError: u'73557162-a57c-4a24-b9b4-383cf46164f2'
```

![image](https://cloud.githubusercontent.com/assets/4684166/22332233/1f357454-e3d0-11e6-802e-b8c234589727.png)

**Comment by tramora** [comment]
@feliupe. There are already a lot of related open issues :
c.f #626, #648 
Please have a look

**Comment by feliupe** [comment]
True @tramora. Should have looked for 'KeyError'
