### ISSUE TITLE
Broker bug - mongodb

### ISSUE THREAD

**Issue by Ahmed-Galal** [mher/flower#672]
flower   -> flower:0.8.3 tornado:4.2.1 babel:1.3
software -> celery:3.1.25 (Cipater) kombu:3.0.37 py:2.7.12
            billiard:3.3.0.23 pymongo:3.4.0
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:mongodb results:mongodb:///

CELERYBEAT_SCHEDULE: {
    'every-min': {   'args': (   'http://notify.appgain.io/574ad3de1ffdbfa835465e39/send',),
                     'schedule': <crontab: */1 * * * * (m/h/d/dM/MY)>,
                     'task': 'task.test_celery'}}
BROKER_URL: 'mongodb://188.166.199.183:1943/cron'
CELERY_RESULT_BACKEND: 'mongodb:///'
CELERY_MONGODB_BACKEND_SETTINGS: {
    'database': '********',
    'host': '188.166.199.183',
    'port': 1943,
    'taskmeta_collection': 'my_tasks'}

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1415, in _execute
    result = yield result
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 230, in wrapper
    yielded = next(result)
  File "/usr/lib/python2.7/dist-packages/flower/views/broker.py", line 28, in get
    http_api=http_api, broker_options=broker_options)
  File "/usr/lib/python2.7/dist-packages/flower/utils/broker.py", line 164, in __new__
    raise NotImplementedError
NotImplementedError

**Comment by mher** [comment]
MongoDB is not supported broker. The latest flower version shows an error message instead of the stack trace.
