### ISSUE TITLE
KeyError (missing Data?) causing DataTables warning

### ISSUE THREAD

**Issue by steve-gregory** [mher/flower#679]
The following error was found on:
```
celery==4.0.2
flower==0.9.1
```

Traceback (most recent call last):
```
  File &quot;/opt/env/.../local/lib/python2.7/site-packages/tornado/web.py&quot;, line 1413, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File &quot;/opt/env/.../local/lib/python2.7/site-packages/tornado/web.py&quot;, line 2717, in wrapper
    return method(self, *args, **kwargs)
  File &quot;/opt/env/.../local/lib/python2.7/site-packages/flower/views/tasks.py&quot;, line 55, in get
    task = as_dict(task)
  File &quot;/opt/env/.../local/lib/python2.7/site-packages/flower/utils/tasks.py&quot;, line 80, in as_dict
    return task.as_dict()
  File &quot;/opt/env/.../local/lib/python2.7/site-packages/celery/events/state.py&quot;, line 358, in as_dict
    k: handler(k, pass1)(get(self, k)) for k in self._fields
  File &quot;/opt/env/.../local/lib/python2.7/site-packages/celery/events/state.py&quot;, line 358, in &lt;dictcomp&gt;
    k: handler(k, pass1)(get(self, k)) for k in self._fields
  File &quot;/opt/env/.../local/lib/python2.7/site-packages/kombu/utils/objects.py&quot;, line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File &quot;/opt/env/.../local/lib/python2.7/site-packages/celery/events/state.py&quot;, line 391, in root
    return self.root_id and self.cluster_state.tasks[self.root_id]
  File &quot;/opt/env/.../local/lib/python2.7/site-packages/kombu/utils/functional.py&quot;, line 65, in __getitem__
    value = self[key] = self.data.pop(key)
  File &quot;/usr/lib/python2.7/collections.py&quot;, line 143, in pop
    raise KeyError(key)
KeyError: &#39;f4aa2685-a22d-4041-93d3-08317a952f83&#39;
```
URL returning 500:
```
https://<SERVER>/flower/tasks/datatable?draw=1&columns%5B0%5D%5Bdata%5D=name&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=true&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=uuid&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=false&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=state&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=true&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=args&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=true&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=kwargs&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=true&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B5%5D%5Bdata%5D=result&columns%5B5%5D%5Bname%5D=&columns%5B5%5D%5Bsearchable%5D=true&columns%5B5%5D%5Borderable%5D=true&columns%5B5%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B5%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B6%5D%5Bdata%5D=received&columns%5B6%5D%5Bname%5D=&columns%5B6%5D%5Bsearchable%5D=true&columns%5B6%5D%5Borderable%5D=true&columns%5B6%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B6%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B7%5D%5Bdata%5D=started&columns%5B7%5D%5Bname%5D=&columns%5B7%5D%5Bsearchable%5D=true&columns%5B7%5D%5Borderable%5D=true&columns%5B7%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B7%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B8%5D%5Bdata%5D=runtime&columns%5B8%5D%5Bname%5D=&columns%5B8%5D%5Bsearchable%5D=true&columns%5B8%5D%5Borderable%5D=true&columns%5B8%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B8%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B9%5D%5Bdata%5D=worker&columns%5B9%5D%5Bname%5D=&columns%5B9%5D%5Bsearchable%5D=true&columns%5B9%5D%5Borderable%5D=true&columns%5B9%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B9%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B10%5D%5Bdata%5D=exchange&columns%5B10%5D%5Bname%5D=&columns%5B10%5D%5Bsearchable%5D=true&columns%5B10%5D%5Borderable%5D=true&columns%5B10%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B10%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B11%5D%5Bdata%5D=routing_key&columns%5B11%5D%5Bname%5D=&columns%5B11%5D%5Bsearchable%5D=true&columns%5B11%5D%5Borderable%5D=true&columns%5B11%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B11%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B12%5D%5Bdata%5D=retries&columns%5B12%5D%5Bname%5D=&columns%5B12%5D%5Bsearchable%5D=true&columns%5B12%5D%5Borderable%5D=true&columns%5B12%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B12%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B13%5D%5Bdata%5D=revoked&columns%5B13%5D%5Bname%5D=&columns%5B13%5D%5Bsearchable%5D=true&columns%5B13%5D%5Borderable%5D=true&columns%5B13%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B13%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B14%5D%5Bdata%5D=exception&columns%5B14%5D%5Bname%5D=&columns%5B14%5D%5Bsearchable%5D=true&columns%5B14%5D%5Borderable%5D=true&columns%5B14%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B14%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B15%5D%5Bdata%5D=expires&columns%5B15%5D%5Bname%5D=&columns%5B15%5D%5Bsearchable%5D=true&columns%5B15%5D%5Borderable%5D=true&columns%5B15%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B15%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B16%5D%5Bdata%5D=eta&columns%5B16%5D%5Bname%5D=&columns%5B16%5D%5Bsearchable%5D=true&columns%5B16%5D%5Borderable%5D=true&columns%5B16%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B16%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=7&order%5B0%5D%5Bdir%5D=asc&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1489708691920
```

**Comment by davidhyman** [comment]
FWIW this seems reproducible for me too, specifically by:
- running some tasks
- confirm visible on flower ui
- stopping the worker
- starting the worker with a different name `-n`
- reload tasks view on flower

**Comment by pssuils** [comment]
Hi, 

We got the same error seeing `https://SERVER/flower/tasks/`. Qe have running flower and celery each of them in a docker container, both seem to be running normally but sometimes flower seems to be unresponsive to load the task list. However, on the dashboard, it lists how many tasks are active, processed, ... etc.
 
The versions running are
> celery==4.0.2
> flower==0.9.1

The stack trace is:
> Unknown Celery version
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1413, in _execute
>     result = method(*self.path_args, **self.path_kwargs)
>   File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 2717, in wrapper
>     return method(self, *args, **kwargs)
>   File "/usr/local/lib/python2.7/site-packages/flower/views/tasks.py", line 61, in get
>     task = as_dict(task)
>   File "/usr/local/lib/python2.7/site-packages/flower/utils/tasks.py", line 80, in as_dict
>     return task.as_dict()
>   File "/usr/local/lib/python2.7/site-packages/celery/events/state.py", line 358, in as_dict
>     k: handler(k, pass1)(get(self, k)) for k in self._fields
>   File "/usr/local/lib/python2.7/site-packages/celery/events/state.py", line 358, in <dictcomp>
>     k: handler(k, pass1)(get(self, k)) for k in self._fields
>   File "/usr/local/lib/python2.7/site-packages/kombu/utils/objects.py", line 44, in __get__
>     value = obj.__dict__[self.__name__] = self.__get(obj)
>   File "/usr/local/lib/python2.7/site-packages/celery/events/state.py", line 391, in root
>     return self.root_id and self.cluster_state.tasks[self.root_id]
>   File "/usr/local/lib/python2.7/site-packages/kombu/utils/functional.py", line 65, in __getitem__
>     value = self[key] = self.data.pop(key)
>   File "/usr/local/lib/python2.7/collections.py", line 160, in pop
>     raise KeyError(key)
> KeyError: u'8cf15c55-2c03-4ac6-9b92-0b63e66a0f17'

Any solutions or checks?

**Comment by lpsinger** [comment]
I'm seeing a similar error with flower 0.9.2.

**Comment by johnarnold** [comment]
+1 i'm getting it too.

**Comment by yothinix** [comment]
+1

**Comment by lpsinger** [comment]
Seems to be fixed in celery 4.1.0 for me.

**Comment by protex** [comment]
I believe the problem occurs if you run a task before flower has time to enable events your workers. The few times that this happened to me, it was because I restarted both my workers and flower at the same time and then quickly ran a task before I got the "Events of group {task} enabled by remote." message.

**Comment by steve-gregory** [comment]
Tested and verified this is no longer a problem on latest of `master` for celery + flower. All clear!
