### ISSUE TITLE
Unknown Celery version

### ISSUE THREAD

**Issue by arheo** [mher/flower#686]
python 3.5.3
flower:  0.9.1
celery: 4.0.2
```
Unknown Celery version
Traceback (most recent call last):
  File "./env3.5.3/lib/python3.5/site-packages/tornado/web.py", line 1415, in _execute
    result = yield result
  File "./env3.5.3/lib/python3.5/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "./env3.5.3/lib/python3.5/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "./env3.5.3/lib/python3.5/site-packages/tornado/gen.py", line 879, in run
    yielded = self.gen.send(value)
  File "./env3.5.3/lib/python3.5/site-packages/flower/views/workers.py", line 34, in get
    self.render("worker.html", worker=dict(worker, name=name))
  File "./env3.5.3/lib/python3.5/site-packages/flower/views/__init__.py", line 21, in render
    super(BaseHandler, self).render(*args, **kwargs)
  File "./env3.5.3/lib/python3.5/site-packages/tornado/web.py", line 704, in render
    html = self.render_string(template_name, **kwargs)
  File "./env3.5.3/lib/python3.5/site-packages/tornado/web.py", line 811, in render_string
    return t.generate(**namespace)
  File "./env3.5.3/lib/python3.5/site-packages/tornado/template.py", line 278, in generate
    return execute()
  File "worker_html.generated.py", line 264, in _tt_execute
    _tt_tmp = task['name']  # worker.html:202 (via base.html:55)
TypeError: string indices must be integers
```

**Comment by mher** [comment]
What is the output of `celery inspect active`?

**Comment by mher** [comment]
Duplicate of https://github.com/mher/flower/issues/667

**Comment by arheo** [comment]
@mher ok

**Comment by mher** [comment]
Please try to run `celery inspect active`

**Comment by Dean-Christian-Armada** [comment]
@mher , This error will occur if the celery version version installed is 4.02. In celery 3.1.24, the issue will not occur
