### ISSUE TITLE
KeyError at /login when providing no info about authentication 

### ISSUE THREAD

**Issue by kregoslup** [mher/flower#690]
Hello,
I have started flower through celery like that:
```
celery flower -A project --port=5555
```
without providing any information about authentication and then I opened localhost:5555/login and KeyError occured: 

```
Unknown Celery version
Traceback (most recent call last):
  File ".virtualenvs/lib/python3.4/site-packages/tornado/web.py", line 1369, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "<string>", line 3, in raise_exc_info
  File ".virtualenvs/lib/python3.4/site-packages/tornado/web.py", line 1572, in wrapper
    result = method(self, *args, **kwargs)
  File ".virtualenvs/lib/python3.4/site-packages/flower/views/auth.py", line 27, in get
    redirect_uri = self.settings[self._OAUTH_SETTINGS_KEY]['redirect_uri']
KeyError: 'oauth'
```
Whole stacktrace was rendered even though DEBUG is set to False.
```
flower==0.9.1
```
```
DEBUG = False
```

**Comment by sandipagarwal** [comment]
You need to provide the `auth` param even if you just give `*` as the value.http://flower.readthedocs.io/en/latest/config.html#auth
