### ISSUE TITLE
Unable to Install Flower

### ISSUE THREAD

**Issue by joshuamcginnis** [mher/flower#694]
I'm running into an issue installing Flower one of our CI boxes using`pip install flower`

The error appears to be with installing:

> ValueError: '/tmp/pip-build-CLsYUt/backports.ssl-match-hostname' is not in list
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-CLsYUt/backports.ssl-match-hostname/

Here's the complete log:
```
> pip install flower
Collecting flower
  Downloading flower-0.9.1.tar.gz (3.9MB)
    28% |█████████▏                      | 1.1MB 43.4MB/s eta 0:00:01    28% |█████████▏                      | 1.1MB 42.3MB/s eta 0:00:01    29% |█████████▎                      | 1.1MB 44.3MB/s eta 0:00:01    29% |█████████▍                      | 1.1MB 43.9MB/s eta 0:00:01    29% |█████████▌                      | 1.1MB 43.3MB/s eta 0:00:01    99% |████████████████████████████████| 3.9MB 49.3MB/s eta 0:00:01    100% |████████████████████████████████| 3.9MB 376kB/s 
Requirement already satisfied: celery>=3.1.0 in /home/ubuntu/virtualenvs/venv-system/lib/python2.7/site-packages (from flower)
Collecting tornado==4.2.0 (from flower)
  Downloading tornado-4.2.tar.gz (433kB)
    99% |███████████████████████████████▊| 430kB 46.1MB/s eta 0:00:01    100% |████████████████████████████████| 440kB 3.3MB/s 
Collecting babel>=1.0 (from flower)
  Downloading Babel-2.4.0-py2.py3-none-any.whl (6.8MB)
    5% |█▊                              | 358kB 43.2MB/s eta 0:00:01    5% |█▊                              | 368kB 43.6MB/s eta 0:00:01    5% |█▉                              | 378kB 42.6MB/s eta 0:00:01    5% |█▉                              | 389kB 43.5MB/s eta 0:00:01    5% |█▉                              | 399kB 43.6MB/s eta 0:00:01    6% |██                              | 409kB 42.9MB/s eta 0:00:01    74% |████████████████████████        | 5.1MB 45.1MB/s eta 0:00:01    75% |████████████████████████        | 5.1MB 47.2MB/s eta 0:00:01    75% |████████████████████████        | 5.1MB 46.6MB/s eta 0:00:01    75% |████████████████████████▏       | 5.1MB 46.6MB/s eta 0:00:01    75% |████████████████████████▏       | 5.1MB 46.6MB/s eta 0:00:01    99% |████████████████████████████████| 6.8MB 50.0MB/s eta 0:00:01    100% |████████████████████████████████| 6.8MB 208kB/s 
Requirement already satisfied: pytz in /home/ubuntu/virtualenvs/venv-system/lib/python2.7/site-packages (from flower)
Requirement already satisfied: futures in /home/ubuntu/virtualenvs/venv-system/lib/python2.7/site-packages (from flower)
Requirement already satisfied: billiard<3.6.0,>=3.5.0.2 in /home/ubuntu/virtualenvs/venv-system/lib/python2.7/site-packages (from celery>=3.1.0->flower)
Requirement already satisfied: kombu<5.0,>=4.0.2 in /home/ubuntu/virtualenvs/venv-system/lib/python2.7/site-packages (from celery>=3.1.0->flower)
Collecting backports.ssl_match_hostname (from tornado==4.2.0->flower)
  Downloading backports.ssl_match_hostname-3.5.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/ubuntu/virtualenvs/venv-system/lib/python2.7/site-packages/setuptools/__init__.py", line 11, in <module>
        from setuptools.extern.six.moves import filterfalse, map
      File "/home/ubuntu/virtualenvs/venv-system/lib/python2.7/site-packages/setuptools/extern/__init__.py", line 1, in <module>
        from pkg_resources.extern import VendorImporter
      File "/home/ubuntu/virtualenvs/venv-system/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3131, in <module>
        @_call_aside
      File "/home/ubuntu/virtualenvs/venv-system/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3117, in _call_aside
        f(*args, **kwargs)
      File "/home/ubuntu/virtualenvs/venv-system/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3156, in _initialize_master_working_set
        add_activation_listener(lambda dist: dist.activate())
      File "/home/ubuntu/virtualenvs/venv-system/lib/python2.7/site-packages/pkg_resources/__init__.py", line 954, in subscribe
        callback(dist)
      File "/home/ubuntu/virtualenvs/venv-system/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3156, in <lambda>
        add_activation_listener(lambda dist: dist.activate())
      File "/home/ubuntu/virtualenvs/venv-system/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2656, in activate
        declare_namespace(pkg)
      File "/home/ubuntu/virtualenvs/venv-system/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2226, in declare_namespace
        _handle_ns(packageName, path_item)
      File "/home/ubuntu/virtualenvs/venv-system/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2195, in _handle_ns
        path.sort(key=sort_key)
      File "/home/ubuntu/virtualenvs/venv-system/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2193, in sort_key
        return sys_path.index(_normalize_cached(os.sep.join(parts)))
    ValueError: '/tmp/pip-build-CLsYUt/backports.ssl-match-hostname' is not in list
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-CLsYUt/backports.ssl-match-hostname/

pip install flower returned exit code 1

Action failed: pip install flower
```

Are there any ideas on how I can further troubleshoot this?

**Comment by joshuamcginnis** [comment]
I've found the issue. Flower is requiring `tornado==4.2.0` which requires `backports.ssl-match-hostname` which depends on Python 3+. 

Installing the latest tornado (4.5.1) seems to work fine. Can we update this @mher? I'm happy to submit a PR if that would help.

**Comment by tablet-mode** [comment]
I've run into the same issue, a quick resolution would be much appreciated :-)

**Comment by mher** [comment]
@joshuamcginnis this issue is fixed in the master version

**Comment by joshuamcginnis** [comment]
@mher Where? Not seeing any recent commits on master. Did you push the change to pypy?

**Comment by mher** [comment]
https://github.com/mher/flower/commit/ee07f024f3d3171fdee856f8578f25619cef1cc5

**Comment by joshuamcginnis** [comment]
I see, from 2 months ago. When do you plan to push this out in a release? I don't think I'd feel comfortable using master branch for a production app.

**Comment by mher** [comment]
Flower 0.9.2 has been released!

**Comment by joshuamcginnis** [comment]
Thanks! This release resolved my original issue.
