### ISSUE TITLE
Error instead of 403 response with OAuth2

### ISSUE THREAD

**Issue by vstoykov** [mher/flower#695]
I've tried to configure flower to use Google's OAuth2 and it seems to work perfect.

The problem is when I wanted to test what will happen when unallowed email tries to login. Then instead of 403 page or something like that the response never return. The connection was open for a very ling time and nothing. Then I looked at the terminal and sow this traceback:
```
[E 170519 12:40:53 concurrent:303] Exception in callback <functools.partial object at 0x7fdb602b4e10> for <tornado.concurrent.Future object at 0x7fdb5559f8d0>
    Traceback (most recent call last):
      File "/path/to/venv/lib/python2.7/site-packages/tornado/concurrent.py", line 300, in _set_done
        cb(self)
      File "/path/to/venv/lib/python2.7/site-packages/tornado/auth.py", line 113, in _auth_future_to_callback
        callback(result)
      File "/path/to/venv/lib/python2.7/site-packages/flower/views/auth.py", line 61, in _on_auth
        raise tornado.web.HTTPError(403, message)
    HTTPError: HTTP 403: Forbidden (Access denied to 'email@example.com'. Please use another account or ask your admin to add your email to flower --auth.)
```

**Comment by jar349** [comment]
here's what I se:
```
2018-04-12T19:03:28.098734+00:00 app[web.1]:       File "/app/.heroku/python/lib/python3.6/site-packages/flower/views/auth.py", line 53, in _on_auth
2018-04-12T19:03:28.098736+00:00 app[web.1]:         raise tornado.web.HTTPError(403, 'Google auth failed: %s' % e)
2018-04-12T19:03:28.098744+00:00 app[web.1]:     tornado.web.HTTPError: HTTP 403: Forbidden (Google auth failed: HTTP 403: Forbidden)
```

**Comment by Praseetha-KR** [comment]
I'm also having the same issue with the docker image `mher/flower:latest`

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flower/views/auth.py", line 49, in _on_auth
    response = httpclient.HTTPClient().fetch(
  File "/usr/local/lib/python3.6/site-packages/tornado/httpclient.py", line 94, in __init__
    gen.coroutine(lambda: async_client_class(**kwargs)))
  File "/usr/local/lib/python3.6/site-packages/tornado/ioloop.py", line 576, in run_sync
    self.start()
  File "/usr/local/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 127, in start
    self.asyncio_loop.run_forever()
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 412, in run_forever
    'Cannot run the event loop while another loop is running')
RuntimeError: Cannot run the event loop while another loop is running

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/site-packages/tornado/auth.py", line 107, in _auth_future_to_callback
    callback(result)
  File "/usr/local/lib/python3.6/site-packages/flower/views/auth.py", line 53, in _on_auth
    raise tornado.web.HTTPError(403, 'Google auth failed: %s' % e)
tornado.web.HTTPError: HTTP 403: Forbidden (Google auth failed: Cannot run the event loop while another loop is running)
```

@mher Is it possible to create a new release & docker tag containing https://github.com/mher/flower/pull/793 which restricts `tornado` to `<5.0.0`

(The `latest` still contains release `0.9.2` which was added on 19 Jun 2017)

**Comment by timesking** [comment]
I met the same problem, which is not fun

**Comment by timesking** [comment]
> I met the same problem, which is not fun
in my case
tornado==5.1.1
flower==0.9.3
works well

**Comment by mher** [comment]
Unfortunately, I don't have time to improve the auth handlers. Feel free to open a pull request.
