### ISSUE TITLE
GitHub auth throws JSON error

### ISSUE THREAD

**Issue by bjudson** [mher/flower#707]
This was previously working with the same configuration, and broke recently. We upgraded from Python 2.7 to 3.4 around the same time. Here is our setup:
```
flower   -> flower:0.9.1 tornado:4.2 babel:2.4.0
software -> celery:3.1.23 (Cipater) kombu:3.0.37 py:3.4.3
            billiard:3.3.0.23 redis:2.10.5
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
```

Environment vars:
```
DJANGO_SETTINGS_MODULE          settings.production
ENVIRONMENT                     production
FLOWER_OAUTH2_KEY               ********************
FLOWER_OAUTH2_REDIRECT_URI      https://www.***********.com/flower/login
FLOWER_OAUTH2_SECRET            ****************************************
```

Command:
```
flower -A app_name --url_prefix=flower --auth_provider=flower.views.auth.GithubLoginHandler --auth=.*@.*\\.com"]
```

Stack trace:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 1369, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 1572, in wrapper
    result = method(self, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/flower/views/auth.py", line 106, in _on_access_token
    future.set_result(json.loads(response.body))
  File "/usr/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

**Comment by bjudson** [comment]
Sorry, just realized this has been fixed, but there haven't been any releases since then. Guess we'll have to install from GitHub instead of PyPI. 

https://github.com/mher/flower/commit/28ff9aee1f8d3feec772295b833f15b989281f6b
