### ISSUE TITLE
EOFError on loading persisted tasks in flower

### ISSUE THREAD

**Issue by syre** [mher/flower#758]
I'm getting the below error occasionally with running: `flower -A celery_publish --port=5555 --url_prefix=flower --persistent=True --db=/srv/publish/prod/flower --max_tasks=100000`

```Traceback (most recent call last):
  File "/srv/publish/qa/env/bin/flower", line 11, in <module>
    sys.exit(main())
  File "/srv/publish/qa/env/local/lib/python2.7/site-packages/flower/__main__.py", line 11, in main
    flower.execute_from_commandline()
  File "/srv/publish/qa/env/local/lib/python2.7/site-packages/celery/bin/base.py", line 281, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/srv/publish/qa/env/local/lib/python2.7/site-packages/flower/command.py", line 59, in handle_argv
    return self.run_from_argv(prog_name, argv)
  File "/srv/publish/qa/env/local/lib/python2.7/site-packages/flower/command.py", line 43, in run_from_argv
    flower = Flower(capp=self.app, options=options, **settings)
  File "/srv/publish/qa/env/local/lib/python2.7/site-packages/flower/app.py", line 42, in __init__
    max_tasks_in_memory=self.options.max_tasks)
  File "/srv/publish/qa/env/local/lib/python2.7/site-packages/flower/events.py", line 79, in __init__
    self.state = state['events']
  File "/usr/lib/python2.7/shelve.py", line 122, in __getitem__
    value = Unpickler(f).load()
EOFError
```
It seems it is trying to load the persisted file but it fails to, or it failed to save it when restarting?

Environment is:
Python: 2.7.9
Celery: 4.1.0
Flower: 0.9.2
Ubuntu 16.04
I'm running flower using supervisor, is there any requirements for running flower this way?

**Comment by sshishov** [comment]
It seems that your `shelve` file is corrupted or something overrode it. Just to make sure, rename it to `--db=/srv/publish/prod/flower.db`.
Also it may happen that the file is not fully dumped on SIGINT, SIGTERM or other exit events.
