### ISSUE TITLE
Flower consuming 100% of cpu due to address in use

### ISSUE THREAD

**Issue by chrisspen** [mher/flower#764]
I have multiple instances of flower running in a multi-tenant environment. I have one instance of flower 0.9.2 monitoring each client site. I'm noticing that, even when no celery tasks are running, flower consumes 100% of cpu. Looking in the logs, I see this error:

    Traceback (most recent call last):
      File "/usr/local/myproject/.env/bin/celery", line 11, in <module>
        sys.exit(main())
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/celery/__main__.py", line 14, in main
        _main()
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/celery/bin/celery.py", line 326, in main
        cmd.execute_from_commandline(argv)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
        super(CeleryCommand, self).execute_from_commandline(argv)))
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/celery/bin/base.py", line 281, in execute_from_commandline
        return self.handle_argv(self.prog_name, argv[1:])
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/celery/bin/celery.py", line 480, in handle_argv
        return self.execute(command, argv)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/celery/bin/celery.py", line 412, in execute
        ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/flower/command.py", line 54, in run_from_argv
        flower.start()
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/flower/app.py", line 52, in start
        xheaders=self.options.xheaders)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/tornado/web.py", line 1943, in listen
        server.listen(port, address)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/tornado/tcpserver.py", line 142, in listen
        sockets = bind_sockets(port, address=address)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/tornado/netutil.py", line 197, in bind_sockets
        sock.bind(sockaddr)
      File "/usr/lib/python2.7/socket.py", line 228, in meth
        return getattr(self._sock,name)(*args)
    socket.error: [Errno 98] Address already in use

So it seems the high cpu is because flower is stuck in a loop trying to initialize, but something's using the port it's trying to bind to. However, I don't see how this is, because I use the `--port` option to give all my flower instances a unique port.

I'm using supervisor to manage the flower daemons, and my supervisor conf file looks like:

    [program:flower_gce]
    environment=ROLE=staging,SITE=gce
    command=/usr/local/myproject/.env/bin/celery flower -A myproject worker --address=0.0.0.0 --port=5556 --url_prefix=flower
    directory=/usr/local/myproject/src
    autostart=true
    autorestart=true
    startretries=3
    user=ubuntu
    stdout_logfile=/var/log/flower-gce.log
    stderr_logfile=/var/log/flower-gce.log

I have one such conf file for each flower instance, and I've double-checked and ensured each has a unique port number. Why is flower complaining about someone else using its port?

I even checked to see if it was from an old flower instance by stopping all supervisor daemons, and then killed all processes named "python" or "flower", but restarting flower via supervisor still results in the same error.

**Comment by chrisspen** [comment]
Nevermind, the problem was my fault. In the script I used to generate the supervisor conf files, I omitted an explicit port on some configurations, causing them to inherent the ports from the previous configuration, resulting in two flower instances using the same port.
