### ISSUE TITLE
Querying worker details seems to kill them

### ISSUE THREAD

**Issue by ownaginatious** [mher/flower#776]
So we currently have 4 separate worker machines in Celery using a Redis backend. We can view stats okay in Flower, but we have an interesting issue where clicking on a worker seems to kill it (not a huge deal since `supervisord` will bring it back up).

We're using Python 2.7.6, `celery` 4.1.0, and `flower` 0.9.2.

Here is a trace of the specific issue that seems to kill them, as reported in the logs. It's not always the same. We've noticed this happens when starting Celery too:

```
[2018-01-27 10:41:07,320: ERROR/MainProcess] Control command error: EncodeError(UnicodeDecodeError('utf8', '\xd4\xc7\xe8\x14R* \xaad\xda\xa0i\xd2\xb6\x15f\xed\x07`\xfe\xbc`\x9f\xe3`\x01y\xb5\t\xdbzG', 0, 1, 'invalid continuation byte'),)
Traceback (most recent call last):
  File "/srv/mp_apps/mp_web/virtualenv/local/lib/python2.7/site-packages/celery/worker/pidbox.py", line 42, in on_message
    self.node.handle_message(body, message)
  File "/srv/mp_apps/mp_web/virtualenv/local/lib/python2.7/site-packages/kombu/pidbox.py", line 129, in handle_message
    return self.dispatch(**body)
  File "/srv/mp_apps/mp_web/virtualenv/local/lib/python2.7/site-packages/kombu/pidbox.py", line 112, in dispatch
    ticket=ticket)
  File "/srv/mp_apps/mp_web/virtualenv/local/lib/python2.7/site-packages/kombu/pidbox.py", line 135, in reply
    serializer=self.mailbox.serializer)
  File "/srv/mp_apps/mp_web/virtualenv/local/lib/python2.7/site-packages/kombu/pidbox.py", line 265, in _publish_reply
    **opts
  File "/srv/mp_apps/mp_web/virtualenv/local/lib/python2.7/site-packages/kombu/messaging.py", line 169, in publish
    compression, headers)
  File "/srv/mp_apps/mp_web/virtualenv/local/lib/python2.7/site-packages/kombu/messaging.py", line 252, in _prepare
    body) = dumps(body, serializer=serializer)
  File "/srv/mp_apps/mp_web/virtualenv/local/lib/python2.7/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/srv/mp_apps/mp_web/virtualenv/local/lib/python2.7/site-packages/kombu/serialization.py", line 54, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/srv/mp_apps/mp_web/virtualenv/local/lib/python2.7/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/srv/mp_apps/mp_web/virtualenv/local/lib/python2.7/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/srv/mp_apps/mp_web/virtualenv/local/lib/python2.7/site-packages/kombu/utils/json.py", line 72, in dumps
    **dict(default_kwargs, **kwargs))
  File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
EncodeError: 'utf8' codec can't decode byte 0xd4 in position 0: invalid continuation byte
```
Doing a `GET` to this works, but kills _all_ the workers in the process: `https://.../flower/api/workers?refresh=True`

Anyone know what's up here or how we could fix it? I thought maybe `flower` were using incompatible serialization methods, but there doesn't seem to be any configuration for that.

Any help would be greatly appreciated. Thanks!

**Comment by ownaginatious** [comment]
Ah, figured it out. Turns out we had some data that was base64 decoded within our settings file and hence not JSON-serializable. False alarm! :)
