### ISSUE TITLE
Container built from Dockerfile fails on startup

### ISSUE THREAD

**Issue by davschne** [mher/flower#785]
When attempting to run Flower in a Docker container using the provided Dockerfile, the container fails on startup. I get the following stack trace:
```
Traceback (most recent call last):
  File "/usr/local/bin/flower", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/flower/__main__.py", line 11, in main
    flower.execute_from_commandline()
  File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 281, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/local/lib/python3.6/site-packages/flower/command.py", line 59, in handle_argv
    return self.run_from_argv(prog_name, argv)
  File "/usr/local/lib/python3.6/site-packages/flower/command.py", line 43, in run_from_argv
    flower = Flower(capp=self.app, options=options, **settings)
  File "/usr/local/lib/python3.6/site-packages/flower/app.py", line 42, in __init__
    max_tasks_in_memory=self.options.max_tasks)
  File "/usr/local/lib/python3.6/site-packages/flower/events.py", line 77, in __init__
    state = shelve.open(self.db)
  File "/usr/local/lib/python3.6/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/usr/local/lib/python3.6/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/usr/local/lib/python3.6/dbm/__init__.py", line 94, in open
    return mod.open(file, flag, mode)
_gdbm.error: [Errno 13] Permission denied
```
I figured this was because the `flower` process was running with restricted access privileges. When I remove the following line in the Dockerfile, it works without any issues:
```dockerfile
USER nobody
```

**Comment by fropert** [comment]
The same error is returned with the **--persistent=True**

**Comment by sunnyar** [comment]
@fropert : Is there a solution for this error with the persistent=True flag ?

**Comment by pendolf** [comment]
@fropert solution is update https://github.com/mher/flower/blob/master/Dockerfile#L18 and stop using `nobody` user, because it does not have system permissions to create files, such a `flower.db`.

**Comment by mher** [comment]
Fixed by https://github.com/mher/flower/commit/d0aa4e53236bc4a796ebfb96edabb61e5d72adec#diff-3254677a7917c6c01f55212f86c57fbf

**Comment by alihazemfarouk** [comment]
I am still getting the same issue with the latest version

**Comment by RodrigoBCC** [comment]
I am still getting the same issue with the latest version

**Comment by alexdev27** [comment]
still getting that error in latest version
