### ISSUE TITLE
 invalid literal for int() with base 10: '0rc1'

### ISSUE THREAD

**Issue by koby-meir** [mher/flower#791]
Hi, 
After a recent update to celery main branch: https://github.com/celery/celery/commit/c7f2a8b6111692696f69c682dd2c57010bae5b6a

This causes the following error:
```
File "/usr/local/lib/python3.6/site-packages/flower/events.py", line 70, in __init__
    if self.persistent and tuple(map(int, celery.__version__.split('.'))) < (3, 0, 15):
ValueError: invalid literal for int() with base 10: '0rc1'
```
This is the problematic line:https://github.com/mher/flower/blob/master/flower/events.py#L70

Which causes flower to crash completely.
maybe this can help for better parsing the version number:
https://stackoverflow.com/questions/11887762/how-do-i-compare-version-numbers-in-python/11887885#11887885

**Comment by nodesocket** [comment]
Running docker container and it is crashing with:

```
flower   -> flower:0.9.2 tornado:5.1.1 babel:2.6.0
software -> celery:4.2.1 (windowlicker) kombu:4.2.2-post1 py:3.7.2
            billiard:3.5.0.5 py-amqp:2.3.2
platform -> system:Linux arch:64bit imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:amqp://userhere:**@rabbitmq.default.svc.cluster.local:5672/



Traceback (most recent call last):
  File "/usr/local/bin/flower", line 11, in <module>
    load_entry_point('flower==0.9.2', 'console_scripts', 'flower')()
  File "/usr/local/lib/python3.7/site-packages/flower/__main__.py", line 11, in main
    flower.execute_from_commandline()
  File "/usr/local/lib/python3.7/site-packages/celery/bin/base.py", line 275, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/local/lib/python3.7/site-packages/flower/command.py", line 59, in handle_argv
    return self.run_from_argv(prog_name, argv)
  File "/usr/local/lib/python3.7/site-packages/flower/command.py", line 36, in run_from_argv
    self.apply_env_options()
  File "/usr/local/lib/python3.7/site-packages/flower/command.py", line 74, in apply_env_options
    value = option.type(value)
ValueError: invalid literal for int() with base 10: 'tcp://172.20.76.251:5555'
```

**Comment by krdian** [comment]
I've got the same error.
