### ISSUE TITLE
DataTables warning: table id=tasks-table - Ajax error.

### ISSUE THREAD

**Issue by leench** [mher/flower#802]
```
[E 180424 15:37:29 web:1590] Uncaught exception POST /tasks/datatable (192.168.2.253)
    HTTPServerRequest(protocol='http', host='192.168.1.80:5555', method='POST', uri='/tasks/datatable', version='HTTP/1.1', remote_ip='192.168.2.253', headers={'Origin': 'http://192.168.1.80:5555', 'Content-Length': '3775', 'Accept-Language':'zh-CN,zh;q=0.9,en;q=0.8,ja;q=0.7,zh-TW;q=0.6', 'Accept-Encoding': 'gzip, deflate', 'Host': '192.168.1.80:5555', 'Accept': 'application/json, text/javascript, */*; q=0.01', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Referer': 'http://192.168.1.80:5555/tasks', 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8', 'Authorization': 'Basic bGVlbjokODAwMjE1cWxvbmc='})
    Traceback (most recent call last):
      File "/wwwapps/movement/env/local/lib/python2.7/site-packages/tornado/web.py", line 1509, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/wwwapps/movement/env/local/lib/python2.7/site-packages/tornado/web.py", line 2897, in wrapper
        return method(self, *args, **kwargs)
      File "/wwwapps/movement/env/local/lib/python2.7/site-packages/flower/views/tasks.py", line 88, in post
        return self.get()
      File "/wwwapps/movement/env/local/lib/python2.7/site-packages/tornado/web.py", line 2897, in wrapper
        return method(self, *args, **kwargs)
      File "/wwwapps/movement/env/local/lib/python2.7/site-packages/flower/views/tasks.py", line 70, in get
        reverse=sort_order
      File "/wwwapps/movement/env/local/lib/python2.7/site-packages/flower/utils/tasks.py", line 42, in iter_tasks
        if not satisfies_search_terms(task, search_terms):
      File "/wwwapps/movement/env/local/lib/python2.7/site-packages/flower/utils/search.py", line 49, in satisfies_search_terms
        task.args, task.kwargs, safe_str(task.result)])),
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 7: ordinal not in range(128)
```

When I type some char in search input.

**Comment by leench** [comment]
```
    HTTPServerRequest(protocol='http', host='10.10.10.80:5555', method='GET', uri='/tasks/datatable?draw=1&columns%5B0%5D%5Bdata%5D=name&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%
5D%5Borderable%5D=true&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=uuid&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5
D%5Borderable%5D=false&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=state&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%
5D%5Borderable%5D=true&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=args&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5
D%5Borderable%5D=true&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=kwargs&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%
5D%5Borderable%5D=true&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B5%5D%5Bdata%5D=result&columns%5B5%5D%5Bname%5D=&columns%5B5%5D%5Bsearchable%5D=true&columns%5B5
%5D%5Borderable%5D=true&columns%5B5%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B5%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B6%5D%5Bdata%5D=received&columns%5B6%5D%5Bname%5D=&columns%5B6%5D%5Bsearchable%5D=true&columns%
5B6%5D%5Borderable%5D=true&columns%5B6%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B6%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B7%5D%5Bdata%5D=started&columns%5B7%5D%5Bname%5D=&columns%5B7%5D%5Bsearchable%5D=true&column
s%5B7%5D%5Borderable%5D=true&columns%5B7%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B7%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B8%5D%5Bdata%5D=runtime&columns%5B8%5D%5Bname%5D=&columns%5B8%5D%5Bsearchable%5D=true&columns%5B8%5D%5Borderable%5D=true&columns%5B8%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B8%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B9%5D%5Bdata%5D=worker&columns%5B9%5D%5Bname%5D=&columns%5B9%5D%5Bsearchable%5D=true&co$umns%5B9%5D%5Borderable%5D=true&columns%5B9%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B9%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B10%5D%5Bdata%5D=exchange&columns%5B10%5D%5Bname%5D=&columns%5B10%5D%5Bsearchable%5D=t$ue&columns%5B10%5D%5Borderable%5D=true&columns%5B10%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B10%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B11%5D%5Bdata%5D=routing_key&columns%5B11%5D%5Bname%5D=&columns%5B11%5D%5Bsea$chable%5D=true&columns%5B11%5D%5Borderable%5D=true&columns%5B11%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B11%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B12%5D%5Bdata%5D=retries&columns%5B12%5D%5Bname%5D=&columns%5B12%$D%5Bsearchable%5D=true&columns%5B12%5D%5Borderable%5D=true&columns%5B12%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B12%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B13%5D%5Bdata%5D=revoked&columns%5B13%5D%5Bname%5D=&colum$s%5B13%5D%5Bsearchable%5D=true&columns%5B13%5D%5Borderable%5D=true&columns%5B13%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B13%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B14%5D%5Bdata%5D=exception&columns%5B14%5D%5Bname$5D=&columns%5B14%5D%5Bsearchable%5D=true&columns%5B14%5D%5Borderable%5D=true&columns%5B14%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B14%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B15%5D%5Bdata%5D=expires&columns%5B15%5$%5Bname%5D=&columns%5B15%5D%5Bsearchable%5D=true&columns%5B15%5D%5Borderable%5D=true&columns%5B15%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B15%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B16%5D%5Bdata%5D=eta&columns%5B$6%5D%5Bname%5D=&columns%5B16%5D%5Bsearchable%5D=true&columns%5B16%5D%5Borderable%5D=true&columns%5B16%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B16%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=7&order%5B0$5D%5Bdir%5D=asc&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1524558588961', version='HTTP/1.1', remote_ip='20.20.20.253', headers={'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8,ja;q=0.7,zh-TW;q$0.6', 'Accept-Encoding': 'gzip, deflate', 'Host': '10.10.10.80:5555', 'Accept': 'application/json, text/javascript, */*; q=0.01', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHT$L, like Gecko) Chrome/65.0.3325.181 Safari/537.36', 'Connection': 'keep-alive', 'X-Requested-With':'XMLHttpRequest', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Referer': 'http://10.10.10.80:5555/tasks'$ 'Authorization': 'Basic bGVlbjokODAwMjE1cWxvbmc='})
    Traceback (most recent call last):
      File "/wwwapps/movement/env/local/lib/python2.7/site-packages/tornado/web.py", line 1509, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/wwwapps/movement/env/local/lib/python2.7/site-packages/tornado/web.py", line 2897, in wrapper
        return method(self, *args, **kwargs)
      File "/wwwapps/movement/env/local/lib/python2.7/site-packages/flower/views/tasks.py", line 61, in get
        task = as_dict(task)
      File "/wwwapps/movement/env/local/lib/python2.7/site-packages/flower/utils/tasks.py", line 80, in as_dict
        return task.as_dict()
      File "/wwwapps/movement/env/local/lib/python2.7/site-packages/celery/events/state.py", line 358, in as_dict
        k: handler(k, pass1)(get(self, k)) for k in self._fields
      File "/wwwapps/movement/env/local/lib/python2.7/site-packages/celery/events/state.py", line 358, in <dictcomp>
        k: handler(k, pass1)(get(self, k)) for k in self._fields
      File "/wwwapps/movement/env/local/lib/python2.7/site-packages/kombu/utils/objects.py", line 44, in __get__
        value = obj.__dict__[self.__name__] = self.__get(obj)
      File "/wwwapps/movement/env/local/lib/python2.7/site-packages/celery/events/state.py", line 391, in root
        return self.root_id and self.cluster_state.tasks[self.root_id]
      File "/wwwapps/movement/env/local/lib/python2.7/site-packages/kombu/utils/functional.py", line 65, in __getitem__
        value = self[key] = self.data.pop(key)
      File "/usr/lib/python2.7/collections.py", line 160, in pop
        raise KeyError(key)
    KeyError: u'89a0146f-00ca-4b9f-92b7-572aeace1cd1'
```

And sometimes can't open tasks tab.

**Comment by ShalbafZadeh** [comment]
happens to me as well

**Comment by digitaldavenyc** [comment]
@ShalbafZadeh This has been on going for years.....

**Comment by LKI** [comment]
I had same error, and I found out it's because some request get 403 (our flower is behind company firewall, and there was some incorrect permission)

After fixing the 403, this error was fixed.
