### ISSUE TITLE
Unknown Celery version

### ISSUE THREAD

**Issue by abhineetraj** [mher/flower#823]
@mher Whenever I click on the queues on the flower console, I get the following error.

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/tornado/web.py", line 1415, in _execute
    result = yield result
  File "/usr/local/lib/python3.5/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/local/lib/python3.5/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.5/site-packages/tornado/gen.py", line 230, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python3.5/site-packages/flower/views/workers.py", line 37, in get
    self.render("worker.html", worker=dict(worker, name=name))
  File "/usr/local/lib/python3.5/site-packages/flower/views/__init__.py", line 21, in render
    super(BaseHandler, self).render(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/tornado/web.py", line 704, in render
    html = self.render_string(template_name, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/tornado/web.py", line 811, in render_string
    return t.generate(**namespace)
  File "/usr/local/lib/python3.5/site-packages/tornado/template.py", line 278, in generate
    return execute()
  File "worker_html.generated.py", line 264, in _tt_execute
    _tt_tmp = task['name']  # worker.html:202 (via base.html:55)
TypeError: string indices must be integers

I am not really sure if this is really something to do with the celery version.

**Comment by abhineetraj** [comment]
Nevermind, fixed this. 

Uninstalled the new celery version from the container and installed the celery that my app is using.

**Comment by ShalbafZadeh** [comment]
@abhineetraj glad it's fixed
please close issue
