### ISSUE TITLE
dbm.error: db type could not be determined

### ISSUE THREAD

**Issue by ebsaral** [mher/flower#827]
What I did:
I upgraded the server stack from Django 1.8 to 1.11 and from Python2.7 to Python3.6
Server is Ubuntu 16.04.5.

It was working fine but now when I ran the command, it gives me this error:

```
Traceback (most recent call last):
  File "/home/ubuntu/bluepoint/env/bin/flower", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/bluepoint/env/lib/python3.6/site-packages/flower/__main__.py", line 11, in main
    flower.execute_from_commandline()
  File "/home/ubuntu/bluepoint/env/lib/python3.6/site-packages/celery/bin/base.py", line 275, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/home/ubuntu/bluepoint/env/lib/python3.6/site-packages/flower/command.py", line 59, in handle_argv
    return self.run_from_argv(prog_name, argv)
  File "/home/ubuntu/bluepoint/env/lib/python3.6/site-packages/flower/command.py", line 43, in run_from_argv
    flower = Flower(capp=self.app, options=options, **settings)
  File "/home/ubuntu/bluepoint/env/lib/python3.6/site-packages/flower/app.py", line 42, in __init__
    max_tasks_in_memory=self.options.max_tasks)
  File "/home/ubuntu/bluepoint/env/lib/python3.6/site-packages/flower/events.py", line 77, in __init__
    state = shelve.open(self.db)
  File "/usr/lib/python3.6/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/usr/lib/python3.6/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/usr/lib/python3.6/dbm/__init__.py", line 88, in open
    raise error[0]("db type could not be determined")
dbm.error: db type could not be determined
```

The command I ran:
```
/home/ubuntu/my_app/env/bin/flower -A MyApp --port=5555 --persistent=True --basic_auth=3megawatt:ilovesolar2018
```

Flower version: 0.9.2

**Comment by sarunas-saulis-beauhurst** [comment]
We hit the same problem when migrating to Python3. It seems to be caused by flower trying to restore it's state as per your command and flower's use of shelve which doesn't seem to handle shelving between different Python versions particularly well.

The easiest solution if simply clearing current state, which should allow flower to store new state in Python 3.

Alternatively flower state management would need to be reworked to use a different approach, but I doubt it would be particularly easy to change to new format whilst also handling this specific edge case.

**Comment by ebsaral** [comment]
I removed `flower.db` in the root directory to fix it after moving to Python 3. @sarunas-saulis-beauhurst

**Comment by GeekyShacklebolt** [comment]
Was facing a related issue with `--persistent` as True, but deleting the older database file and specifying `--db` flag worked for me at the end. For reference: https://stackoverflow.com/questions/70475574/celery-flower-connection-issue-with-persistent-true
