### ISSUE TITLE
support for redis broker using ssl

### ISSUE THREAD

**Issue by liortamari** [mher/flower#832]
when connecting to ssl enabled redis server, the broker connection fails:

```
flower   -> flower:0.9.2 tornado:5.1 babel:2.6.0
software -> celery:4.1.1 (latentcall) kombu:4.2.1 py:3.6.6
            billiard:3.5.0.4 redis:2.10.6
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:db+postgresql://**:**@**/**

accept_content: ['json', 'pickle']
event_serializer: 'json'
result_serializer: 'pickle'
worker_prefetch_multiplier: 1
task_acks_late: True
task_default_queue: 'default'
task_default_exchange: 'default'
broker_url: 'redis://:********@***:6379/1'
broker_transport_options: {
 'visibility_timeout': 21600}
result_backend: 'db+postgresql://**:********@**/**'
worker_concurrency: 2
broker_use_ssl: {
 'ssl_cert_reqs': <VerifyMode.CERT_NONE: 0>}



[2018-08-19 13:17:04,618] INFO - Connected to redis://:**@**:6379/1
[2018-08-19 13:18:24,778] WARNING - 404 GET /broker (*.*.*.*): Unable to get queues: 'Error while reading from socket: (104, 'Connection reset by peer')'
[2018-08-19 13:21:03,036] ERROR - Uncaught exception GET /monitor/broker (*.*.*.*)
HTTPServerRequest(protocol='http', host='localhost:5555', method='GET', uri='/monitor/broker', version='HTTP/1.1', remote_ip='*.*.*.*')
Traceback (most recent call last):
  File "/virtual-envs/airflow/lib/python3.6/site-packages/redis/connection.py", line 174, in _read_from_socket
    data = recv(self._sock, socket_read_size)
  File "/virtual-envs/airflow/lib/python3.6/site-packages/redis/_compat.py", line 79, in recv
    return sock.recv(*args, **kwargs)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/virtual-envs/airflow/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/virtual-envs/airflow/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/virtual-envs/airflow/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/virtual-envs/airflow/lib/python3.6/site-packages/flower/views/monitor.py", line 102, in get
    queues = yield broker.queues(queue_names)
  File "/virtual-envs/airflow/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/virtual-envs/airflow/lib/python3.6/site-packages/tornado/gen.py", line 307, in wrapper
    result = func(*args, **kwargs)
  File "/virtual-envs/airflow/lib/python3.6/types.py", line 248, in wrapped
    coro = func(*args, **kwargs)
  File "/virtual-envs/airflow/lib/python3.6/site-packages/flower/utils/broker.py", line 135, in queues
    'messages': sum([self.redis.llen(x) for x in priority_names])
  File "/virtual-envs/airflow/lib/python3.6/site-packages/flower/utils/broker.py", line 135, in <listcomp>
    'messages': sum([self.redis.llen(x) for x in priority_names])
  File "/virtual-envs/airflow/lib/python3.6/site-packages/redis/client.py", line 1325, in llen
    return self.execute_command('LLEN', name)
  File "/virtual-envs/airflow/lib/python3.6/site-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/virtual-envs/airflow/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/virtual-envs/airflow/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/virtual-envs/airflow/lib/python3.6/site-packages/redis/connection.py", line 493, in connect
    self.on_connect()
  File "/virtual-envs/airflow/lib/python3.6/site-packages/redis/connection.py", line 561, in on_connect
    if nativestr(self.read_response()) != 'OK':
  File "/virtual-envs/airflow/lib/python3.6/site-packages/redis/connection.py", line 624, in read_response
    response = self._parser.read_response()
  File "/virtual-envs/airflow/lib/python3.6/site-packages/redis/connection.py", line 284, in read_response
    response = self._buffer.readline()
  File "/virtual-envs/airflow/lib/python3.6/site-packages/redis/connection.py", line 216, in readline
    self._read_from_socket()
  File "/virtual-envs/airflow/lib/python3.6/site-packages/redis/connection.py", line 191, in _read_from_socket
    (e.args,))
redis.exceptions.ConnectionError: Error while reading from socket: (104, 'Connection reset by peer')

**Comment by jsh2134** [comment]
I am also seeing this issue. Were you able to find a workaround?

**Comment by aydumoulin** [comment]
I can connect using `rediss://` uri style
However I see no direct way of passing along ssl options such as in celery

```python
broker_use_ssl = {'cert_reqs': ssl.CERT_REQUIRED}
```

**Comment by hoylemd** [comment]
> I can connect using `rediss://` uri style

How do you do this? I'm trying to pass it via command line, but I get an error

```
flower --broker="rediss://:my_password@redis_host:6380/0"
KeyError: 'No such transport: rediss.  Did you mean redis?'
```

**Comment by aydumoulin** [comment]
@hoylemd my version of flower allowed it 

See [celery's redis backend](https://github.com/celery/celery/blob/master/celery/backends/redis.py#L233)

**Comment by Penumbra69** [comment]
I'm not sure how any version of Flower can connect to a redis broker via SSL -- the broker code itself doesn't even pass any SSL options to the Redis client instantiation - an "ssl=True" parameter would be all that's needed here most times (or at least with my 'transport_encryption_enabled' AWS redis server), but the option to pass through the other SSL options required if needed would be nice too:

From [here](https://github.com/mher/flower/blob/75d407102dad796c619ee3577c767ed210fe50f5/flower/utils/broker.py#L144)
`
        self.redis = redis.Redis(host=self.host, port=self.port,
                                 db=self.vhost, password=self.password) 
`

For the full redis client signature - which does have SSL ability See: [Redis-Py Client INIT code](https://github.com/andymccurdy/redis-py/blob/0be4d2920684345eb52115c7142c39d65356e7d4/redis/client.py#L635)

For background -- After several hours of failed attempts configureing flower through airflow variables, and by hand - I tried connecting to my redis instance by hand using this exact same library - and the same behavior is observed when I do:
- In "airflow flower" - flower loads up, emits my Broker URL information and registered tasks - then freezes solid.
- In a python shell - If I don't pass in the ssl=True when connecting via a python shell, SAME frozen without an error behavior

If I pass 'ssl=true' to the redis client, the connection is successful. 

What's odd here is that airflow worker and airflow scheduler don't seem to mind, and connect to the redis instance with the AIRFLOW__CELERY__BROKER_USE_SSL=True option just fine... It's only flower which freezes solid and never errors.

Hope this clarifies some things.

**Comment by aydumoulin** [comment]
@Penumbra69 I experienced the same issue.

Celery worker/beat could connect and direct use of `redis-py` worked.
However flower is not functional

I suggest setting this up in private secure network and having a non SSL redis communication inside.
