### ISSUE TITLE
Unknown Celery version /login bug

### ISSUE THREAD

**Issue by AvkashKana** [mher/flower#837]
Unknown Celery version
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1369, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1572, in wrapper
    result = method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flower/views/auth.py", line 27, in get
    redirect_uri = self.settings[self._OAUTH_SETTINGS_KEY]['redirect_uri']
KeyError: 'oauth'

**Comment by AvkashKana** [comment]
Bug found when you go to server.address.com:5555/login

**Comment by mher** [comment]
This  bug is already fixed in the latest version

**Comment by bwaligorski** [comment]
Which version are you referring to? I am observing this issue in v0.9.4.
