### ISSUE TITLE
mongodb replica set, pidbox command error: ValueError("invalid literal for int() with base 10: '27018,192.168.1.249'",)

### ISSUE THREAD

**Issue by AlanW0ng** [mher/flower#838]
my  broker and backend were set as a mongo uri: ```mongodb://root:root@192.168.1.201:27018,192.168.1.249:27017,192.168.1.249:27018,192.168.1.188:27017,192.168.1.182:27017/admin```
environment: python 2.7, ubuntu 18.04
package version:
```
$ pip list|grep flower
flower                             0.9.2      
$ pip list|grep celery
celery                             4.2.1
```

and here's the full exception:
```
[2018-09-03 19:15:08,262: ERROR/MainProcess] pidbox command error: ValueError("invalid literal for int() with base 10: '27018,192.168.1.249'",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/kombu/pidbox.py", line 101, in dispatch
    reply = handle(method, arguments)
  File "/usr/local/lib/python2.7/dist-packages/kombu/pidbox.py", line 119, in handle_call
    return self.handle(method, arguments)
  File "/usr/local/lib/python2.7/dist-packages/kombu/pidbox.py", line 116, in handle
    return self.handlers[method](self.state, **arguments)
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/control.py", line 95, in conf
    return jsonify(state.app.conf.table(with_defaults=with_defaults),
  File "/usr/local/lib/python2.7/dist-packages/celery/app/utils.py", line 185, in table
    self if with_defaults else self.without_defaults())
  File "/usr/local/lib/python2.7/dist-packages/celery/app/utils.py", line 321, in filter_hidden_settings
    return {k: maybe_censor(k, v) for k, v in items(conf)}
  File "/usr/local/lib/python2.7/dist-packages/celery/app/utils.py", line 321, in <dictcomp>
    return {k: maybe_censor(k, v) for k, v in items(conf)}
  File "/usr/local/lib/python2.7/dist-packages/celery/app/utils.py", line 317, in maybe_censor
    return maybe_sanitize_url(value, mask=mask)
  File "/usr/local/lib/python2.7/dist-packages/kombu/utils/url.py", line 92, in maybe_sanitize_url
    return sanitize_url(url, mask)
  File "/usr/local/lib/python2.7/dist-packages/kombu/utils/url.py", line 85, in sanitize_url
    return as_url(*_parse_url(url), sanitize=True, mask=mask)
  File "/usr/local/lib/python2.7/dist-packages/kombu/utils/url.py", line 52, in url_to_parts
    parts.port,
  File "/usr/lib/python2.7/urlparse.py", line 113, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: '27018,192.168.1.249'
```

**Comment by auvipy** [comment]
could you share some more detail? also does upgrading celery and kombu work?

**Comment by mher** [comment]
mongodb broker doesn't implement celery events. Flower uses celery events.

**Comment by mpuhacz** [comment]
@mher are we talking about e.g: https://github.com/celery/celery/issues/1047 or maybe some other type of events? Seems like this feature has been implemented some long time ago.
