### ISSUE TITLE
How do you use Flower when your broker is the Django database?

### ISSUE THREAD

**Issue by orientalperil** [mher/flower#84]
I use the Django database as my broker for simplicity:

```
BROKER_URL = 'django://'
```

Trying to start flower gives me an error because it doesn't know about the Django settings:

```
bin/celery flower --broker=django://
[I 130524 08:59:14 command:57] Visit me at http://localhost:5555
Traceback (most recent call last):
  File "bin/celery", line 46, in <module>
    sys.exit(celery.__main__.main())
  File "/Users/haitran/repos/safe_and_sound/eggs/celery-3.0.19-py2.7.egg/celery/__main__.py", line 14, in main
    main()
  File "/Users/haitran/repos/safe_and_sound/eggs/celery-3.0.19-py2.7.egg/celery/bin/celery.py", line 957, in main
    cmd.execute_from_commandline(argv)
  File "/Users/haitran/repos/safe_and_sound/eggs/celery-3.0.19-py2.7.egg/celery/bin/celery.py", line 901, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/Users/haitran/repos/safe_and_sound/eggs/celery-3.0.19-py2.7.egg/celery/bin/base.py", line 187, in execute_from_commandline
    return self.handle_argv(prog_name, argv[1:])
  File "/Users/haitran/repos/safe_and_sound/eggs/celery-3.0.19-py2.7.egg/celery/bin/celery.py", line 893, in handle_argv
    return self.execute(command, argv)
  File "/Users/haitran/repos/safe_and_sound/eggs/celery-3.0.19-py2.7.egg/celery/bin/celery.py", line 868, in execute
    return cls(app=self.app).run_from_argv(self.prog_name, argv)
  File "/Users/haitran/repos/safe_and_sound/eggs/flower-0.5.1-py2.7.egg/flower/command.py", line 58, in run_from_argv
    logging.info('Broker: %s', self.app.connection().as_uri())
  File "/Users/haitran/repos/safe_and_sound/eggs/kombu-2.5.10-py2.7.egg/kombu/connection.py", line 561, in as_uri
    fields = self.info()
  File "/Users/haitran/repos/safe_and_sound/eggs/kombu-2.5.10-py2.7.egg/kombu/connection.py", line 549, in info
    return OrderedDict(self._info())
  File "/Users/haitran/repos/safe_and_sound/eggs/kombu-2.5.10-py2.7.egg/kombu/connection.py", line 523, in _info
    D = self.transport.default_connection_params
  File "/Users/haitran/repos/safe_and_sound/eggs/kombu-2.5.10-py2.7.egg/kombu/connection.py", line 764, in transport
    self._transport = self.create_transport()
  File "/Users/haitran/repos/safe_and_sound/eggs/kombu-2.5.10-py2.7.egg/kombu/connection.py", line 504, in create_transport
    return self.get_transport_cls()(client=self)
  File "/Users/haitran/repos/safe_and_sound/eggs/kombu-2.5.10-py2.7.egg/kombu/connection.py", line 511, in get_transport_cls
    transport_cls = get_transport_cls(transport_cls)
  File "/Users/haitran/repos/safe_and_sound/eggs/kombu-2.5.10-py2.7.egg/kombu/transport/__init__.py", line 105, in get_transport_cls
    _transport_cache[transport] = resolve_transport(transport)
  File "/Users/haitran/repos/safe_and_sound/eggs/kombu-2.5.10-py2.7.egg/kombu/transport/__init__.py", line 89, in resolve_transport
    return symbol_by_name(transport)
  File "/Users/haitran/repos/safe_and_sound/eggs/kombu-2.5.10-py2.7.egg/kombu/utils/__init__.py", line 80, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/usr/local/Cellar/python/2.7.1/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/haitran/repos/safe_and_sound/eggs/kombu-2.5.10-py2.7.egg/kombu/transport/django/__init__.py", line 14, in <module>
    from .models import Queue
  File "/Users/haitran/repos/safe_and_sound/eggs/kombu-2.5.10-py2.7.egg/kombu/transport/django/models.py", line 3, in <module>
    from django.db import models
  File "/Users/haitran/repos/safe_and_sound/eggs/Django-1.5.1-py2.7.egg/django/db/__init__.py", line 11, in <module>
    if settings.DATABASES and DEFAULT_DB_ALIAS not in settings.DATABASES:
  File "/Users/haitran/repos/safe_and_sound/eggs/Django-1.5.1-py2.7.egg/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/Users/haitran/repos/safe_and_sound/eggs/Django-1.5.1-py2.7.egg/django/conf/__init__.py", line 46, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting DATABASES, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```

I set the environment variable `DJANGO_SETTINGS_MODULE`, but it had no effect.  Is this possible?

**Comment by nikhil-above** [comment]
Oh. This info should be in documentation.

**Comment by Code-Joke** [comment]
> I figured it out: `python manage.py celery flower`

It is not working..
