### ISSUE TITLE
Clicking on any worker name in the dashboard throws error

### ISSUE THREAD

**Issue by dickensja** [mher/flower#853]
Clicking on any worker name in the dashboard throws the following:
```
flower   -> flower:1.0.0-dev tornado:4.5.3 babel:2.6.0
software -> celery:4.2.1 (windowlicker) kombu:4.2.1 py:2.7.15rc1
            billiard:3.5.0.4 py-amqp:2.3.2
platform -> system:Linux arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled



Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1512, in _execute
    result = yield result
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python2.7/dist-packages/flower/views/workers.py", line 34, in get
    self.render("worker.html", worker=dict(worker, name=name))
  File "/usr/local/lib/python2.7/dist-packages/flower/views/__init__.py", line 21, in render
    super(BaseHandler, self).render(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 724, in render
    html = self.render_string(template_name, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 865, in render_string
    return t.generate(**namespace)
  File "/usr/local/lib/python2.7/dist-packages/tornado/template.py", line 348, in generate
    return execute()
  File "worker_html.generated.py", line 264, in _tt_execute
    _tt_tmp = task['name']  # worker.html:212 (via base.html:55)
TypeError: string indices must be integers
```

**Comment by ushuz** [comment]
Same here
