### ISSUE TITLE
Got "Unknown Celery version" error running flower with celery 4

### ISSUE THREAD

**Issue by zachliu** [mher/flower#872]
Does flower support celery 4?
I have `celery 4.2.1` and `flower 0.9.2`. I got this:

```
Unknown Celery version
Traceback (most recent call last):
File "/usr/local/bin/flower", line 11, in <module>
sys.exit(main())
File "/usr/local/lib/python2.7/dist-packages/flower/__main__.py", line 11, in main
flower.execute_from_commandline()
File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 275, in execute_from_commandline
return self.handle_argv(self.prog_name, argv[1:])
File "/usr/local/lib/python2.7/dist-packages/flower/command.py", line 59, in handle_argv
return self.run_from_argv(prog_name, argv)
File "/usr/local/lib/python2.7/dist-packages/flower/command.py", line 42, in run_from_argv
self.app.loader.import_default_modules()
File "/usr/local/lib/python2.7/dist-packages/celery/loaders/base.py", line 109, in import_default_modules
return [self.import_task_module(m) for m in self.default_modules]
File "/usr/local/lib/python2.7/dist-packages/kombu/utils/objects.py", line 44, in __get__
value = obj.__dict__[self.__name__] = self.__get(obj)
File "/usr/local/lib/python2.7/dist-packages/celery/loaders/base.py", line 227, in default_modules
tuple(maybe_list(self.app.conf.imports)) +
File "/usr/local/lib/python2.7/dist-packages/celery/utils/collections.py", line 126, in __getattr__
return self[k]
File "/usr/local/lib/python2.7/dist-packages/celery/utils/collections.py", line 429, in __getitem__
return getitem(k)
File "/usr/local/lib/python2.7/dist-packages/celery/utils/collections.py", line 278, in __getitem__
return mapping[_key]
File "/usr/lib/python2.7/UserDict.py", line 36, in __getitem__
if key in self.data:
File "/usr/local/lib/python2.7/dist-packages/kombu/utils/objects.py", line 44, in __get__
value = obj.__dict__[self.__name__] = self.__get(obj)
File "/usr/local/lib/python2.7/dist-packages/celery/app/base.py", line 141, in data
return self.callback()
File "/usr/local/lib/python2.7/dist-packages/celery/app/base.py", line 924, in _finalize_pending_conf
conf = self._conf = self._load_config()
File "/usr/local/lib/python2.7/dist-packages/celery/app/base.py", line 937, in _load_config
self.prepare_config(self.loader.conf), self._preconf,
File "/usr/local/lib/python2.7/dist-packages/celery/loaders/base.py", line 235, in conf
self._conf = self.read_configuration()
File "/usr/local/lib/python2.7/dist-packages/celery/loaders/base.py", line 215, in read_configuration
usercfg = self._import_config_module(custom_config)
File "/usr/local/lib/python2.7/dist-packages/celery/loaders/base.py", line 151, in _import_config_module
self.find_module(name)
File "/usr/local/lib/python2.7/dist-packages/celery/loaders/base.py", line 162, in find_module
return find_module(module)
File "/usr/local/lib/python2.7/dist-packages/celery/utils/imports.py", line 85, in find_module
mpart = imp('.'.join(parts[:i + 1]))
File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
__import__(name)
ImportError: Import by filename is not supported.
```

**Comment by Kub-AT** [comment]
Yes it does.

**Comment by zachliu** [comment]
@Kub-AT Thank you for the succinct answer :joy: But the `Unknown Celery version` error msg says otherwise.

Btw, this is how i start the flower
`exec /usr/local/bin/flower -A redash.worker --conf=/app/flowerconfig.py`

```python
# flowerconfig.py
from settings import CELERY_BROKER # This is Redis

broker_api = CELERY_BROKER
persistent = True
address = '0.0.0.0'
port = 5555
```

It works under celery 3 but not 4.

**Comment by zachliu** [comment]
This is so weird :confused: 
If I do this:
```shell
$ /usr/local/bin/flower -A redash.worker --conf=flowerconfig.py
```
I've got `ImportError: Import by filename is not supported.`

If I do this:
```shell
$ /usr/local/bin/flower -A redash.worker --conf=flowerconfig
```
I've got `ImportError: No module named flowerconfig`

To make it work, I have to keep two files: `flowerconfig` and `flowerconfig.py`. Both with the same content :scream:

**Comment by Kub-AT** [comment]
try `--config` not `--conf` or without `celeryconfig.py` is default I think.

`If you’re using the default loader, you must create the celeryconfig.py module and make sure it’s available on the Python path.`
http://docs.celeryproject.org/en/v4.2.1/userguide/configuration.html

**Comment by c0n71nu3** [comment]
Do we have any workarounds/solutions to the problem being discussed above ?

**Comment by zachliu** [comment]
@c0n71nu3 No solutions, just my strange workaround.

**Comment by mher** [comment]
Please try the latest version
