### ISSUE TITLE
Version check with celery 3.1.26.post2

### ISSUE THREAD

**Issue by arthurio** [mher/flower#887]
Versions

```
celery==3.1.26.post2
flower==0.9.2
```

Traceback

```
Traceback (most recent call last):
  File "/opt/pyenv/versions/xxx/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/opt/pyenv/versions/2.7.15/envs/xxx/lib/python2.7/site-packages/celery/__main__.py", line 30, in main
    main()
  File "/opt/pyenv/versions/2.7.15/envs/xxx/lib/python2.7/site-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/opt/pyenv/versions/2.7.15/envs/xxx/lib/python2.7/site-packages/celery/bin/celery.py", line 793, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/opt/pyenv/versions/2.7.15/envs/xxx/lib/python2.7/site-packages/celery/bin/base.py", line 311, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/opt/pyenv/versions/2.7.15/envs/xxx/lib/python2.7/site-packages/celery/bin/celery.py", line 785, in handle_argv
    return self.execute(command, argv)
  File "/opt/pyenv/versions/2.7.15/envs/xxx/lib/python2.7/site-packages/celery/bin/celery.py", line 717, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/opt/pyenv/versions/2.7.15/envs/xxx/lib/python2.7/site-packages/flower/command.py", line 43, in run_from_argv
    flower = Flower(capp=self.app, options=options, **settings)
  File "/opt/pyenv/versions/2.7.15/envs/xxx/lib/python2.7/site-packages/flower/app.py", line 42, in __init__
    max_tasks_in_memory=self.options.max_tasks)
  File "/opt/pyenv/versions/2.7.15/envs/xxx/lib/python2.7/site-packages/flower/events.py", line 70, in __init__
    if self.persistent and tuple(map(int, celery.__version__.split('.'))) < (3, 0, 15):
ValueError: invalid literal for int() with base 10: 'post2'
```

To handle the case of `3.1.26.post2` we could replace `celery.__version__.split('.')` with `celery.__version__.split('.')[:3]`.
However, I'm not sure if there are similar checks in other places of the code base?

**Comment by denizdogan** [comment]
This was fixed about a year ago, here: https://github.com/pachewise/flower/commit/c0166a61e36d1424538a3283f48ff94bb7a1736c

Not sure it's worth creating a 0.9.3 fix for it, but it is what it is :)

**Comment by mher** [comment]
The fix is released
