### ISSUE TITLE
Failed to capture events: 'Error while reading from socket: 

### ISSUE THREAD

**Issue by echoocking** [mher/flower#893]
at python3.7, flower 0.9.3, celery 4.3.0 occur
Failed to capture events: 'Error while reading from socket: ('Connection closed by server.',)', trying again in 1 seconds.
```
[E 190413 14:40:27 events:125] Failed to capture events: 'Error while reading from socket: ('Connection closed by server.',)', trying again in 1 seconds.
[D 190413 14:40:27 events:126] Error while reading from socket: ('Connection closed by server.',)
    Traceback (most recent call last):
      File "/root/.pyenv/versions/3.7.2/envs/py3.7/lib/python3.7/site-packages/redis/connection.py", line 185, in _read_from_socket
        raise socket.error(SERVER_CLOSED_CONNECTION_ERROR)
    OSError: Connection closed by server.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/root/.pyenv/versions/3.7.2/envs/py3.7/lib/python3.7/site-packages/flower/events.py", line 114, in run
        recv.capture(limit=None, timeout=None, wakeup=True)
      File "/root/.pyenv/versions/3.7.2/envs/py3.7/lib/python3.7/site-packages/celery/events/receiver.py", line 93, in capture
        return list(self.consume(limit=limit, timeout=timeout, wakeup=wakeup))
      File "/root/.pyenv/versions/3.7.2/envs/py3.7/lib/python3.7/site-packages/kombu/mixins.py", line 192, in consume
        conn.drain_events(timeout=safety_interval)
      File "/root/.pyenv/versions/3.7.2/envs/py3.7/lib/python3.7/site-packages/kombu/connection.py", line 315, in drain_events
        return self.transport.drain_events(self.connection, **kwargs)
      File "/root/.pyenv/versions/3.7.2/envs/py3.7/lib/python3.7/site-packages/kombu/transport/virtual/base.py", line 963, in drain_events
        get(self._deliver, timeout=timeout)
      File "/root/.pyenv/versions/3.7.2/envs/py3.7/lib/python3.7/site-packages/kombu/transport/redis.py", line 370, in get
        ret = self.handle_event(fileno, event)
      File "/root/.pyenv/versions/3.7.2/envs/py3.7/lib/python3.7/site-packages/kombu/transport/redis.py", line 352, in handle_event
        return self.on_readable(fileno), self
      File "/root/.pyenv/versions/3.7.2/envs/py3.7/lib/python3.7/site-packages/kombu/transport/redis.py", line 348, in on_readable
        chan.handlers[type]()
      File "/root/.pyenv/versions/3.7.2/envs/py3.7/lib/python3.7/site-packages/kombu/transport/redis.py", line 683, in _receive
        ret.append(self._receive_one(c))
      File "/root/.pyenv/versions/3.7.2/envs/py3.7/lib/python3.7/site-packages/kombu/transport/redis.py", line 689, in _receive_one
        response = c.parse_response()
      File "/root/.pyenv/versions/3.7.2/envs/py3.7/lib/python3.7/site-packages/redis/client.py", line 3036, in parse_response
        return self._execute(connection, connection.read_response)
      File "/root/.pyenv/versions/3.7.2/envs/py3.7/lib/python3.7/site-packages/redis/client.py", line 3013, in _execute
        return command(*args)
      File "/root/.pyenv/versions/3.7.2/envs/py3.7/lib/python3.7/site-packages/redis/connection.py", line 637, in read_response
        response = self._parser.read_response()
      File "/root/.pyenv/versions/3.7.2/envs/py3.7/lib/python3.7/site-packages/redis/connection.py", line 330, in read_response
        response = [self.read_response() for i in xrange(length)]
      File "/root/.pyenv/versions/3.7.2/envs/py3.7/lib/python3.7/site-packages/redis/connection.py", line 330, in <listcomp>
        response = [self.read_response() for i in xrange(length)]
      File "/root/.pyenv/versions/3.7.2/envs/py3.7/lib/python3.7/site-packages/redis/connection.py", line 324, in read_response
        response = self._buffer.read(length)
      File "/root/.pyenv/versions/3.7.2/envs/py3.7/lib/python3.7/site-packages/redis/connection.py", line 205, in read
        self._read_from_socket(length - self.length)
      File "/root/.pyenv/versions/3.7.2/envs/py3.7/lib/python3.7/site-packages/redis/connection.py", line 199, in _read_from_socket
        (e.args,))
    redis.exceptions.ConnectionError: Error while reading from socket: ('Connection closed by server.',)
```

**Comment by denizdogan** [comment]
I've been getting the same problem a lot lately as well, but couldn't figure out whether it was Flower or something else. No idea why.

**Comment by echoocking** [comment]
@denizdogan Maybe you should update redis connection params. I solve this problem some time ago.So i closed this issue. If anything i can help you, please let me know. :)

**Comment by KarlaSQ** [comment]
@echoocking I've been getting the same problem too.But I'm not sure which connection params need to be updated.How did you solve this issue ?

**Comment by echoocking** [comment]
@KarlaSQ can you show me your flower settings or start command?
