### ISSUE TITLE
500 Errors / SSL Assertion Error

### ISSUE THREAD

**Issue by NickWoodhams** [mher/flower#918]
flower   -> flower:1.0.0-dev tornado:5.1.1 humanize:(0, 4)
software -> celery:4.3.0 (rhubarb) kombu:4.6.3 py:3.7.4
            billiard:3.6.0.0 py-amqp:2.5.0
platform -> system:Linux arch:64bit
            kernel version:4.15.0-55-generic imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled

Traceback (most recent call last):
  File "/home/nick/autoauctions.io/venv/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/home/nick/autoauctions.io/venv/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/nick/autoauctions.io/venv/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/nick/autoauctions.io/venv/lib/python3.7/site-packages/flower/views/auth.py", line 112, in get
    code=self.get_argument('code'),
  File "/home/nick/autoauctions.io/venv/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/nick/autoauctions.io/venv/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/nick/autoauctions.io/venv/lib/python3.7/site-packages/flower/views/auth.py", line 98, in get_authenticated_user
    'Accept': 'application/json'}, body=body)
  File "/home/nick/autoauctions.io/venv/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/nick/autoauctions.io/venv/lib/python3.7/site-packages/tornado/simple_httpclient.py", line 272, in run
    max_buffer_size=self.max_buffer_size)
  File "/home/nick/autoauctions.io/venv/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/nick/autoauctions.io/venv/lib/python3.7/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/home/nick/autoauctions.io/venv/lib/python3.7/site-packages/tornado/tcpclient.py", line 242, in connect
    server_hostname=host)
  File "/home/nick/autoauctions.io/venv/lib/python3.7/site-packages/tornado/iostream.py", line 1381, in start_tls
    do_handshake_on_connect=False)
  File "/home/nick/autoauctions.io/venv/lib/python3.7/site-packages/tornado/netutil.py", line 565, in ssl_wrap_socket
    context = ssl_options_to_context(ssl_options)
  File "/home/nick/autoauctions.io/venv/lib/python3.7/site-packages/tornado/netutil.py", line 533, in ssl_options_to_context
    assert isinstance(ssl_options, dict)
AssertionError

**Comment by mher** [comment]
This looks like a misconfiguration issue. Make sure ssl_options is configured properly
