### ISSUE TITLE
flower fails to load

### ISSUE THREAD

**Issue by sg85mang** [mher/flower#922]
flower -A celery_main --port=5555
flower   -> flower:0.9.3 tornado:5.1.1 babel:2.7.0
software -> celery:4.3.0 (rhubarb) kombu:4.6.3 py:3.7.3
            billiard:3.6.0.0 redis:3.3.7
platform -> system:Linux arch:64bit, ELF
            kernel version:5.0.0-20-generic imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:rpc:///

broker_url: 'redis://localhost:6379/0'
result_backend: 'rpc:///'
include: ['celery_main.task_receiver']

Traceback (most recent call last):
  File "/usr/local/bin/flower", line 11, in <module>
    load_entry_point('flower==0.9.3', 'console_scripts', 'flower')()
  File "/usr/local/lib/python3.7/dist-packages/flower/__main__.py", line 11, in main
    flower.execute_from_commandline()
  File "/home/w3pt/.local/lib/python3.7/site-packages/celery/bin/base.py", line 298, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/local/lib/python3.7/dist-packages/flower/command.py", line 56, in handle_argv
    return self.run_from_argv(prog_name, argv)
  File "/usr/local/lib/python3.7/dist-packages/flower/command.py", line 40, in run_from_argv
    flower = Flower(capp=self.app, options=options, **settings)
  File "/usr/local/lib/python3.7/dist-packages/flower/app.py", line 32, in __init__
    self.io_loop = io_loop or ioloop.IOLoop.instance()
  File "/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py", line 221, in instance
    return IOLoop.current()
  File "/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py", line 282, in current
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.7/asyncio/events.py", line 644, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'MainThread'.

**Comment by rishabhc32** [comment]
If someone is facing this issue, make sure that you are not calling `eventlet.monkey_patch()` yourself. For me, calling `eventlet.monkey_patch` in one the file was causing this issue, removing it everything worked normally.
