### ISSUE TITLE
Breaks with tornado 6.x

### ISSUE THREAD

**Issue by robvdl** [mher/flower#934]
I am using the PYTHON:3.6 docker image, running celery 4.3.0.

If I don't pin tornado at 5.1.1, celery breaks if flower is simply installed. Even if I am not launching flower itself, it seems celery is loading some flower related things as seen in my traceback. These break with tornado 6.x but it's fine if you pin torando to 5.1.1

It seems flower needs to adapt to the latest tornado 6.x releases.

```
celery_1    | Traceback (most recent call last):
celery_1    |   File "/virtualenv/bin/celery", line 10, in <module>
celery_1    |     sys.exit(main())
celery_1    |   File "/virtualenv/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
celery_1    |     _main()
celery_1    |   File "/virtualenv/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
celery_1    |     cmd.execute_from_commandline(argv)
celery_1    |   File "/virtualenv/lib/python3.6/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
celery_1    |     super(CeleryCommand, self).execute_from_commandline(argv)))
celery_1    |   File "/virtualenv/lib/python3.6/site-packages/celery/bin/base.py", line 283, in execute_from_commandline
celery_1    |     self.on_concurrency_setup()
celery_1    |   File "/virtualenv/lib/python3.6/site-packages/celery/bin/celery.py", line 539, in on_concurrency_setup
celery_1    |     self.load_extension_commands()
celery_1    |   File "/virtualenv/lib/python3.6/site-packages/celery/bin/celery.py", line 543, in load_extension_commands
celery_1    |     self.register_command).load()
celery_1    |   File "/virtualenv/lib/python3.6/site-packages/celery/bin/base.py", line 152, in load
celery_1    |     for name, cls in imports.load_extension_classes(self.namespace):
celery_1    |   File "/virtualenv/lib/python3.6/site-packages/celery/utils/imports.py", line 163, in load_extension_classes
celery_1    |     cls = symbol_by_name(class_name)
celery_1    |   File "/virtualenv/lib/python3.6/site-packages/kombu/utils/imports.py", line 57, in symbol_by_name
celery_1    |     module = imp(module_name, package=package, **kwargs)
celery_1    |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
celery_1    |     return _bootstrap._gcd_import(name[level:], package, level)
celery_1    |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
celery_1    |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
celery_1    |   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
celery_1    |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
celery_1    |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
celery_1    |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
celery_1    |   File "/virtualenv/lib/python3.6/site-packages/flower/command.py", line 18, in <module>
celery_1    |     from .app import Flower
celery_1    |   File "/virtualenv/lib/python3.6/site-packages/flower/app.py", line 15, in <module>
celery_1    |     from .urls import handlers
celery_1    |   File "/virtualenv/lib/python3.6/site-packages/flower/urls.py", line 9, in <module>
celery_1    |     from .api import tasks
celery_1    |   File "/virtualenv/lib/python3.6/site-packages/flower/api/tasks.py", line 81, in <module>
celery_1    |     class TaskApply(BaseTaskHandler):
celery_1    |   File "/virtualenv/lib/python3.6/site-packages/flower/api/tasks.py", line 83, in TaskApply
celery_1    |     @web.asynchronous
celery_1    | AttributeError: module 'tornado.web' has no attribute 'asynchronous'
```

**Comment by robvdl** [comment]
I am wondering. celery-flower on pypi had a 1.0.1 release in 2017 and then nothing since.

It is currently 2019 and there are 35 unmerged pull requests. Is this project dead? It seems in need of some love.

**Comment by robvdl** [comment]
I think I am confused between celery-flower and flower on pypi.

Because there is a project on pypi called celery-flower with a newer version 1.0.1, one would naturally think that this must be the lastest flower as there are multiple packages called flower, celery-flower and flower-new on pypi which is a bit confusing.

It seems this project is active and the version is 0.9.3 on pypi, so perhaps what I have been using all this time is the wrong library.

**Comment by robvdl** [comment]
Sorry this was the wrong library I was using, django-flower. Have switched to flower 0.9.3 and all is good. Thank you, I'll close this issue.
