### ISSUE TITLE
Unknown Celery version

### ISSUE THREAD

**Issue by sandudorogan** [mher/flower#936]
When searching for a task, I got this trace:
```
Unknown Celery version
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 2721, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flower/views/tasks.py", line 88, in get
    search=search
  File "/usr/local/lib/python2.7/dist-packages/flower/views/__init__.py", line 20, in render
    super(BaseHandler, self).render(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 704, in render
    html = self.render_string(template_name, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 811, in render_string
    return t.generate(**namespace)
  File "/usr/local/lib/python2.7/dist-packages/tornado/template.py", line 278, in generate
    return execute()
  File "tasks_html.generated.py", line 225, in _tt_execute
    for uuid, task in tasks:  # tasks.html:151 (via base.html:49)
  File "/usr/local/lib/python2.7/dist-packages/flower/utils/tasks.py", line 46, in iter_tasks
    if not satisfies_search_terms(task, any_value_search_term, result_search_term, args_search_terms, kwargs_search_terms):
  File "/usr/local/lib/python2.7/dist-packages/flower/utils/search.py", line 32, in satisfies_search_terms
    any_value_search_term and any_value_search_term in '|'.join([task.args, task.kwargs, str(task.result)]),
TypeError: sequence item 0: expected string, NoneType found
```

These are the arguments that got me the error:
![image](https://user-images.githubusercontent.com/15573842/66736023-c7f54a80-ee70-11e9-9e32-05eabb81a69a.png)

**Comment by mher** [comment]
This error should be fixed in recent flower version
