### ISSUE TITLE
Have an issue with running flower with rabbitmq

### ISSUE THREAD

**Issue by imomaliev** [mher/flower#937]
here is my flowerconfig.py
```
tasks_columns = "name,uuid,state,args,kwargs,result,received,eta,started,runtime,worker"
persistent = True
xhaeders = True
db = "/project/flower/db"
broker_api = "http://guest:guest@rabbitmq:15672/api/"
```

```
Attaching to project_flower_1
Terminated
Celery workers not available
-> celery@worker.project: OK
        pong
Starting flower
[I 191017 13:57:24 command:136] Visit me at http://localhost:5555
[I 191017 13:57:24 command:141] Broker: amqp://guest:**@rabbitmq:5672//
[I 191017 13:57:24 command:144] Registered tasks: 
    ['action:contacts-sync',
     'action:prospect',
     'celery.accumulate',
     'celery.backend_cleanup',
     'celery.chain',
     'celery.chord',
     'celery.chord_unlock',
     'celery.chunks',
     'celery.group',
     'celery.map',
     'celery.starmap']
[I 191017 13:57:24 mixins:229] Connected to amqp://guest:**@rabbitmq:5672//
[E 191017 13:57:31 web:1670] Uncaught exception GET /login?code=4/sQH5pAvoA5y3fgg2g6u0tvQrFap-UjHe1k8uli1hSY7VDqovZoxmgdaiewzsOA5RkM0BH7M2S2FhExDTARuUnVs&scope=email%20profile%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email&authuser=0&hd=project&session_state=54e5e9b5ccca41ae12a39f18ad82e53cf2d665e9..872f&prompt=none (172.18.0.9)
    HTTPServerRequest(protocol='http', host='project', method='GET', uri='/login?code=4/sQH5pAvoA5y3fgg2g6u0tvQrFap-UjHe1k8uli1hSY7VDqovZoxmgdaiewzsOA5RkM0BH7M2S2FhExDTARuUnVs&scope=email%20profile%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email&authuser=0&hd=project&session_state=54e5e9b5ccca41ae12a39f18ad82e53cf2d665e9..872f&prompt=none', version='HTTP/1.1', remote_ip='172.18.0.9')
    Traceback (most recent call last):
      File "/project/backend/.venv/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/project/backend/.venv/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/project/backend/.venv/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/project/backend/.venv/lib/python3.7/site-packages/flower/views/auth.py", line 32, in get
        yield self._on_auth(user)
      File "/project/backend/.venv/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/project/backend/.venv/lib/python3.7/site-packages/tornado/gen.py", line 1147, in run
        yielded = self.gen.send(value)
      File "/project/backend/.venv/lib/python3.7/site-packages/flower/views/auth.py", line 66, in _on_auth
        if self.application.options.url_prefix and next[0] != '/':
    TypeError: 'builtin_function_or_method' object is not subscriptable
[E 191017 13:57:39 web:1670] Uncaught exception GET /task/7ad008a1-67ce-4605-9eef-3103f693c0aa (172.18.0.9)
    HTTPServerRequest(protocol='http', host='project', method='GET', uri='/task/7ad008a1-67ce-4605-9eef-3103f693c0aa', version='HTTP/1.1', remote_ip='172.18.0.9')
    Traceback (most recent call last):
      File "/project/backend/.venv/lib/python3.7/site-packages/kombu/utils/objects.py", line 42, in __get__
        return obj.__dict__[self.__name__]
    KeyError: 'timezone'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/project/backend/.venv/lib/python3.7/site-packages/kombu/utils/objects.py", line 42, in __get__
        return obj.__dict__[self.__name__]
    KeyError: 'data'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/project/backend/.venv/lib/python3.7/site-packages/tornado/web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/project/backend/.venv/lib/python3.7/site-packages/tornado/web.py", line 3006, in wrapper
        return method(self, *args, **kwargs)
      File "/project/backend/.venv/lib/python3.7/site-packages/flower/views/tasks.py", line 28, in get
        self.render("task.html", task=task)
      File "/project/backend/.venv/lib/python3.7/site-packages/flower/views/__init__.py", line 21, in render
        super(BaseHandler, self).render(*args, **kwargs)
      File "/project/backend/.venv/lib/python3.7/site-packages/tornado/web.py", line 766, in render
        html = self.render_string(template_name, **kwargs)
      File "/project/backend/.venv/lib/python3.7/site-packages/tornado/web.py", line 907, in render_string
        return t.generate(**namespace)
      File "/project/backend/.venv/lib/python3.7/site-packages/tornado/template.py", line 346, in generate
        return execute()
      File "task_html.generated.py", line 207, in _tt_execute
        _tt_tmp = humanize(getattr(task, name, None), type='time')  # task.html:73 (via base.html:55)
      File "/project/backend/.venv/lib/python3.7/site-packages/flower/utils/template.py", line 38, in humanize
        tz = timezone(tz) if tz else getattr(current_app, 'timezone', '') or utc
      File "/project/backend/.venv/lib/python3.7/site-packages/celery/local.py", line 146, in __getattr__
        return getattr(self._get_current_object(), name)
      File "/project/backend/.venv/lib/python3.7/site-packages/kombu/utils/objects.py", line 44, in __get__
        value = obj.__dict__[self.__name__] = self.__get(obj)
      File "/project/backend/.venv/lib/python3.7/site-packages/celery/app/base.py", line 1271, in timezone
        if not conf.timezone:
      File "/project/backend/.venv/lib/python3.7/site-packages/celery/app/utils.py", line 137, in timezone
        return self.first('timezone', 'time_zone')
      File "/project/backend/.venv/lib/python3.7/site-packages/celery/utils/collections.py", line 455, in first
        return first(None, (self.get(key) for key in keys))
      File "/project/backend/.venv/lib/python3.7/site-packages/celery/utils/functional.py", line 84, in first
        None,
      File "/project/backend/.venv/lib/python3.7/site-packages/celery/utils/functional.py", line 82, in <genexpr>
        (v for v in evaluate_promises(it) if (
      File "/project/backend/.venv/lib/python3.7/site-packages/celery/utils/functional.py", line 69, in evaluate_promises
        for value in it:
      File "/project/backend/.venv/lib/python3.7/site-packages/celery/utils/collections.py", line 455, in <genexpr>
        return first(None, (self.get(key) for key in keys))
      File "/project/backend/.venv/lib/python3.7/site-packages/celery/utils/collections.py", line 460, in get
        return self[key]
      File "/project/backend/.venv/lib/python3.7/site-packages/celery/utils/collections.py", line 437, in __getitem__
        return getitem(k)
      File "/project/backend/.venv/lib/python3.7/site-packages/celery/utils/collections.py", line 286, in __getitem__
        return mapping[_key]
      File "/project/backend/.venv/lib/python3.7/collections/__init__.py", line 1023, in __getitem__
        if key in self.data:
      File "/project/backend/.venv/lib/python3.7/site-packages/kombu/utils/objects.py", line 44, in __get__
        value = obj.__dict__[self.__name__] = self.__get(obj)
      File "/project/backend/.venv/lib/python3.7/site-packages/celery/app/base.py", line 141, in data
        return self.callback()
      File "/project/backend/.venv/lib/python3.7/site-packages/celery/app/base.py", line 935, in _finalize_pending_conf
        conf = self._conf = self._load_config()
      File "/project/backend/.venv/lib/python3.7/site-packages/celery/app/base.py", line 948, in _load_config
        self.prepare_config(self.loader.conf), self._preconf,
      File "/project/backend/.venv/lib/python3.7/site-packages/celery/loaders/base.py", line 238, in conf
        self._conf = self.read_configuration()
      File "/project/backend/.venv/lib/python3.7/site-packages/celery/loaders/base.py", line 218, in read_configuration
        usercfg = self._import_config_module(custom_config)
      File "/project/backend/.venv/lib/python3.7/site-packages/celery/loaders/base.py", line 151, in _import_config_module
        self.find_module(name)
      File "/project/backend/.venv/lib/python3.7/site-packages/celery/loaders/base.py", line 162, in find_module
        return find_module(module)
      File "/project/backend/.venv/lib/python3.7/site-packages/celery/utils/imports.py", line 81, in find_module
        return imp(module)
      File "/project/backend/.venv/lib/python3.7/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
    ModuleNotFoundError: No module named '/project/flowerconfig'
```

**Comment by imomaliev** [comment]
after some digging around looks like this is related to #923, interestingly if arguments are passed vi command line they are used correctly and issue will occur
