### ISSUE TITLE
asyncio NotImplementedError when running Flower with Python3.8 on Windows

### ISSUE THREAD

**Issue by johanvergeer** [mher/flower#973]
When I run Flower on Windows with Python 3.8 I get an error:

`our_app.tasks` is the module with Celery tasks

```
celery -A our_app.tasks flower
[2020-05-08 09:21:47,519] our_app.celery_app INFO: App configured.
Traceback (most recent call last):
  File "C:\Users\Me\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Me\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Me\our_app.our_module.py\venv2\Scripts\celery.exe\__main__.py", line 7, in <module>
  File "c:\users\Me\our_app.our_module.py\venv2\lib\site-packages\celery\__main__.py", line 16, in main
    _main()
  File "c:\users\Me\our_app.our_module.py\venv2\lib\site-packages\celery\bin\celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "c:\users\Me\our_app.our_module.py\venv2\lib\site-packages\celery\bin\celery.py", line 495, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "c:\users\Me\our_app.our_module.py\venv2\lib\site-packages\celery\bin\base.py", line 305, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "c:\users\Me\our_app.our_module.py\venv2\lib\site-packages\celery\bin\celery.py", line 487, in handle_argv
    return self.execute(command, argv)
  File "c:\users\Me\our_app.our_module.py\venv2\lib\site-packages\celery\bin\celery.py", line 415, in execute
    return cls(
  File "c:\users\Me\our_app.our_module.py\venv2\lib\site-packages\flower\command.py", line 51, in run_from_argv
    flower.start()
  File "c:\users\Me\our_app.our_module.py\venv2\lib\site-packages\flower\app.py", line 50, in start
    self.listen(self.options.port, address=self.options.address,
  File "c:\users\Me\our_app.our_module.py\venv2\lib\site-packages\tornado\web.py", line 2116, in listen
    server.listen(port, address)
  File "c:\users\Me\our_app.our_module.py\venv2\lib\site-packages\tornado\tcpserver.py", line 152, in listen
    self.add_sockets(sockets)
  File "c:\users\Me\our_app.our_module.py\venv2\lib\site-packages\tornado\tcpserver.py", line 165, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "c:\users\Me\our_app.our_module.py\venv2\lib\site-packages\tornado\netutil.py", line 279, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "c:\users\Me\our_app.our_module.py\venv2\lib\site-packages\tornado\platform\asyncio.py", line 100, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "C:\Users\Me\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError
```

After adding the following code to flowerconfig.py in the root of our project the issue is solved:

```python
import asyncio
import sys

if sys.platform == 'win32':
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
```

**Comment by mher** [comment]
This is known tornado/asyncio issue https://github.com/tornadoweb/tornado/issues/2608

https://www.tornadoweb.org/en/stable/releases/v6.0.4.html#general-changes
